/*
  Base de estádios do futebol argentino (Torneo Clausura, Copa Argentina,
  Primera Nacional).

  Mesmo formato de /estadios.js e /estadios_brasil.js: usado pelo script.js
  para resolver cidade, provincia (regiao) e coordenadas dos jogos da
  Argentina quando o campo "estadio" bate com um destes nomes, e também
  como base para o fallback "estádio mandante padrão" (a maioria dos jogos
  da AFA não vem com estádio explícito na fonte).
*/

window.ESTADIOS_ARGENTINA = [
  {
    nome: "Estadio Monumental Antonio Vespucio Liberti",
    aliases: ["monumental", "estadio monumental", "river plate estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.5453,
    lng: -58.4497,
  },
  {
    nome: "Estadio Alberto J. Armando (La Bombonera)",
    aliases: ["la bombonera", "bombonera", "estadio alberto j armando", "estadio alberto jose armando", "estadio alberto josé armando"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6356,
    lng: -58.3648,
  },
  {
    nome: "Estadio Presidente Perón (Cilindro)",
    aliases: ["cilindro", "estadio presidente peron", "racing club estadio"],
    cidade: "Avellaneda",
    regiao: "Buenos Aires",
    lat: -34.6656,
    lng: -58.3897,
  },
  {
    nome: "Estadio Libertadores de América",
    aliases: ["libertadores de america", "independiente estadio"],
    cidade: "Avellaneda",
    regiao: "Buenos Aires",
    lat: -34.6656,
    lng: -58.3719,
  },
  {
    nome: "Estadio Pedro Bidegain (Nuevo Gasómetro)",
    aliases: ["nuevo gasometro", "pedro bidegain", "san lorenzo estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6524,
    lng: -58.4009,
  },
  {
    nome: "Estadio Tomás Adolfo Ducó",
    aliases: ["tomas duco", "estadio huracan"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6367,
    lng: -58.4189,
  },
  {
    nome: "Estadio José Amalfitani",
    aliases: ["jose amalfitani", "amalfitani", "velez estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6417,
    lng: -58.5228,
  },
  {
    nome: "Estadio UNO (Jorge Luis Hirschi)",
    aliases: ["estadio uno", "jorge luis hirschi", "estudiantes la plata estadio"],
    cidade: "La Plata",
    regiao: "Buenos Aires",
    lat: -34.9750,
    lng: -57.9506,
  },
  {
    nome: "Estadio Juan Carmelo Zerillo (Bosque)",
    aliases: ["estadio bosque", "juan carmelo zerillo", "gimnasia la plata estadio"],
    cidade: "La Plata",
    regiao: "Buenos Aires",
    lat: -34.9117,
    lng: -57.9503,
  },
  {
    nome: "Estadio Mario Alberto Kempes",
    aliases: ["mario kempes", "estadio kempes", "talleres estadio"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.3350,
    lng: -64.2444,
  },
  {
    nome: "Estadio Julio César Villagra (Gigante de Alberdi)",
    aliases: ["gigante de alberdi", "julio cesar villagra", "belgrano estadio", "belgrano cba", "belgrano (cba"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.4272,
    lng: -64.2069,
  },
  {
    nome: "Estadio Gigante de Arroyito",
    aliases: ["gigante de arroyito", "arroyito", "rosario central estadio"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9425,
    lng: -60.6425,
  },
  {
    nome: "Estadio Marcelo Bielsa (Coloso del Parque)",
    aliases: ["coloso del parque", "marcelo bielsa", "newell's estadio", "newells estadio", "newell's old boys", "newells old boys"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9494,
    lng: -60.6767,
  },
  {
    nome: "Estadio 15 de Abril",
    aliases: ["15 de abril", "union santa fe estadio"],
    cidade: "Santa Fe",
    regiao: "Santa Fe",
    lat: -31.6333,
    lng: -60.7000,
  },
  {
    nome: "Estadio Monumental José Fierro",
    aliases: ["jose fierro", "atletico tucuman estadio"],
    cidade: "San Miguel de Tucumán",
    regiao: "Tucumán",
    lat: -26.8236,
    lng: -65.2564,
  },
  {
    nome: "Estadio Madre de Ciudades",
    aliases: ["madre de ciudades", "central cordoba santiago estadio"],
    cidade: "Santiago del Estero",
    regiao: "Santiago del Estero",
    lat: -27.7951,
    lng: -64.2431,
  },
  {
    nome: "Estadio Florencio Sola",
    aliases: ["florencio sola", "banfield estadio"],
    cidade: "Banfield",
    regiao: "Buenos Aires",
    lat: -34.7458,
    lng: -58.3944,
  },
  {
    nome: "Estadio Ciudad de Lanús (Néstor Díaz Pérez)",
    aliases: ["ciudad de lanus", "nestor diaz perez", "lanus estadio"],
    cidade: "Lanús",
    regiao: "Buenos Aires",
    lat: -34.7044,
    lng: -58.3919,
  },
  {
    nome: "Estadio Ciudad de Vicente López",
    aliases: ["ciudad de vicente lopez", "platense estadio"],
    cidade: "Vicente López",
    regiao: "Buenos Aires",
    lat: -34.5233,
    lng: -58.4886,
  },
  {
    nome: "Estadio José Dellagiovanna (La Candela)",
    aliases: ["la candela", "jose dellagiovanna", "tigre estadio"],
    cidade: "Victoria (Tigre)",
    regiao: "Buenos Aires",
    lat: -34.4494,
    lng: -58.5389,
  },
  {
    nome: "Estadio Diego Armando Maradona",
    aliases: ["estadio maradona", "argentinos juniors estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6089,
    lng: -58.4794,
  },
  {
    nome: "Estadio Eva Perón",
    aliases: ["eva peron", "sarmiento junin estadio"],
    cidade: "Junín",
    regiao: "Buenos Aires",
    lat: -34.5883,
    lng: -60.9500,
  },
  {
    nome: "Estadio Norberto Tomaghello",
    aliases: ["norberto tomaghello", "defensa y justicia estadio"],
    cidade: "Florencio Varela",
    regiao: "Buenos Aires",
    lat: -34.8206,
    lng: -58.3789,
  },
  {
    nome: "Estadio José María Minella",
    aliases: ["jose maria minella", "aldosivi estadio"],
    cidade: "Mar del Plata",
    regiao: "Buenos Aires",
    lat: -37.9633,
    lng: -57.5750,
  },
  {
    nome: "Estadio Guillermo Laza",
    aliases: ["guillermo laza", "deportivo riestra estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6650,
    lng: -58.4436,
  },
  {
    nome: "Estadio Bautista Gargantini",
    aliases: ["bautista gargantini", "independiente rivadavia estadio"],
    cidade: "Mendoza",
    regiao: "Mendoza",
    lat: -32.8908,
    lng: -68.8272,
  },
  {
    nome: "Estadio Víctor Antonio Legrotaglie",
    aliases: ["victor legrotaglie", "gimnasia mendoza estadio"],
    cidade: "Mendoza",
    regiao: "Mendoza",
    lat: -32.8850,
    lng: -68.8419,
  },
  {
    nome: "Estadio Antonio Candini",
    aliases: ["antonio candini", "estudiantes rio cuarto estadio"],
    cidade: "Río Cuarto",
    regiao: "Córdoba",
    lat: -33.1232,
    lng: -64.3492,
  },
  {
    nome: "Estadio Presidente Perón (Instituto)",
    aliases: ["instituto estadio", "estadio instituto atletico central cordoba"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.4200,
    lng: -64.1836,
  },
  {
    nome: "Estadio Claudio Tapia (Barracas Central)",
    aliases: ["barracas central estadio", "claudio tapia estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6420,
    lng: -58.3894,
  },
  {
    nome: "Estadio Padre Ernesto Martearena",
    aliases: ["padre e. martearena", "padre martearena", "martearena"],
    cidade: "Salta",
    regiao: "Salta",
    lat: -24.7859,
    lng: -65.4064,
  },
  {
    nome: "Estadio Malvinas Argentinas",
    aliases: ["malvinas argentinas", "estadio ciudad de mendoza"],
    cidade: "Mendoza",
    regiao: "Mendoza",
    lat: -32.8869,
    lng: -68.8628,
    fonte: "manual/aproximado (Parque General San Martín, Mendoza) - usado por Independiente Rivadavia em competições CONMEBOL",
  },

  /* ===================================================================
     Primera Nacional (2ª divisão Argentina) — adicionados na auditoria
     de coordenadas. Coordenadas em nível de cidade (aproximado).
     =================================================================== */
  {
    nome: "Estadio Islas Malvinas",
    aliases: ["islas malvinas"],
    cidade: "Buenos Aires (Floresta)",
    regiao: "Buenos Aires",
    lat: -34.6339,
    lng: -58.5008,
    fonte: "manual/aproximado (Floresta, CABA — mandante All Boys)",
  },
  {
    nome: "Estadio Nuevo Francisco Urbano",
    aliases: ["francisco urbano", "nuevo francisco urbano"],
    cidade: "Morón",
    regiao: "Buenos Aires",
    lat: -34.6531,
    lng: -58.6197,
    fonte: "manual/aproximado (cidade de Morón — mandante Deportivo Morón)",
  },
  {
    nome: "Estadio Eduardo Gallardón",
    aliases: ["eduardo gallardon", "eduardo gallardón"],
    cidade: "Lomas de Zamora",
    regiao: "Buenos Aires",
    lat: -34.7683,
    lng: -58.3997,
    fonte: "manual/aproximado (cidade de Lomas de Zamora — mandante Los Andes)",
  },
  {
    nome: "Estadio César Luis Menotti",
    aliases: ["cesar luis menotti", "césar luis menotti"],
    cidade: "San Miguel",
    regiao: "Buenos Aires",
    lat: -34.5417,
    lng: -58.7167,
    fonte: "manual/aproximado (cidade de San Miguel — mandante Club San Miguel)",
  },
  {
    nome: "Estadio Gigante del Norte",
    aliases: ["gigante del norte"],
    cidade: "Salta",
    regiao: "Salta",
    lat: -24.7859,
    lng: -65.4117,
    fonte: "manual/aproximado (cidade de Salta — mandante Gimnasia y Tiro)",
  },
  {
    nome: "Estadio 23 de Agosto",
    aliases: ["23 de agosto"],
    cidade: "San Salvador de Jujuy",
    regiao: "Jujuy",
    lat: -24.1858,
    lng: -65.2995,
    fonte: "manual/aproximado (cidade de San Salvador de Jujuy — mandante Gimnasia y Esgrima de Jujuy)",
  },
  {
    nome: "Estadio La Ciudadela",
    aliases: ["la ciudadela"],
    cidade: "San Miguel de Tucumán",
    regiao: "Tucumán",
    lat: -26.8241,
    lng: -65.2226,
    fonte: "manual/aproximado (cidade de Tucumán — mandante San Martín de Tucumán)",
  },
  {
    nome: "Estadio Don León Kolbowski",
    aliases: ["leon kolbowski", "don leon kolbowski"],
    cidade: "Buenos Aires (Villa Crespo)",
    regiao: "Buenos Aires",
    lat: -34.5992,
    lng: -58.4436,
    fonte: "manual/aproximado (Villa Crespo, CABA — mandante Atlanta)",
  },
  {
    nome: "Estadio Presidente Perón",
    aliases: ["presidente peron", "presidente perón"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.3833,
    lng: -64.2333,
    fonte: "manual/aproximado (Barrio Nueva Italia, Córdoba — mandante Racing de Córdoba)",
  },
  {
    nome: "Estadio Ofelia Rosenzuaig",
    aliases: ["ofelia rosenzuaig"],
    cidade: "Carlos Casares",
    regiao: "Buenos Aires",
    lat: -35.6167,
    lng: -61.3833,
    fonte: "manual/aproximado (cidade de Carlos Casares — mandante Agropecuario Argentino)",
  },
  {
    nome: "Estadio Monumental Alfredo Terrera",
    aliases: ["alfredo terrera", "monumental alfredo terrera"],
    cidade: "Rafaela",
    regiao: "Santa Fe",
    lat: -31.2503,
    lng: -61.4867,
    fonte: "manual/aproximado (cidade de Rafaela — mandante Atlético de Rafaela)",
  },
  {
    nome: "Estadio Doctor Osvaldo Baletto",
    aliases: ["osvaldo baletto", "doctor osvaldo baletto"],
    cidade: "Avellaneda (Isla Maciel / Dock Sud)",
    regiao: "Buenos Aires",
    lat: -34.6544,
    lng: -58.3467,
    fonte: "manual/aproximado (Isla Maciel, Dock Sud, Avellaneda — mandante San Telmo) - Wikipedia",
  },
  {
    nome: "Estadio 20 de Octubre",
    aliases: ["20 de octubre"],
    cidade: "Tristán Suárez (Ezeiza)",
    regiao: "Buenos Aires",
    lat: -34.8103,
    lng: -58.5306,
    fonte: "manual/aproximado (Tristán Suárez, Partido de Ezeiza — mandante Tristán Suárez) - Wikipedia",
  },
  {
    nome: "Estadio Brigadier General Estanislao López",
    aliases: ["brigadier general estanislao lopez", "brigadier lopez", "cementerio de los elefantes"],
    cidade: "Santa Fe",
    regiao: "Santa Fe",
    lat: -31.6632,
    lng: -60.7252,
    fonte: "manual/aproximado (cidade de Santa Fe — mandante Colón) - Wikipedia/Wikimapia",
  },
  {
    nome: "Estadio Ciudad de Libertad (Raúl Roberto Sabureau)",
    aliases: ["ciudad de libertad", "raul roberto sabureau"],
    cidade: "Libertad",
    regiao: "Buenos Aires",
    lat: -34.7392,
    lng: -58.7161,
    fonte: "manual/aproximado (Libertad, Buenos Aires — mandante F.C. Midland) - Wikipedia",
  },
  {
    nome: "Estadio Arturo Miranda (La Isla)",
    aliases: ["arturo miranda", "la isla"],
    cidade: "Santiago del Estero",
    regiao: "Santiago del Estero",
    lat: -27.7834,
    lng: -64.2669,
    fonte: "manual/aproximado (cidade de Santiago del Estero — mandante Güemes) - Wikipedia",
  },

  /* ===================================================================
     Primera B, Primera C, Promocional Amateur e Futebol Feminino
     (predios de treino). Coordenadas em nivel de bairro/cidade
     (aproximado - fontes: Wikipedia, promiedos, futbolargentino,
     soccergaming forums de mods). Alguns times amadores nao tem
     estadio proprio e usam o campo de outro clube (mapeado via
     ESTADIO_MANDANTE_PADRAO_ARGENTINA em script.js).
     =================================================================== */
  {
    nome: "Estadio Municipal Carlos Barraza",
    aliases: ["estadio municipal carlos barraza", "carlos barraza"],
    cidade: "Pilar",
    regiao: "Buenos Aires",
    lat: -34.4586,
    lng: -58.9138,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Hugo Moyano",
    aliases: ["estadio hugo moyano", "hugo moyano"],
    cidade: "Esteban Echeverría",
    regiao: "Buenos Aires",
    lat: -34.7728,
    lng: -58.4863,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Genacio Sálice",
    aliases: ["estadio genacio salice", "genacio salice"],
    cidade: "Berisso",
    regiao: "Buenos Aires",
    lat: -34.8712,
    lng: -57.8853,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Francisco Boga",
    aliases: ["estadio francisco boga", "francisco boga"],
    cidade: "Burzaco",
    regiao: "Buenos Aires",
    lat: -34.8508,
    lng: -58.3843,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Julio Humberto Grondona",
    aliases: ["estadio julio humberto grondona", "julio humberto grondona"],
    cidade: "Sarandí",
    regiao: "Buenos Aires",
    lat: -34.6892,
    lng: -58.3467,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Gigante de Villa Fox",
    aliases: ["estadio gigante de villa fox", "gigante de villa fox"],
    cidade: "Zárate",
    regiao: "Buenos Aires",
    lat: -34.0961,
    lng: -59.0269,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ciudad de Laferrere (Garrafa Sánchez)",
    aliases: ["estadio ciudad de laferrere garrafa sanchez", "ciudad de laferrere", "garrafa sanchez"],
    cidade: "La Matanza",
    regiao: "Buenos Aires",
    lat: -34.7423,
    lng: -58.5951,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Armenia",
    aliases: ["estadio armenia"],
    cidade: "Ingeniero Maschwitz",
    regiao: "Buenos Aires",
    lat: -34.3639,
    lng: -58.7539,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Juan Carlos Brieva (Merlo Norte)",
    aliases: ["estadio juan carlos brieva merlo norte", "juan carlos brieva", "merlo norte"],
    cidade: "Merlo",
    regiao: "Buenos Aires",
    lat: -34.6653,
    lng: -58.7278,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Barraca Quilmeña",
    aliases: ["estadio barraca quilmena", "barraca quilmena"],
    cidade: "Quilmes",
    regiao: "Buenos Aires",
    lat: -34.7203,
    lng: -58.2545,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Lorenzo Arandilla",
    aliases: ["estadio lorenzo arandilla", "lorenzo arandilla"],
    cidade: "Adrogué",
    regiao: "Buenos Aires",
    lat: -34.7994,
    lng: -58.3888,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Carlos Alberto Sacaan",
    aliases: ["estadio carlos alberto sacaan", "carlos alberto sacaan", "carlos sacaan"],
    cidade: "Ituzaingó",
    regiao: "Buenos Aires",
    lat: -34.6614,
    lng: -58.6708,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Pampa y Mañones (Excursionistas)",
    aliases: ["estadio pampa y manones excursionistas", "pampa y manones", "pampa y minones"],
    cidade: "Buenos Aires (Belgrano)",
    regiao: "Buenos Aires",
    lat: -34.5631,
    lng: -58.4569,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Alfredo Ramos",
    aliases: ["estadio alfredo ramos", "alfredo ramos"],
    cidade: "San Miguel",
    regiao: "Buenos Aires",
    lat: -34.5407,
    lng: -58.7122,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Juan Antonio Arias",
    aliases: ["estadio juan antonio arias", "juan antonio arias", "juan antoni arias"],
    cidade: "Buenos Aires (Liniers)",
    regiao: "Buenos Aires",
    lat: -34.6414,
    lng: -58.5236,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio República de Italia (Sportivo Italiano)",
    aliases: ["estadio republica de italia sportivo italiano", "republica de italia", "dep italiano estadio"],
    cidade: "Villa Domínico",
    regiao: "Buenos Aires",
    lat: -34.6975,
    lng: -58.3308,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Pablo Comelli",
    aliases: ["estadio pablo comelli", "pablo comelli"],
    cidade: "Remedios de Escalada",
    regiao: "Buenos Aires",
    lat: -34.7089,
    lng: -58.3931,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Carlos V",
    aliases: ["estadio carlos v", "carlos v"],
    cidade: "Jáuregui (Luján)",
    regiao: "Buenos Aires",
    lat: -34.5701,
    lng: -59.0522,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Monumental de Villa Lynch (UAI Urquiza)",
    aliases: ["estadio monumental de villa lynch uai urquiza", "monumental de villa lynch"],
    cidade: "Villa Lynch",
    regiao: "Buenos Aires",
    lat: -34.5906,
    lng: -58.5486,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio José Manuel Moreno",
    aliases: ["estadio jose manuel moreno", "jose manuel moreno"],
    cidade: "Merlo",
    regiao: "Buenos Aires",
    lat: -34.6653,
    lng: -58.7278,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Coliseo de Mitre y Puccini (Villa Dálmine)",
    aliases: ["estadio coliseo de mitre y puccini villa dalmine", "coliseo de mitre y puccini"],
    cidade: "Campana",
    regiao: "Buenos Aires",
    lat: -34.1655,
    lng: -58.9592,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio De los Inmigrantes (Sportivo Dock Sud)",
    aliases: ["estadio de los inmigrantes sportivo dock sud", "de los inmigrantes"],
    cidade: "Dock Sud (Avellaneda)",
    regiao: "Buenos Aires",
    lat: -34.6511,
    lng: -58.3411,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Nueva España (Dep. Español)",
    aliases: ["estadio nueva espana dep espanol", "nueva espana"],
    cidade: "Buenos Aires (Villa Lugano)",
    regiao: "Buenos Aires",
    lat: -34.6786,
    lng: -58.4744,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Jorge Alfredo Arín (Cañuelas)",
    aliases: ["estadio jorge alfredo arin canuelas", "jorge alfredo arin"],
    cidade: "Cañuelas",
    regiao: "Buenos Aires",
    lat: -35.0517,
    lng: -58.7628,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio José María Moraños",
    aliases: ["estadio jose maria moranos", "jose maria moranos"],
    cidade: "Buenos Aires (Villa Lugano)",
    regiao: "Buenos Aires",
    lat: -34.6786,
    lng: -58.4744,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Norman Lee",
    aliases: ["estadio norman lee", "norman lee"],
    cidade: "Berazategui",
    regiao: "Buenos Aires",
    lat: -34.7642,
    lng: -58.2119,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio 12 de Octubre (Def. de Cambaceres)",
    aliases: ["estadio 12 de octubre def de cambaceres", "12 de octubre"],
    cidade: "Ensenada",
    regiao: "Buenos Aires",
    lat: -34.8674,
    lng: -57.9082,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Francisco Ghersinich (El Porvenir)",
    aliases: ["estadio francisco ghersinich el porvenir", "francisco ghersinich"],
    cidade: "Gerli (Avellaneda)",
    regiao: "Buenos Aires",
    lat: -34.6803,
    lng: -58.3667,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Gabino Sosa",
    aliases: ["estadio gabino sosa", "gabino sosa"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9468,
    lng: -60.6393,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ricardo Puga",
    aliases: ["estadio ricardo puga", "ricardo puga"],
    cidade: "San Miguel",
    regiao: "Buenos Aires",
    lat: -34.5233,
    lng: -58.7194,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ciudad Evita",
    aliases: ["estadio ciudad evita", "ciudad evita"],
    cidade: "La Matanza (Ciudad Evita)",
    regiao: "Buenos Aires",
    lat: -34.7443,
    lng: -58.5595,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ramón Roque Martín",
    aliases: ["estadio ramon roque martin", "ramon roque martin"],
    cidade: "Buenos Aires (Villa Lugano)",
    regiao: "Buenos Aires",
    lat: -34.6786,
    lng: -58.4744,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio José Martín Olaeta",
    aliases: ["estadio jose martin olaeta", "jose martin olaeta"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9468,
    lng: -60.6393,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Predio Cacique (Central Ballester)",
    aliases: ["estadio predio cacique central ballester", "predio cacique"],
    cidade: "Villa Ballester",
    regiao: "Buenos Aires",
    lat: -34.5433,
    lng: -58.5628,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Rodolfo Vicente Capocasa (Claypole)",
    aliases: ["estadio rodolfo vicente capocasa claypole", "rodolfo vicente capocasa"],
    cidade: "Claypole",
    regiao: "Buenos Aires",
    lat: -34.8267,
    lng: -58.3608,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Enrique VI (General Lamadrid)",
    aliases: ["estadio enrique vi general lamadrid", "enrique vi"],
    cidade: "Buenos Aires (Villa Lugano)",
    regiao: "Buenos Aires",
    lat: -34.6786,
    lng: -58.4744,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ciudad de San Miguel (Juventud Unida)",
    aliases: ["estadio ciudad de san miguel juventud unida", "ciudad de san miguel"],
    cidade: "San Miguel",
    regiao: "Buenos Aires",
    lat: -34.5407,
    lng: -58.7122,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Rubén Carlos Vallejos (Puerto Nuevo)",
    aliases: ["estadio ruben carlos vallejos puerto nuevo", "ruben carlos vallejos"],
    cidade: "Buenos Aires (La Boca)",
    regiao: "Buenos Aires",
    lat: -34.6345,
    lng: -58.3616,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Saturnino Moure (Victoriano Arenas)",
    aliases: ["estadio saturnino moure victoriano arenas", "saturnino moure"],
    cidade: "Villa Domínico (Avellaneda)",
    regiao: "Buenos Aires",
    lat: -34.6975,
    lng: -58.3308,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Municipal de Mercedes (Liga Mercedina)",
    aliases: ["estadio municipal de mercedes liga mercedina", "liga mercedina", "municipal de mercedes"],
    cidade: "Mercedes (Buenos Aires)",
    regiao: "Buenos Aires",
    lat: -34.6512,
    lng: -59.4309,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Beto Larrosa (Sacachispas)",
    aliases: ["estadio beto larrosa sacachispas", "beto larrosa"],
    cidade: "Buenos Aires (Villa Soldati)",
    regiao: "Buenos Aires",
    lat: -34.6733,
    lng: -58.4386,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Municipal de Luján",
    aliases: ["estadio municipal de lujan", "municipal de lujan"],
    cidade: "Luján",
    regiao: "Buenos Aires",
    lat: -34.5701,
    lng: -59.108,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio General Rodríguez (L.N. Alem)",
    aliases: ["estadio general rodriguez l n alem", "general rodriguez estadio"],
    cidade: "General Rodríguez",
    regiao: "Buenos Aires",
    lat: -34.6089,
    lng: -58.9556,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Juan Pasquale",
    aliases: ["estadio juan pasquale", "juan pasquale"],
    cidade: "Buenos Aires (Núñez)",
    regiao: "Buenos Aires",
    lat: -34.5453,
    lng: -58.4636,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Nuevo Francisco Urbano (Sp. Barracas)",
    aliases: ["estadio nuevo francisco urbano sp barracas", "nuevo francisco urbano sp barracas"],
    cidade: "Morón",
    regiao: "Buenos Aires",
    lat: -34.6531,
    lng: -58.6198,
    fonte: "manual/aproximado",
  },
  {
    nome: "Cancha 3 Predio Santo Domingo (Independiente Femenino)",
    aliases: ["cancha 3 predio santo domingo independiente femenino", "cancha 3 predio santo domingo"],
    cidade: "Villa Domínico (Avellaneda)",
    regiao: "Buenos Aires",
    lat: -34.6975,
    lng: -58.3308,
    fonte: "manual/aproximado",
  },
  {
    nome: "Predio Bella Vista (Newell's Femenino)",
    aliases: ["predio bella vista newell s femenino", "predio bella vista"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9468,
    lng: -60.6393,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio La Boutique (Talleres Femenino)",
    aliases: ["estadio la boutique talleres femenino", "estadio la boutique", "la boutique"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.4201,
    lng: -64.1888,
    fonte: "manual/aproximado",
  },
  {
    nome: "River Camp (River Femenino)",
    aliases: ["river camp river femenino", "river camp"],
    cidade: "Ezeiza",
    regiao: "Buenos Aires",
    lat: -34.8306,
    lng: -58.5316,
    fonte: "manual/aproximado",
  },
  {
    nome: "Sintético Caballito (Ferro Femenino)",
    aliases: ["sintetico caballito ferro femenino", "sintetico caballito"],
    cidade: "Buenos Aires (Caballito)",
    regiao: "Buenos Aires",
    lat: -34.6178,
    lng: -58.4386,
    fonte: "manual/aproximado",
  },
  {
    nome: "Predio Estancia Chica - Cancha 1 (Gimnasia La Plata Femenino)",
    aliases: ["predio estancia chica cancha 1 gimnasia la plata femenino", "predio estancia chica cancha 1", "predio estancia chica"],
    cidade: "La Plata",
    regiao: "Buenos Aires",
    lat: -34.9214,
    lng: -57.9544,
    fonte: "manual/aproximado",
  },
  {
    nome: "Predio Tita (Racing Femenino)",
    aliases: ["predio tita racing femenino", "predio tita"],
    cidade: "Avellaneda",
    regiao: "Buenos Aires",
    lat: -34.6626,
    lng: -58.3654,
    fonte: "manual/aproximado",
  },
  {
    nome: "Ciudad Deportiva (San Lorenzo Femenino)",
    aliases: ["ciudad deportiva san lorenzo femenino", "ciudad deportiva san lorenzo"],
    cidade: "Buenos Aires (Bajo Flores)",
    regiao: "Buenos Aires",
    lat: -34.6497,
    lng: -58.4272,
    fonte: "manual/aproximado",
  },
  {
    nome: "Campo de Deportes (Banfield Femenino)",
    aliases: ["campo de deportes banfield femenino", "campo de deportes banfield"],
    cidade: "Banfield",
    regiao: "Buenos Aires",
    lat: -34.7439,
    lng: -58.3947,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Tres de Febrero",
    aliases: ["tres de febrero", "estadio tres de febrero"],
    cidade: "José Ingenieros",
    regiao: "Buenos Aires",
    lat: -34.5963,
    lng: -58.5828,
    fonte: "Wikipedia (Club Almagro) - casa do Almagro",
  },
  {
    nome: "Estadio Abel Sastre (Coliseo del Golfo)",
    aliases: ["abel sastre", "coliseo del golfo", "estadio abel sastre"],
    cidade: "Puerto Madryn",
    regiao: "Chubut",
    lat: -42.7783,
    lng: -65.0361,
    fonte: "Wikipedia (Estadio Abel Sastre) - casa do Deportivo Madryn",
  },
];
