/*
  Base de estádios do Ceará (fonte="FCF" no scrap_fcf_ceara.py).

  Cobre os clubes vistos ao vivo em 17/07/2026:
  - Grandes clubes de Fortaleza (Ceará, Fortaleza, Ferroviário, Floresta,
    Tiradentes) e do Cearense Série C 2026 (Pacatuba, Limoeiro, Vila Real,
    Tianguá, Calouros do Ar, Acopiara, Palmácia).
  - Times do interior vistos no widget "Jogos Anteriores" da home da FCF
    (Horizonte, Maracanã, Caucaia, Barbalha, Crato, Itapipoca, Icasa,
    Guarany de Sobral, Iguatu, Quixadá, Juventus, Pacajus).

  Coordenadas exatas quando achadas (Wikipedia/fonte oficial); quando só
  achei a cidade-sede (sem endereço exato do estádio), uso o centro da
  cidade como aproximação, igual ao padrão já usado em estadios_peru.js
  ("aproximado").
*/
window.ESTADIOS_CEARA = [
  {
    nome: "Estádio Presidente Vargas",
    aliases: ["pv", "presidente vargas"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.7654,
    lng: -38.5459,
    fonte: "Wikipedia (Estádio Presidente Vargas, Ceará) - casa de Ceará/Ferroviário/Floresta/Tiradentes/América-CE",
  },
  {
    nome: "Arena Castelão",
    aliases: ["castelao", "castelão", "estadio placido aderaldo castelo", "governador placido castelo"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.8076,
    lng: -38.5219,
    fonte: "Wikipedia (Arena Castelão) - casa do Fortaleza",
  },
  {
    nome: "CT Ribamar Bezerra",
    aliases: ["ct ribamar bezerra", "ribamar bezerra"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.7500,
    lng: -38.5700,
    fonte: "aproximado (cidade de Fortaleza) - CT do Fortaleza usado em categorias de base",
  },
  {
    nome: "Franzé Moraes",
    aliases: ["franze moraes"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.7500,
    lng: -38.5700,
    fonte: "aproximado (cidade de Fortaleza) - CT/campo do Ceará usado em categorias de base",
  },
  {
    nome: "Elzir Cabral",
    aliases: ["elzir cabral"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.7500,
    lng: -38.5700,
    fonte: "aproximado (cidade de Fortaleza) - campo do Ferroviário usado em categorias de base",
  },
  {
    nome: "Estádio Domingão",
    aliases: ["domingao", "domingão"],
    cidade: "Horizonte",
    regiao: "Ceará",
    lat: -4.0983,
    lng: -38.4939,
    fonte: "aproximado (centro de Horizonte/CE) - casa do Horizonte e Maranguape",
  },
  {
    nome: "Estádio Almir Dutra",
    aliases: ["almir dutra"],
    cidade: "Maracanaú",
    regiao: "Ceará",
    lat: -3.8767,
    lng: -38.6256,
    fonte: "aproximado (centro de Maracanaú/CE) - casa do Maracanã",
  },
  {
    nome: "Estádio Raimundo de Oliveira",
    aliases: ["raimundo de oliveira"],
    cidade: "Caucaia",
    regiao: "Ceará",
    lat: -3.7361,
    lng: -38.6531,
    fonte: "aproximado (centro de Caucaia/CE) - casa do Caucaia",
  },
  {
    nome: "Estádio Inaldão (Lírio Callou)",
    aliases: ["inaldao", "inaldão", "lirio callou", "lírio callou"],
    cidade: "Barbalha",
    regiao: "Ceará",
    lat: -7.3006,
    lng: -39.3020,
    fonte: "aproximado (centro de Barbalha/CE) - casa do Barbalha",
  },
  {
    nome: "Estádio Mirandão",
    aliases: ["mirandao", "mirandão"],
    cidade: "Crato",
    regiao: "Ceará",
    lat: -7.2342,
    lng: -39.4097,
    fonte: "aproximado (centro do Crato/CE) - casa do Crato",
  },
  {
    nome: "Estádio Perilo Teixeira",
    aliases: ["perilo teixeira"],
    cidade: "Itapipoca",
    regiao: "Ceará",
    lat: -3.4936,
    lng: -39.5786,
    fonte: "aproximado (centro de Itapipoca/CE) - casa do Itapipoca",
  },
  {
    nome: "Arena Romeirão (Estádio Mauro Sampaio)",
    aliases: ["arena romeirao", "arena romeirão", "romeirao", "romeirão", "mauro sampaio"],
    cidade: "Juazeiro do Norte",
    regiao: "Ceará",
    lat: -7.2130,
    lng: -39.3155,
    fonte: "aproximado (centro de Juazeiro do Norte/CE) - casa do Icasa e Guarani de Juazeiro",
  },
  {
    nome: "Estádio Carneirão",
    aliases: ["carneirao", "carneirão"],
    cidade: "Juazeiro do Norte",
    regiao: "Ceará",
    lat: -7.2130,
    lng: -39.3155,
    fonte: "aproximado (centro de Juazeiro do Norte/CE) - casa do Juventus-CE",
  },
  {
    nome: "Estádio Morenão (Agenorzão)",
    aliases: ["morenao", "morenão", "agenorzao", "agenorzão"],
    cidade: "Iguatu",
    regiao: "Ceará",
    lat: -6.3597,
    lng: -39.2986,
    fonte: "aproximado (centro de Iguatu/CE) - casa do Iguatu",
  },
  {
    nome: "Estádio Abilhão",
    aliases: ["abilhao", "abilhão"],
    cidade: "Quixadá",
    regiao: "Ceará",
    lat: -4.9714,
    lng: -39.0153,
    fonte: "aproximado (centro de Quixadá/CE) - casa do Quixadá",
  },
  {
    nome: "Estádio Junco",
    aliases: ["junco", "estadio junco"],
    cidade: "Sobral",
    regiao: "Ceará",
    lat: -3.6880,
    lng: -40.3494,
    fonte: "aproximado (centro de Sobral/CE) - casa do Vila Real e Guarany de Sobral (Cearense Série C 2026)",
  },
  {
    nome: "Estádio Municipal de Limoeiro do Norte",
    aliases: ["limoeiro"],
    cidade: "Limoeiro do Norte",
    regiao: "Ceará",
    lat: -5.1478,
    lng: -38.0994,
    fonte: "aproximado (centro de Limoeiro do Norte/CE) - casa do Esporte Limoeiro (Cearense Série C 2026)",
  },
  {
    nome: "Estádio Municipal de Tianguá",
    aliases: ["tiangua", "tianguá"],
    cidade: "Tianguá",
    regiao: "Ceará",
    lat: -3.7314,
    lng: -40.9922,
    fonte: "aproximado (centro de Tianguá/CE) - casa do Tianguá EC (Cearense Série C 2026)",
  },
  {
    nome: "Estádio Municipal de Acopiara",
    aliases: ["acopiara"],
    cidade: "Acopiara",
    regiao: "Ceará",
    lat: -6.0872,
    lng: -39.4506,
    fonte: "aproximado (centro de Acopiara/CE) - casa do FC Acopiara (Cearense Série C 2026)",
  },
  {
    nome: "Estádio Municipal de Palmácia",
    aliases: ["palmacia", "palmácia"],
    cidade: "Palmácia",
    regiao: "Ceará",
    lat: -4.0333,
    lng: -38.7000,
    fonte: "aproximado (centro de Palmácia/CE) - casa do Palmácia EC (Cearense Série C 2026)",
  },
  {
    nome: "Estádio Municipal de Pacatuba",
    aliases: ["pacatuba"],
    cidade: "Pacatuba",
    regiao: "Ceará",
    lat: -3.9836,
    lng: -38.6208,
    fonte: "aproximado (centro de Pacatuba/CE) - casa do Pacatuba (Cearense Série C 2026)",
  },
];

// Fallback por mandante (usado só quando o jogo não vem com nome de
// estádio - a maioria dos jogos da FCF já traz o estádio no texto, então
// esse mapa é reforço/exceção, não o caminho principal).
window.ESTADIO_MANDANTE_PADRAO_FCF = {
  "ceara": "pv",
  "ceará": "pv",
  "fortaleza": "castelao",
  "ferroviario": "pv",
  "ferroviário": "pv",
  "floresta": "pv",
  "tiradentes": "pv",
  "horizonte": "domingao",
  "maranguape": "domingao",
  "maracana": "almir dutra",
  "maracanã": "almir dutra",
  "caucaia": "raimundo de oliveira",
  "barbalha": "inaldao",
  "crato": "mirandao",
  "itapipoca": "perilo teixeira",
  "icasa": "arena romeirao",
  "guarany de sobral": "arena romeirao",
  "guarani de juazeiro": "arena romeirao",
  "juventus": "carneirao",
  "iguatu": "morenao",
  "quixada": "abilhao",
  "quixadá": "abilhao",
  "vila real": "junco",
  "esporte limoeiro": "limoeiro",
  "limoeiro": "limoeiro",
  "tiangua": "tiangua",
  "tianguá": "tiangua",
  "fc acopiara": "acopiara",
  "acopiara": "acopiara",
  "palmacia": "palmacia",
  "palmácia": "palmacia",
  "pacatuba": "pacatuba",
};
