/*
  Base de estádios do futebol brasileiro (CBF: Série A/B/C/D, Copa do Brasil).

  Mesmo formato de /estadios.js (Chile), usado pelo script.js para
  resolver cidade, estado (regiao) e coordenadas dos jogos do Brasil
  quando o campo "estadio" do scraper bate com um destes nomes.

  Campos:
  - nome: nome principal
  - aliases: variações do nome que podem aparecer no JSON
  - cidade
  - regiao: estado (UF por extenso)
  - lat/lng
*/

window.ESTADIOS_BRASIL = [
  {
    nome: "Allianz Parque",
    aliases: ["allianz parque", "arena palmeiras"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.5273,
    lng: -46.6783,
  },
  {
    nome: "Arena Condá",
    aliases: ["arena conda", "arena condá"],
    cidade: "Chapecó",
    regiao: "Santa Catarina",
    lat: -27.0910,
    lng: -52.6222,
  },
  {
    nome: "Arena Fonte Nova",
    aliases: ["arena fonte nova", "fonte nova", "itaipava arena fonte nova"],
    cidade: "Salvador",
    regiao: "Bahia",
    lat: -12.9836,
    lng: -38.5054,
  },
  {
    nome: "Arena MRV",
    aliases: ["arena mrv"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.8657,
    lng: -44.0994,
  },
  {
    nome: "Arena da Baixada",
    aliases: ["arena da baixada", "ligga arena", "joaquim americo"],
    cidade: "Curitiba",
    regiao: "Paraná",
    lat: -25.4483,
    lng: -49.2731,
  },
  {
    nome: "Arena do Grêmio",
    aliases: ["arena do gremio", "arena do grêmio"],
    cidade: "Porto Alegre",
    regiao: "Rio Grande do Sul",
    lat: -29.9827,
    lng: -51.0680,
  },
  {
    nome: "Estádio Barradão",
    aliases: ["barradão", "barradao"],
    cidade: "Salvador",
    regiao: "Bahia",
    lat: -12.9481,
    lng: -38.4489,
  },
  {
    nome: "Estádio Beira-Rio",
    aliases: ["beira-rio", "beira rio"],
    cidade: "Porto Alegre",
    regiao: "Rio Grande do Sul",
    lat: -30.0653,
    lng: -51.2352,
  },
  {
    nome: "Estádio Couto Pereira",
    aliases: ["couto pereira"],
    cidade: "Curitiba",
    regiao: "Paraná",
    lat: -25.4406,
    lng: -49.2439,
  },
  {
    nome: "Estádio Municipal Cícero de Souza Marques",
    aliases: ["cícero s. marques", "cicero s. marques", "cícero de souza marques", "cicero de souza marques"],
    cidade: "Bragança Paulista",
    regiao: "São Paulo",
    lat: -22.9519,
    lng: -46.5419,
  },
  {
    nome: "Estádio José Maria de Campos Maia",
    aliases: ["josé m. c. maia", "jose m. c. maia", "josé maria de campos maia"],
    cidade: "Mirassol",
    regiao: "São Paulo",
    lat: -20.8181,
    lng: -49.5222,
  },
  {
    nome: "Estádio Olímpico do Pará (Mangueirão)",
    aliases: ["mangueirão", "mangueirao", "olimpico do para"],
    cidade: "Belém",
    regiao: "Pará",
    lat: -1.4108,
    lng: -48.4489,
  },
  {
    nome: "Maracanã",
    aliases: ["maracanã", "maracana", "estadio do maracana"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9121,
    lng: -43.2302,
  },
  {
    nome: "Mineirão",
    aliases: ["mineirão", "mineirao"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.8656,
    lng: -43.9695,
  },
  {
    nome: "MorumBIS",
    aliases: ["morumbis", "morumbi", "estadio cicero pompeu de toledo"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.6003,
    lng: -46.7194,
  },
  {
    nome: "Neo Química Arena",
    aliases: ["neo quimica arena", "neo química arena", "arena corinthians"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.5453,
    lng: -46.4742,
  },
  {
    nome: "Estádio Nilton Santos",
    aliases: ["nilton santos", "engenhão", "engenhao"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8925,
    lng: -43.2300,
  },
  {
    nome: "Estádio São Januário",
    aliases: ["são januário", "sao januario"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8917,
    lng: -43.2286,
  },
  {
    nome: "Estádio Urbano Caldeira (Vila Belmiro)",
    aliases: ["vila belmiro", "urbano caldeira"],
    cidade: "Santos",
    regiao: "São Paulo",
    lat: -23.9469,
    lng: -46.3353,
  },
  {
    nome: "Estádio Santa Cruz",
    aliases: ["santa cruz"],
    cidade: "Ribeirão Preto",
    regiao: "São Paulo",
    lat: -21.1775,
    lng: -47.8103,
  },
  {
    nome: "Estádio Onésio Brasileiro Alvarenga (Serrinha)",
    aliases: ["onésio b. alvarenga", "onesio b. alvarenga", "onésio brasileiro alvarenga", "serrinha"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6764,
    lng: -49.2643,
  },
  {
    nome: "Estádio Augusto Bauer",
    aliases: ["augusto bauer", "augusto"],
    cidade: "Brusque",
    regiao: "Santa Catarina",
    lat: -27.0961,
    lng: -48.9107,
  },
  {
    nome: "Estádio Centenário",
    aliases: ["centenário", "centenario"],
    cidade: "Caxias do Sul",
    regiao: "Rio Grande do Sul",
    lat: -29.1686,
    lng: -51.1794,
  },
  {
    nome: "Arena Pantanal",
    aliases: ["arena pantanal"],
    cidade: "Cuiabá",
    regiao: "Mato Grosso",
    lat: -15.6014,
    lng: -56.1025,
  },
  {
    nome: "Arena Castelão",
    aliases: ["arena castelão", "arena castelao", "castelão", "castelao"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.8071,
    lng: -38.5219,
  },
  {
    nome: "Estádio Heriberto Hülse",
    aliases: ["heriberto hülse", "heriberto hulse"],
    cidade: "Criciúma",
    regiao: "Santa Catarina",
    lat: -28.6775,
    lng: -49.3697,
  },
  {
    nome: "Estádio Jorge Ismael de Biasi",
    aliases: ["jorge ismael de biasi", "jorge de biasi"],
    cidade: "Novo Horizonte",
    regiao: "São Paulo",
    lat: -21.4644,
    lng: -49.2214,
  },
  {
    nome: "Estádio Vitorino Gonçalves Dias",
    aliases: ["vitorino gonçalves dias", "vitorino goncalves dias"],
    cidade: "Londrina",
    regiao: "Paraná",
    lat: -23.3103,
    lng: -51.1628,
  },
  {
    nome: "Estádio Hailé Pinheiro",
    aliases: ["hailé pinheiro", "haile pinheiro"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6395,
    lng: -49.2903,
  },
  {
    nome: "Estádio Moisés Lucarelli",
    aliases: ["moisés lucarelli", "moises lucarelli"],
    cidade: "Campinas",
    regiao: "São Paulo",
    lat: -22.9067,
    lng: -47.0517,
  },
  {
    nome: "Estádio Alfredo Jaconi",
    aliases: ["alfredo jaconi"],
    cidade: "Caxias do Sul",
    regiao: "Rio Grande do Sul",
    lat: -29.1544,
    lng: -51.1636,
  },
  {
    nome: "Estádio Ilha do Retiro",
    aliases: ["ilha do retiro"],
    cidade: "Recife",
    regiao: "Pernambuco",
    lat: -8.0631,
    lng: -34.9086,
  },
  {
    nome: "Estádio Rei Pelé",
    aliases: ["rei pelé", "rei pele"],
    cidade: "Maceió",
    regiao: "Alagoas",
    lat: -9.6208,
    lng: -35.7181,
  },
  {
    nome: "Independência",
    aliases: ["arena da independência", "arena da independencia", "independência"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.9186,
    lng: -43.9411,
  },
  {
    nome: "Estádio Orlando Scarpelli",
    aliases: ["orlando scarpelli", "scarpelli"],
    cidade: "Florianópolis",
    regiao: "Santa Catarina",
    lat: -27.5972,
    lng: -48.5450,
  },
  {
    nome: "Estádio Curuzu",
    aliases: ["curuzu"],
    cidade: "Belém",
    regiao: "Pará",
    lat: -1.4392,
    lng: -48.4642,
  },
  {
    nome: "Estádio Almeidão",
    aliases: ["almeidão", "almeidao"],
    cidade: "João Pessoa",
    regiao: "Paraíba",
    lat: -7.1362,
    lng: -34.8578,
  },
  {
    nome: "Estádio Raulino de Oliveira",
    aliases: ["raulino de oliveira"],
    cidade: "Volta Redonda",
    regiao: "Rio de Janeiro",
    lat: -22.5202,
    lng: -44.1042,
  },
  {
    nome: "Arena Batistão",
    aliases: ["arena batistão", "arena batistao", "batistão"],
    cidade: "Aracaju",
    regiao: "Sergipe",
    lat: -10.9350,
    lng: -37.0731,
  },
  {
    nome: "Estádio Brinco de Ouro da Princesa",
    aliases: ["brinco de ouro", "brinco de ouro da princesa"],
    cidade: "Campinas",
    regiao: "São Paulo",
    lat: -22.9040,
    lng: -47.0850,
  },
  {
    nome: "Estádio Germano Krüger",
    aliases: ["germano kruger", "germano krüger"],
    cidade: "Ponta Grossa",
    regiao: "Paraná",
    lat: -25.0916,
    lng: -50.1668,
  },
  {
    nome: "Arena Pernambuco",
    aliases: ["arena pernambuco", "arena pernambuco s. lourenço"],
    cidade: "São Lourenço da Mata",
    regiao: "Pernambuco",
    lat: -8.0186,
    lng: -35.0119,
  },
  {
    nome: "Estádio Primeiro de Maio",
    aliases: ["1º de maio", "primeiro de maio", "1º de maio são bernardo"],
    cidade: "São Bernardo do Campo",
    regiao: "São Paulo",
    lat: -23.7167,
    lng: -46.5567,
  },
  {
    nome: "Estádio da Ressacada",
    aliases: ["ressacada"],
    cidade: "Florianópolis",
    regiao: "Santa Catarina",
    lat: -27.6797,
    lng: -48.5583,
  },
  {
    nome: "Estádio Frasqueirão (Saraivão)",
    aliases: ["saraivao", "saraivão", "frasqueirao"],
    cidade: "Ivinhema",
    regiao: "Mato Grosso do Sul",
    lat: -22.3033,
    lng: -53.8181,
  },
  {
    nome: "Arena das Dunas",
    aliases: ["arena das dunas"],
    cidade: "Natal",
    regiao: "Rio Grande do Norte",
    lat: -5.8236,
    lng: -35.2306,
  },
  {
    nome: "Estádio Bezerrão",
    aliases: ["bezerrao", "bezerrão"],
    cidade: "Gama",
    regiao: "Distrito Federal",
    lat: -15.9989,
    lng: -48.0611,
  },
  {
    nome: "Estádio Guilherme da Silveira Filho (Luso Brasileiro)",
    aliases: ["luso brasileiro", "guilherme da silveira"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8781,
    lng: -43.4642,
  },
  {
    nome: "Estádio Comendador Souza (Canindé)",
    aliases: ["caninde", "canindé", "comendador souza"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.5217,
    lng: -46.6297,
  },
  {
    nome: "Estádio Municipal Parque do Sabiá",
    aliases: ["parque do sabia", "parque do sabiá"],
    cidade: "Uberlândia",
    regiao: "Minas Gerais",
    lat: -18.9142,
    lng: -48.2661,
  },
  {
    nome: "Estádio Amigão",
    aliases: ["amigao", "amigão"],
    cidade: "Campina Grande",
    regiao: "Paraíba",
    lat: -7.2325,
    lng: -35.8817,
  },
  {
    nome: "Estádio Presidente Vargas",
    aliases: ["presidente vargas"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.7431,
    lng: -38.5406,
  },
  {
    nome: "Estádio Municipal João Saldanha",
    aliases: ["joao saldanha", "joão saldanha", "municipal joao saldanha"],
    cidade: "Maricá",
    regiao: "Rio de Janeiro",
    lat: -22.9195,
    lng: -42.8186,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Nivaldo Pereira (São Januário / CT Vasco)",
    aliases: ["nivaldo pereira"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8912,
    lng: -43.2229,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Jânio de Moraes (Laranjão)",
    aliases: ["janio de moraes", "jânio de moraes", "laranjao", "laranjão"],
    cidade: "Nova Iguaçu",
    regiao: "Rio de Janeiro",
    lat: -22.7556,
    lng: -43.4603,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Eduardo Guinle",
    aliases: ["eduardo guinle"],
    cidade: "Nova Friburgo",
    regiao: "Rio de Janeiro",
    lat: -22.2819,
    lng: -42.5311,
    fonte: "aproximado/cidade",
  },
  {
    nome: "CT do Boavista",
    aliases: ["ct do boavista", "boavista"],
    cidade: "Saquarema",
    regiao: "Rio de Janeiro",
    lat: -22.9200,
    lng: -42.5100,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Marcelo Vieira",
    aliases: ["marcelo vieira"],
    cidade: "Maricá",
    regiao: "Rio de Janeiro",
    lat: -22.9195,
    lng: -42.8186,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Municipal do Trabalhador (SESI)",
    aliases: ["municipal do trabalhador", "e. do sesi", "estadio do sesi"],
    cidade: "Resende",
    regiao: "Rio de Janeiro",
    lat: -22.4705,
    lng: -44.4509,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Antônio Ferreira de Medeiros",
    aliases: ["antonio ferreira de medeiros", "antônio ferreira de medeiros"],
    cidade: "Cardoso Moreira",
    regiao: "Rio de Janeiro",
    lat: -21.5850,
    lng: -41.4200,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Alair Corrêa",
    aliases: ["alair correa", "alair corrêa"],
    cidade: "Volta Redonda",
    regiao: "Rio de Janeiro",
    lat: -22.5202,
    lng: -44.1041,
    fonte: "aproximado/cidade - a confirmar",
  },
  {
    nome: "Estádio Giulite Coutinho (Edson Passos)",
    aliases: ["giulite coutinho", "edson passos"],
    cidade: "Mesquita",
    regiao: "Rio de Janeiro",
    lat: -22.7889,
    lng: -43.4392,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Ítalo Del Cima",
    aliases: ["italo del cima", "ítalo del cima"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9020,
    lng: -43.5610,
  },
  {
    nome: "Estádio Leônidas da Silva",
    aliases: ["leonidas da silva", "leônidas da silva"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8620,
    lng: -43.2540,
  },
  {
    nome: "Estádio Prefeito Ismael de Souza Leão do Sul",
    aliases: ["ismael de souza", "leao do sul", "leão do sul"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9068,
    lng: -43.1729,
    fonte: "aproximado/cidade - a confirmar",
  },
  {
    nome: "Estádio de Los Lários",
    aliases: ["los larios", "los lários"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9068,
    lng: -43.1729,
    fonte: "aproximado/cidade - a confirmar",
  },
  {
    nome: "Estádio Antônio Ferreira de Medeiros (Ferreirão)",
    aliases: ["antonio ferreira de medeiros", "antônio ferreira de medeiros", "ferreirao", "ferreirão"],
    cidade: "Cardoso Moreira",
    regiao: "Rio de Janeiro",
    lat: -21.5589,
    lng: -41.5158,
    fonte: "manual/aproximado (Cardoso Moreira, RJ)",
  },
  {
    nome: "Estádio Alair Corrêa (Correão)",
    aliases: ["alair correa", "alair corrêa", "correao", "correão"],
    cidade: "Cabo Frio",
    regiao: "Rio de Janeiro",
    lat: -22.8794,
    lng: -42.0186,
    fonte: "manual/aproximado (Cabo Frio, RJ)",
  },
  {
    nome: "Estádio Leônidas da Silva (Teixeira de Castro)",
    aliases: ["leonidas da silva", "leônidas da silva", "teixeira de castro"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8657,
    lng: -43.2578,
    fonte: "manual/aproximado (Bonsucesso, Rio de Janeiro)",
  },
];
