/*
  Base de estádios do futebol colombiano (Liga BetPlay, Torneo BetPlay,
  Copa BetPlay). Coordenadas em nível de estádio quando encontradas com
  boa confiança, ou aproximação no nível da cidade quando não.
*/

window.ESTADIOS_COLOMBIA = [
  {
    nome: "Estadio Nemesio Camacho El Campín",
    aliases: ["nemesio camacho el campin", "el campin", "el campín"],
    cidade: "Bogotá",
    regiao: "Bogotá",
    lat: 4.6486,
    lng: -74.0776,
  },
  {
    nome: "Estadio Metropolitano de Techo",
    aliases: ["metropolitano de techo"],
    cidade: "Bogotá",
    regiao: "Bogotá",
    lat: 4.6280,
    lng: -74.1590,
    fonte: "manual/aproximado (Kennedy, Bogotá)",
  },
  {
    nome: "Estadio Olímpico Pascual Guerrero",
    aliases: ["pascual guerrero"],
    cidade: "Cali",
    regiao: "Valle del Cauca",
    lat: 3.4372,
    lng: -76.5388,
  },
  {
    nome: "Estadio Deportivo Cali (Palmaseca)",
    aliases: ["deportivo cali", "palmaseca", "estadio deportivo cali"],
    cidade: "Cali",
    regiao: "Valle del Cauca",
    lat: 3.4800,
    lng: -76.3700,
    fonte: "manual/aproximado (Palmaseca, entre Cali e Candelaria)",
  },
  {
    nome: "Estadio Atanasio Girardot",
    aliases: ["atanasio girardot"],
    cidade: "Medellín",
    regiao: "Antioquia",
    lat: 6.2506,
    lng: -75.5783,
  },
  {
    nome: "Estadio Armando Maestre Pavajeau",
    aliases: ["armando maestre pavajeau", "armando maestre"],
    cidade: "Valledupar",
    regiao: "Cesar",
    lat: 10.4636,
    lng: -73.2529,
    fonte: "manual/aproximado (Carrera 18A #20-15, Valledupar)",
  },
  {
    nome: "Estadio Centenario de Armenia",
    aliases: ["centenario de armenia", "centenario"],
    cidade: "Armenia",
    regiao: "Quindío",
    lat: 4.5339,
    lng: -75.6811,
    fonte: "manual/aproximado (cidade de Armenia, Quindío)",
  },
  {
    nome: "Estadio Departamental Libertad",
    aliases: ["departamental libertad", "libertad"],
    cidade: "Pasto",
    regiao: "Nariño",
    lat: 1.2136,
    lng: -77.2811,
    fonte: "manual/aproximado (cidade de Pasto)",
  },
  {
    nome: "Estadio Alfonso López",
    aliases: ["alfonso lopez", "alfonso lópez", "estadio american"],
    cidade: "Bucaramanga",
    regiao: "Santander",
    lat: 7.1275,
    lng: -73.1225,
    fonte: "manual/aproximado (cidade de Bucaramanga)",
  },
  {
    nome: "Estadio Bello Horizonte - Rey Pelé",
    aliases: ["bello horizonte", "rey pele", "rey pelé"],
    cidade: "Villavicencio",
    regiao: "Meta",
    lat: 4.1420,
    lng: -73.6266,
    fonte: "manual/aproximado (cidade de Villavicencio)",
  },
  {
    nome: "Estadio Francisco Rivera Escobar",
    aliases: ["francisco rivera escobar"],
    cidade: "Palmira",
    regiao: "Valle del Cauca",
    lat: 3.5322,
    lng: -76.3033,
    fonte: "manual/aproximado (cidade de Palmira)",
  },
  {
    nome: "Estadio Jaraguay (Municipal de Montería)",
    aliases: ["jaraguay", "municipal de monteria", "municipal de montería"],
    cidade: "Montería",
    regiao: "Córdoba",
    lat: 8.7479,
    lng: -75.8814,
    fonte: "manual/aproximado (cidade de Montería)",
  },
  {
    nome: "Estadio Manuel Murillo Toro",
    aliases: ["manuel murillo toro"],
    cidade: "Ibagué",
    regiao: "Tolima",
    lat: 4.4389,
    lng: -75.2322,
    fonte: "manual/aproximado (cidade de Ibagué)",
  },
  {
    nome: "Estadio General Santander",
    aliases: ["general santander"],
    cidade: "Cúcuta",
    regiao: "Norte de Santander",
    lat: 7.8891,
    lng: -72.4967,
    fonte: "manual/aproximado (cidade de Cúcuta)",
  },
  {
    nome: "Estadio Hernán Ramírez Villegas",
    aliases: ["hernan ramirez villegas", "hernán ramírez villegas"],
    cidade: "Pereira",
    regiao: "Risaralda",
    lat: 4.8087,
    lng: -75.6906,
    fonte: "manual/aproximado (cidade de Pereira)",
  },
  {
    nome: "Estadio La Independencia",
    aliases: ["la independencia"],
    cidade: "Tunja",
    regiao: "Boyacá",
    lat: 5.5353,
    lng: -73.3678,
    fonte: "manual/aproximado (cidade de Tunja)",
  },
  {
    nome: "Estadio Metropolitano Ciudad de Itagüí",
    aliases: ["metropolitano ciudad de itagui", "metropolitano ciudad de itagüí", "ditaires"],
    cidade: "Itagüí",
    regiao: "Antioquia",
    lat: 6.1719,
    lng: -75.6119,
    fonte: "manual/aproximado (cidade de Itagüí)",
  },
  {
    nome: "Estadio Palogrande",
    aliases: ["palogrande"],
    cidade: "Manizales",
    regiao: "Caldas",
    lat: 5.0703,
    lng: -75.5138,
    fonte: "manual/aproximado (cidade de Manizales)",
  },
  {
    nome: "Polideportivo Sur",
    aliases: ["polideportivo sur"],
    cidade: "Envigado",
    regiao: "Antioquia",
    lat: 6.1683,
    lng: -75.5906,
    fonte: "manual/aproximado (cidade de Envigado)",
  },
  {
    nome: "Estadio Romelio Martínez",
    aliases: ["romelio martinez", "romelio martínez"],
    cidade: "Barranquilla",
    regiao: "Atlántico",
    lat: 10.9995,
    lng: -74.8014,
    fonte: "manual/aproximado (cidade de Barranquilla)",
  },
  {
    nome: "Estadio Cincuentenario",
    aliases: ["cincuentenario", "estadio cincuentenario"],
    cidade: "Medellín",
    regiao: "Antioquia",
    lat: 6.2691,
    lng: -75.5651,
    fonte: "manual/aproximado (comuna Aranjuez, Medellín — sede provisória do Águilas Doradas)",
  },
];
