/*
  Base de estádios do futebol peruano. Ainda é um stub pequeno: o
  scraper de futbolperuano.com (Liga 1/2/3, Copa de la Liga, Copa Perú,
  Femenino) não traz o nome do estádio por partida na fonte usada, só
  data/hora/times, então por enquanto isso serve principalmente pros
  jogos do Peru que aparecem via CONMEBOL (Libertadores/Sudamericana),
  que já trazem estádio. Dá pra completar com mais clubes depois.
*/

window.ESTADIOS_PERU = [
  {
    nome: "Estadio Nacional de Lima",
    aliases: ["estadio nacional de lima", "estadio nacional del peru", "estadio nacional del perú", "nacional del peru"],
    cidade: "Lima",
    regiao: "Lima",
    lat: -12.0698,
    lng: -77.0378,
  },
  {
    nome: "Estadio Inca Garcilaso de la Vega",
    aliases: ["inca garcilaso de la vega", "estadio garcilaso"],
    cidade: "Cusco",
    regiao: "Cusco",
    lat: -13.5183,
    lng: -71.9714,
    fonte: "manual/aproximado (Cusco, Peru)",
  },
  {
    nome: "Estadio Alejandro Villanueva (Matute)",
    aliases: ["alejandro villanueva", "matute", "estadio alianza lima"],
    cidade: "Lima",
    regiao: "Lima",
    lat: -12.0672,
    lng: -77.0117,
    fonte: "manual/aproximado (La Victoria, Lima)",
  },
  {
    nome: "Estadio Monumental \"U\"",
    aliases: ["estadio monumental u", "monumental u", "estadio monumental \"u\"", "monumental de universitario"],
    cidade: "Lima",
    regiao: "Lima",
    lat: -12.0089,
    lng: -76.8567,
    fonte: "manual/aproximado (Ate, Lima)",
  },
  {
    nome: "Estadio Alberto Gallardo (La Florida)",
    aliases: ["alberto gallardo", "la florida sporting cristal"],
    cidade: "Lima",
    regiao: "Lima",
    lat: -12.0755,
    lng: -77.0011,
    fonte: "manual/aproximado (San Luis, Lima)",
  },
  {
    nome: "Estadio Mansiche",
    aliases: ["mansiche", "estadio mansiche"],
    cidade: "Trujillo",
    regiao: "La Libertad",
    lat: -8.1116,
    lng: -79.0287,
    fonte: "manual/aproximado (Trujillo, Peru)",
  },
  {
    nome: "Estadio Monumental de la UNSA",
    aliases: ["monumental de la unsa", "estadio unsa", "monumental unsa"],
    cidade: "Arequipa",
    regiao: "Arequipa",
    lat: -16.4090,
    lng: -71.5375,
    fonte: "manual/aproximado (Arequipa, Peru)",
  },
  {
    nome: "Estadio Campeones del 36",
    aliases: ["campeones del 36"],
    cidade: "Piura",
    regiao: "Piura",
    lat: -5.1945,
    lng: -80.6328,
    fonte: "manual/aproximado (Piura, Peru)",
  },
  {
    nome: "Estadio Miguel Grau (Callao)",
    aliases: ["miguel grau callao", "estadio miguel grau del callao"],
    cidade: "Callao",
    regiao: "Callao",
    lat: -12.0575,
    lng: -77.1067,
    fonte: "manual/aproximado (Bellavista, Callao)",
  },
  {
    nome: "Estadio IPD Huancayo",
    aliases: ["ipd huancayo", "huancayo"],
    cidade: "Huancayo",
    regiao: "Junín",
    lat: -12.0653,
    lng: -75.2049,
    fonte: "manual/aproximado (cidade de Huancayo)",
  },
  {
    nome: "Estadio IPD Sullana",
    aliases: ["ipd sullana"],
    cidade: "Sullana",
    regiao: "Piura",
    lat: -4.9036,
    lng: -80.6828,
    fonte: "manual/aproximado (cidade de Sullana)",
  },
  {
    nome: "Estadio Max Agurto Sánchez",
    aliases: ["max agurto sanchez", "max agurto"],
    cidade: "Pucallpa",
    regiao: "Ucayali",
    lat: -8.3791,
    lng: -74.5539,
    fonte: "manual/aproximado (cidade de Pucallpa)",
  },
  {
    nome: "Estadio Heraclio Tapia",
    aliases: ["heraclio tapia"],
    cidade: "Huánuco",
    regiao: "Huánuco",
    lat: -9.9306,
    lng: -76.2422,
    fonte: "manual/aproximado (cidade de Huánuco)",
  },
  {
    nome: "Estadio Huaral (aproximado)",
    aliases: ["huaral"],
    cidade: "Huaral",
    regiao: "Lima",
    lat: -11.4958,
    lng: -77.2064,
    fonte: "manual/aproximado (cidade de Huaral - Coopsol)",
  },
  {
    nome: "Estadio Calca (Valle Sagrado, aproximado)",
    aliases: ["calca valle sagrado"],
    cidade: "Calca",
    regiao: "Cusco",
    lat: -13.3325,
    lng: -71.9586,
    fonte: "manual/aproximado (cidade de Calca - Valle Sagrado)",
  },
];
