/*
  Base de estádios do Goiás (fonte="FGF" no scrap_fgf_goias_api.py).

  A API da FGF (jogos_ajax_ver3.php) traz o nome do estádio/CT como texto
  livre, mas nunca a cidade. Muitos são CTs (Centros de Treinamento) de
  clubes de base/2ª-3ª divisão sem nome de cidade no próprio nome, então o
  fallback nacional por texto (findStadiumInfo) não teria como resolver a
  cidade sozinho. Esta base mapeia estádio -> cidade a partir de pesquisa
  sobre a sede de cada clube que manda seus jogos ali (jul/2026): a maioria
  dos CTs pertence a um único clube (ex.: "CT Vila do Tigre" = CT do Vila
  Nova, em Goiânia); alguns são compartilhados por clubes da mesma cidade
  (ex.: "Sesi Multiparque" usado por Atlético-GO e Guanabara City, ambos de
  Goiânia).

  Dois casos (Ovel, Real Clube) não tiveram cidade confirmada em fontes
  públicas até 26/07/2026 -- usa Goiânia (onde fica a maior parte dos
  clubes de base do estado) como aproximação razoável, igual à convenção já
  usada em estadios_es_cidades.js/estadios_ceara.js quando falta o dado
  exato.

  Coordenadas: centro do município (fonte IBGE, via
  kelvins/municipios-brasileiros), não o endereço exato do CT/estádio --
  suficiente para posicionar o jogo no mapa.
*/
window.ESTADIOS_GOIAS = [
  {
    nome: "Abrão Manoel da Costa",
    aliases: ["abrao manoel da costa"],
    cidade: "Trindade",
    regiao: "Goiás",
    lat: -16.6517,
    lng: -49.4927,
    fonte: "Trindade EC manda jogos em Trindade-GO",
  },
  {
    nome: "Anibal Batista de Toledo",
    aliases: ["anibal batista de toledo"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "usado por Crixás/Goiânia EC SAF/Aparecidense - estádio compartilhado em Goiânia",
  },
  {
    nome: "CE Wilson Goiano",
    aliases: ["ce wilson goiano", "cewg"],
    cidade: "Trindade",
    regiao: "Goiás",
    lat: -16.6517,
    lng: -49.4927,
    fonte: "Centro Esportivo Wilson Goiano, fundado em Trindade-GO",
  },
  {
    nome: "CT Anapolina",
    aliases: ["ct anapolina"],
    cidade: "Anápolis",
    regiao: "Goiás",
    lat: -16.3281,
    lng: -48.9530,
    fonte: "Anapolina S.A.F. - Anápolis-GO",
  },
  {
    nome: "CT Buriti Sereno",
    aliases: ["ct buriti sereno"],
    cidade: "Aparecida de Goiânia",
    regiao: "Goiás",
    lat: -16.8198,
    lng: -49.2469,
    fonte: "Planalto EC e Aparecidense - ambos sediados em Aparecida de Goiânia",
  },
  {
    nome: "CT Cidade do Tubarão",
    aliases: ["ct cidade do tubarao"],
    cidade: "Senador Canedo",
    regiao: "Goiás",
    lat: -16.7084,
    lng: -49.0914,
    fonte: "Canedo FC (\"Tubarão do Cerrado\") - Senador Canedo-GO",
  },
  {
    nome: "CT Edmo Pinheiro",
    aliases: ["ct edmo pinheiro"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "centro de treinamento do Goiás EC, em Goiânia",
  },
  {
    nome: "CT Fazendinha",
    aliases: ["ct fazendinha"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "Flugoiânia - Goiânia-GO",
  },
  {
    nome: "CT Ovel",
    aliases: ["ct ovel"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "Associação Esportiva Ovel - Estr. 113, 284, Chácaras Recreio São Joaquim, Goiânia-GO (CEP 74470-210, confirmado via CEP -> IBGE 5208707 = Goiânia); lat/lng = centro do município (endereço exato do bairro não geocodificado com confiança)",
  },
  {
    nome: "CT Toca do Lobo",
    aliases: ["ct toca do lobo"],
    cidade: "Aparecida de Goiânia",
    regiao: "Goiás",
    lat: -16.8198,
    lng: -49.2469,
    fonte: "CEC Cerrado Esporte Clube (\"Lobo do Cerrado\") - Aparecida de Goiânia-GO",
  },
  {
    nome: "CT Valterci de Melo",
    aliases: ["ct valterci de melo"],
    cidade: "Anápolis",
    regiao: "Goiás",
    lat: -16.3281,
    lng: -48.9530,
    fonte: "Anápolis FC - Anápolis-GO",
  },
  {
    nome: "CT Vila do Tigre",
    aliases: ["ct vila do tigre"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "centro de treinamento do Vila Nova (\"Tigre\") - Goiânia",
  },
  {
    nome: "CT Atlanta",
    aliases: ["ct atlanta", "ct. atlanta"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "Atlanta FC - região Noroeste de Goiânia (Três Ilhas)",
  },
  {
    nome: "Comigo",
    aliases: ["comigo"],
    cidade: "Rio Verde",
    regiao: "Goiás",
    lat: -17.7923,
    lng: -50.9192,
    fonte: "Independente de Rio Verde - Rio Verde-GO",
  },
  {
    nome: "Defelê",
    aliases: ["defele"],
    cidade: "Luziânia",
    regiao: "Goiás",
    lat: -16.2530,
    lng: -47.9500,
    fonte: "Royal FC - Luziânia-GO",
  },
  {
    nome: "Dorvalino Monteiro dos Reis",
    aliases: ["dorvalino monteiro dos reis"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "Atlético Goianiense - Goiânia-GO",
  },
  {
    nome: "Francisco Ferreira",
    aliases: ["francisco ferreira"],
    cidade: "Iporá",
    regiao: "Goiás",
    lat: -16.4398,
    lng: -51.1180,
    fonte: "AC Iporaense - Iporá-GO",
  },
  {
    nome: "Geraldo Rodrigues",
    aliases: ["geraldo rodrigues", "geraldao"],
    cidade: "Jussara",
    regiao: "Goiás",
    lat: -15.8659,
    lng: -50.8668,
    fonte: "Tupy de Jussara - Jussara-GO",
  },
  {
    nome: "Gilmar Alves",
    aliases: ["gilmar alves"],
    cidade: "Bom Jesus de Goiás",
    regiao: "Goiás",
    lat: -18.2173,
    lng: -49.7400,
    fonte: "Bom Jesus EC - Bom Jesus de Goiás-GO",
  },
  {
    nome: "João José Teodoro",
    aliases: ["joao jose teodoro"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "Goiânia EC SAF - Goiânia-GO",
  },
  {
    nome: "João Vilela",
    aliases: ["joao vilela"],
    cidade: "Morrinhos",
    regiao: "Goiás",
    lat: -17.7334,
    lng: -49.1059,
    fonte: "Morrinhos FC - Morrinhos-GO",
  },
  {
    nome: "Jutair Neto",
    aliases: ["jutair neto"],
    cidade: "São Luís de Montes Belos",
    regiao: "Goiás",
    lat: -16.5211,
    lng: -50.3726,
    fonte: "São Luiz FC - São Luís de Montes Belos-GO",
  },
  {
    nome: "Mozart Veloso do Carmo",
    aliases: ["mozart veloso do carmo"],
    cidade: "Rio Verde",
    regiao: "Goiás",
    lat: -17.7923,
    lng: -50.9192,
    fonte: "Rio Verde EC - Rio Verde-GO",
  },
  {
    nome: "Odilon Flores",
    aliases: ["odilon flores"],
    cidade: "Mineiros",
    regiao: "Goiás",
    lat: -17.5654,
    lng: -52.5537,
    fonte: "estádio oficial do Mineiros EC (MEC) - Mineiros-GO, confirmado (capacidade 7.000)",
  },
  {
    nome: "Onofre Ferreira de Cubas",
    aliases: ["onofre ferreira de cubas"],
    cidade: "Itumbiara",
    regiao: "Goiás",
    lat: -18.4093,
    lng: -49.2158,
    fonte: "Real Clube (Real de Itumbiara), fundado 05/02/1998 - Itumbiara-GO",
  },
  {
    nome: "Resenha Sports Center",
    aliases: ["resenha sports center"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "Estrela - cidade nao confirmada em fonte publica - aproximacao (Goiânia)",
  },
  {
    nome: "Rio das Pedras",
    aliases: ["rio das pedras"],
    cidade: "Itaberaí",
    regiao: "Goiás",
    lat: -16.0206,
    lng: -49.8060,
    fonte: "Itaberaí SAF - Itaberaí-GO",
  },
  {
    nome: "Ronan Maia",
    aliases: ["ronan maia"],
    cidade: "Jataí",
    regiao: "Goiás",
    lat: -17.8784,
    lng: -51.7204,
    fonte: "AE Jataiense - Jataí-GO",
  },
  {
    nome: "Sandoval Prudente",
    aliases: ["sandoval prudente"],
    cidade: "Cristianópolis",
    regiao: "Goiás",
    lat: -17.1987,
    lng: -48.7034,
    fonte: "Cristianópolis FC - Cristianópolis-GO",
  },
  {
    nome: "Sebastião Aniceto de Oliveira",
    aliases: ["sebastiao aniceto de oliveira"],
    cidade: "Senador Canedo",
    regiao: "Goiás",
    lat: -16.7084,
    lng: -49.0914,
    fonte: "Desportivo Real FC - Senador Canedo-GO",
  },
  {
    nome: "Sebastião Mariano da Silva",
    aliases: ["sebastiao mariano da silva"],
    cidade: "Senador Canedo",
    regiao: "Goiás",
    lat: -16.7084,
    lng: -49.0914,
    fonte: "Desportivo Real FC - Senador Canedo-GO (categoria diferente, mesma cidade)",
  },
  {
    nome: "Serra de Caldas",
    aliases: ["serra de caldas"],
    cidade: "Caldas Novas",
    regiao: "Goiás",
    lat: -17.7441,
    lng: -48.6246,
    fonte: "Olímpio manda jogos da Copa Goiás de base em Caldas Novas-GO",
  },
  {
    nome: "Sesi Multiparque",
    aliases: ["sesi multiparque"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "complexo esportivo do SESI em Goiânia, usado por Atlético-GO e Guanabara City",
  },
  {
    nome: "Valdir Cândido de Queiroz",
    aliases: ["valdir candido de queiroz"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6864,
    lng: -49.2643,
    fonte: "usado por Atlético-GO e Goiânia EC SAF - Goiânia-GO",
  },
  {
    nome: "Waldeir José de Oliveira",
    aliases: ["waldeir jose de oliveira"],
    cidade: "Goianésia",
    regiao: "Goiás",
    lat: -15.3118,
    lng: -49.1162,
    fonte: "Goianésia EC - Goianésia-GO",
  },
];
