/*
  Base de estádios do futebol argentino (Torneo Clausura, Copa Argentina,
  Primera Nacional).

  Mesmo formato de /estadios.js e /estadios_brasil.js: usado pelo script.js
  para resolver cidade, provincia (regiao) e coordenadas dos jogos da
  Argentina quando o campo "estadio" bate com um destes nomes, e também
  como base para o fallback "estádio mandante padrão" (a maioria dos jogos
  da AFA não vem com estádio explícito na fonte).
*/

window.ESTADIOS_ARGENTINA = [
  {
    nome: "Estadio Monumental Antonio Vespucio Liberti",
    aliases: ["monumental", "estadio monumental", "river plate estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.5453,
    lng: -58.4497,
  },
  {
    nome: "Estadio Alberto J. Armando (La Bombonera)",
    aliases: ["la bombonera", "bombonera", "estadio alberto j armando", "estadio alberto jose armando", "estadio alberto josé armando"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6356,
    lng: -58.3648,
  },
  {
    nome: "Estadio Presidente Perón (Cilindro)",
    aliases: ["cilindro", "estadio presidente peron", "racing club estadio"],
    cidade: "Avellaneda",
    regiao: "Buenos Aires",
    lat: -34.6656,
    lng: -58.3897,
  },
  {
    nome: "Estadio Libertadores de América",
    aliases: ["libertadores de america", "independiente estadio"],
    cidade: "Avellaneda",
    regiao: "Buenos Aires",
    lat: -34.6656,
    lng: -58.3719,
  },
  {
    nome: "Estadio Pedro Bidegain (Nuevo Gasómetro)",
    aliases: ["nuevo gasometro", "pedro bidegain", "san lorenzo estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6524,
    lng: -58.4009,
  },
  {
    nome: "Estadio Tomás Adolfo Ducó",
    aliases: ["tomas duco", "estadio huracan"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6367,
    lng: -58.4189,
  },
  {
    nome: "Estadio José Amalfitani",
    aliases: ["jose amalfitani", "amalfitani", "velez estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6417,
    lng: -58.5228,
  },
  {
    nome: "Estadio UNO (Jorge Luis Hirschi)",
    aliases: ["estadio uno", "jorge luis hirschi", "estudiantes la plata estadio"],
    cidade: "La Plata",
    regiao: "Buenos Aires",
    lat: -34.9750,
    lng: -57.9506,
  },
  {
    nome: "Estadio Juan Carmelo Zerillo (Bosque)",
    aliases: ["estadio bosque", "juan carmelo zerillo", "gimnasia la plata estadio"],
    cidade: "La Plata",
    regiao: "Buenos Aires",
    lat: -34.9117,
    lng: -57.9503,
  },
  {
    nome: "Estadio Mario Alberto Kempes",
    aliases: ["mario kempes", "estadio kempes", "talleres estadio"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.3350,
    lng: -64.2444,
  },
  {
    nome: "Estadio Julio César Villagra (Gigante de Alberdi)",
    aliases: ["gigante de alberdi", "julio cesar villagra", "belgrano estadio", "belgrano cba", "belgrano (cba"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.4272,
    lng: -64.2069,
  },
  {
    nome: "Estadio Gigante de Arroyito",
    aliases: ["gigante de arroyito", "arroyito", "rosario central estadio"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9425,
    lng: -60.6425,
  },
  {
    nome: "Estadio Marcelo Bielsa (Coloso del Parque)",
    aliases: ["coloso del parque", "marcelo bielsa", "newell's estadio", "newells estadio", "newell's old boys", "newells old boys"],
    cidade: "Rosario",
    regiao: "Santa Fe",
    lat: -32.9494,
    lng: -60.6767,
  },
  {
    nome: "Estadio 15 de Abril",
    aliases: ["15 de abril", "union santa fe estadio"],
    cidade: "Santa Fe",
    regiao: "Santa Fe",
    lat: -31.6333,
    lng: -60.7000,
  },
  {
    nome: "Estadio Monumental José Fierro",
    aliases: ["jose fierro", "atletico tucuman estadio"],
    cidade: "San Miguel de Tucumán",
    regiao: "Tucumán",
    lat: -26.8236,
    lng: -65.2564,
  },
  {
    nome: "Estadio Madre de Ciudades",
    aliases: ["madre de ciudades", "central cordoba santiago estadio"],
    cidade: "Santiago del Estero",
    regiao: "Santiago del Estero",
    lat: -27.7951,
    lng: -64.2431,
  },
  {
    nome: "Estadio Florencio Sola",
    aliases: ["florencio sola", "banfield estadio"],
    cidade: "Banfield",
    regiao: "Buenos Aires",
    lat: -34.7458,
    lng: -58.3944,
  },
  {
    nome: "Estadio Ciudad de Lanús (Néstor Díaz Pérez)",
    aliases: ["ciudad de lanus", "nestor diaz perez", "lanus estadio"],
    cidade: "Lanús",
    regiao: "Buenos Aires",
    lat: -34.7044,
    lng: -58.3919,
  },
  {
    nome: "Estadio Ciudad de Vicente López",
    aliases: ["ciudad de vicente lopez", "platense estadio"],
    cidade: "Vicente López",
    regiao: "Buenos Aires",
    lat: -34.5233,
    lng: -58.4886,
  },
  {
    nome: "Estadio José Dellagiovanna (La Candela)",
    aliases: ["la candela", "jose dellagiovanna", "tigre estadio"],
    cidade: "Victoria (Tigre)",
    regiao: "Buenos Aires",
    lat: -34.4494,
    lng: -58.5389,
  },
  {
    nome: "Estadio Diego Armando Maradona",
    aliases: ["estadio maradona", "argentinos juniors estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6089,
    lng: -58.4794,
  },
  {
    nome: "Estadio Eva Perón",
    aliases: ["eva peron", "sarmiento junin estadio"],
    cidade: "Junín",
    regiao: "Buenos Aires",
    lat: -34.5883,
    lng: -60.9500,
  },
  {
    nome: "Estadio Norberto Tomaghello",
    aliases: ["norberto tomaghello", "defensa y justicia estadio"],
    cidade: "Florencio Varela",
    regiao: "Buenos Aires",
    lat: -34.8206,
    lng: -58.3789,
  },
  {
    nome: "Estadio José María Minella",
    aliases: ["jose maria minella", "aldosivi estadio"],
    cidade: "Mar del Plata",
    regiao: "Buenos Aires",
    lat: -37.9633,
    lng: -57.5750,
  },
  {
    nome: "Estadio Guillermo Laza",
    aliases: ["guillermo laza", "deportivo riestra estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6650,
    lng: -58.4436,
  },
  {
    nome: "Estadio Bautista Gargantini",
    aliases: ["bautista gargantini", "independiente rivadavia estadio"],
    cidade: "Mendoza",
    regiao: "Mendoza",
    lat: -32.8908,
    lng: -68.8272,
  },
  {
    nome: "Estadio Víctor Antonio Legrotaglie",
    aliases: ["victor legrotaglie", "gimnasia mendoza estadio"],
    cidade: "Mendoza",
    regiao: "Mendoza",
    lat: -32.8850,
    lng: -68.8419,
  },
  {
    nome: "Estadio Antonio Candini",
    aliases: ["antonio candini", "estudiantes rio cuarto estadio"],
    cidade: "Río Cuarto",
    regiao: "Córdoba",
    lat: -33.1232,
    lng: -64.3492,
  },
  {
    nome: "Estadio Presidente Perón (Instituto)",
    aliases: ["instituto estadio", "estadio instituto atletico central cordoba"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.4200,
    lng: -64.1836,
  },
  {
    nome: "Estadio Claudio Tapia (Barracas Central)",
    aliases: ["barracas central estadio", "claudio tapia estadio"],
    cidade: "Buenos Aires",
    regiao: "Ciudad Autónoma de Buenos Aires",
    lat: -34.6420,
    lng: -58.3894,
  },
  {
    nome: "Estadio Padre Ernesto Martearena",
    aliases: ["padre e. martearena", "padre martearena", "martearena"],
    cidade: "Salta",
    regiao: "Salta",
    lat: -24.7859,
    lng: -65.4064,
  },
  {
    nome: "Estadio Malvinas Argentinas",
    aliases: ["malvinas argentinas", "estadio ciudad de mendoza"],
    cidade: "Mendoza",
    regiao: "Mendoza",
    lat: -32.8869,
    lng: -68.8628,
    fonte: "manual/aproximado (Parque General San Martín, Mendoza) - usado por Independiente Rivadavia em competições CONMEBOL",
  },

  /* ===================================================================
     Primera Nacional (2ª divisão Argentina) — adicionados na auditoria
     de coordenadas. Coordenadas em nível de cidade (aproximado).
     =================================================================== */
  {
    nome: "Estadio Islas Malvinas",
    aliases: ["islas malvinas"],
    cidade: "Buenos Aires (Floresta)",
    regiao: "Buenos Aires",
    lat: -34.6339,
    lng: -58.5008,
    fonte: "manual/aproximado (Floresta, CABA — mandante All Boys)",
  },
  {
    nome: "Estadio Nuevo Francisco Urbano",
    aliases: ["francisco urbano", "nuevo francisco urbano"],
    cidade: "Morón",
    regiao: "Buenos Aires",
    lat: -34.6531,
    lng: -58.6197,
    fonte: "manual/aproximado (cidade de Morón — mandante Deportivo Morón)",
  },
  {
    nome: "Estadio Eduardo Gallardón",
    aliases: ["eduardo gallardon", "eduardo gallardón"],
    cidade: "Lomas de Zamora",
    regiao: "Buenos Aires",
    lat: -34.7683,
    lng: -58.3997,
    fonte: "manual/aproximado (cidade de Lomas de Zamora — mandante Los Andes)",
  },
  {
    nome: "Estadio César Luis Menotti",
    aliases: ["cesar luis menotti", "césar luis menotti"],
    cidade: "San Miguel",
    regiao: "Buenos Aires",
    lat: -34.5417,
    lng: -58.7167,
    fonte: "manual/aproximado (cidade de San Miguel — mandante Club San Miguel)",
  },
  {
    nome: "Estadio Gigante del Norte",
    aliases: ["gigante del norte"],
    cidade: "Salta",
    regiao: "Salta",
    lat: -24.7859,
    lng: -65.4117,
    fonte: "manual/aproximado (cidade de Salta — mandante Gimnasia y Tiro)",
  },
  {
    nome: "Estadio 23 de Agosto",
    aliases: ["23 de agosto"],
    cidade: "San Salvador de Jujuy",
    regiao: "Jujuy",
    lat: -24.1858,
    lng: -65.2995,
    fonte: "manual/aproximado (cidade de San Salvador de Jujuy — mandante Gimnasia y Esgrima de Jujuy)",
  },
  {
    nome: "Estadio La Ciudadela",
    aliases: ["la ciudadela"],
    cidade: "San Miguel de Tucumán",
    regiao: "Tucumán",
    lat: -26.8241,
    lng: -65.2226,
    fonte: "manual/aproximado (cidade de Tucumán — mandante San Martín de Tucumán)",
  },
  {
    nome: "Estadio Don León Kolbowski",
    aliases: ["leon kolbowski", "don leon kolbowski"],
    cidade: "Buenos Aires (Villa Crespo)",
    regiao: "Buenos Aires",
    lat: -34.5992,
    lng: -58.4436,
    fonte: "manual/aproximado (Villa Crespo, CABA — mandante Atlanta)",
  },
  {
    nome: "Estadio Presidente Perón",
    aliases: ["presidente peron", "presidente perón"],
    cidade: "Córdoba",
    regiao: "Córdoba",
    lat: -31.3833,
    lng: -64.2333,
    fonte: "manual/aproximado (Barrio Nueva Italia, Córdoba — mandante Racing de Córdoba)",
  },
  {
    nome: "Estadio Ofelia Rosenzuaig",
    aliases: ["ofelia rosenzuaig"],
    cidade: "Carlos Casares",
    regiao: "Buenos Aires",
    lat: -35.6167,
    lng: -61.3833,
    fonte: "manual/aproximado (cidade de Carlos Casares — mandante Agropecuario Argentino)",
  },
  {
    nome: "Estadio Monumental Alfredo Terrera",
    aliases: ["alfredo terrera", "monumental alfredo terrera"],
    cidade: "Rafaela",
    regiao: "Santa Fe",
    lat: -31.2503,
    lng: -61.4867,
    fonte: "manual/aproximado (cidade de Rafaela — mandante Atlético de Rafaela)",
  },
  {
    nome: "Estadio Doctor Osvaldo Baletto",
    aliases: ["osvaldo baletto", "doctor osvaldo baletto"],
    cidade: "Avellaneda (Isla Maciel / Dock Sud)",
    regiao: "Buenos Aires",
    lat: -34.6544,
    lng: -58.3467,
    fonte: "manual/aproximado (Isla Maciel, Dock Sud, Avellaneda — mandante San Telmo) - Wikipedia",
  },
  {
    nome: "Estadio 20 de Octubre",
    aliases: ["20 de octubre"],
    cidade: "Tristán Suárez (Ezeiza)",
    regiao: "Buenos Aires",
    lat: -34.8103,
    lng: -58.5306,
    fonte: "manual/aproximado (Tristán Suárez, Partido de Ezeiza — mandante Tristán Suárez) - Wikipedia",
  },
  {
    nome: "Estadio Brigadier General Estanislao López",
    aliases: ["brigadier general estanislao lopez", "brigadier lopez", "cementerio de los elefantes"],
    cidade: "Santa Fe",
    regiao: "Santa Fe",
    lat: -31.6632,
    lng: -60.7252,
    fonte: "manual/aproximado (cidade de Santa Fe — mandante Colón) - Wikipedia/Wikimapia",
  },
  {
    nome: "Estadio Ciudad de Libertad (Raúl Roberto Sabureau)",
    aliases: ["ciudad de libertad", "raul roberto sabureau"],
    cidade: "Libertad",
    regiao: "Buenos Aires",
    lat: -34.7392,
    lng: -58.7161,
    fonte: "manual/aproximado (Libertad, Buenos Aires — mandante F.C. Midland) - Wikipedia",
  },
  {
    nome: "Estadio Arturo Miranda (La Isla)",
    aliases: ["arturo miranda", "la isla"],
    cidade: "Santiago del Estero",
    regiao: "Santiago del Estero",
    lat: -27.7834,
    lng: -64.2669,
    fonte: "manual/aproximado (cidade de Santiago del Estero — mandante Güemes) - Wikipedia",
  },
];
