/*
  Base de estádios do futebol paraguaio (APF: Copa de Primera, División
  Intermedia). Mesmo formato de estadios.js / estadios_brasil.js /
  estadios_argentina.js / estadios_uruguay.js.
*/

window.ESTADIOS_PARAGUAY = [
  {
    nome: "Estadio Río Parapití",
    aliases: ["rio parapiti", "río parapití", "monumental rio parapiti"],
    cidade: "Pedro Juan Caballero",
    regiao: "Amambay",
    lat: -22.5459,
    lng: -55.7364,
    fonte: "manual/aproximado (cidade de Pedro Juan Caballero)",
  },
  {
    nome: "Estadio ueno Luis Salinas Tanasio",
    aliases: ["luis salinas tanasio", "luis salinas", "estadio ueno luis salinas"],
    cidade: "Itauguá",
    regiao: "Central",
    lat: -25.3959,
    lng: -57.3550,
    fonte: "manual/aproximado (cidade de Itauguá)",
  },
  {
    nome: "Estadio ueno La Nueva Olla (General Pablo Rojas)",
    aliases: ["nueva olla", "general pablo rojas", "la olla", "estadio ueno la nueva olla"],
    cidade: "Asunción",
    regiao: "Asunción",
    lat: -25.3000,
    lng: -57.6375,
  },
  {
    nome: "Estadio Arsenio Erico",
    aliases: ["arsenio erico"],
    cidade: "Asunción",
    regiao: "Asunción",
    lat: -25.3168,
    lng: -57.5807,
  },
  {
    nome: "Estadio Ricardo Gregor",
    aliases: ["ricardo gregor"],
    cidade: "Luque",
    regiao: "Central",
    lat: -25.2637,
    lng: -57.4936,
    fonte: "manual/aproximado (cidade de Luque)",
  },
  {
    nome: "Estadio Ameliano Villeta",
    aliases: ["ameliano villeta", "sportivo ameliano villeta"],
    cidade: "Villeta",
    regiao: "Central",
    lat: -25.5167,
    lng: -57.5500,
    fonte: "manual/aproximado (cidade de Villeta)",
  },

  /* ===================================================================
     Primera B, Primera C, Intermedia (clubes menores) e Copa Paraguay.
     Coordenadas em nivel de bairro/cidade (aproximado). Fontes: Wikipedia
     (Anexo:Estadios de futbol de Paraguay), forum SkyscraperCity
     'Paraguay | Infraestructura Deportiva' (lista time->estadio->bairro),
     ABC Color, Diario HOY, soccerzz.com.
     IMPORTANTE: nas divisoes B/C varios jogos sao mandados em estadios
     COMPARTILHADOS que rodam entre semanas (nao e sempre o estadio do
     'dono'), entao o fallback abaixo e uma aproximacao best-effort -
     o ideal e sempre confiar primeiro no campo estadio vindo direto do
     scraper (que pega da pagina de detalhe do jogo).
     =================================================================== */
  {
    nome: "Estadio 26 de Febrero",
    aliases: ["estadio 26 de febrero"],
    cidade: "Luque",
    regiao: "Paraguay",
    lat: -25.2696,
    lng: -57.4872,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Rafael Giménez",
    aliases: ["estadio rafael gimenez", "rafael gimenez"],
    cidade: "Santo Domingo (Asunción)",
    regiao: "Paraguay",
    lat: -25.256,
    lng: -57.628,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Flaviano Díaz",
    aliases: ["estadio flaviano diaz", "flaviano diaz"],
    cidade: "Barrio Obrero (Asunción)",
    regiao: "Paraguay",
    lat: -25.2989,
    lng: -57.6103,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Celestino Mongelos",
    aliases: ["estadio celestino mongelos", "celestino mongelos"],
    cidade: "Santa Ana (Asunción)",
    regiao: "Paraguay",
    lat: -25.3011,
    lng: -57.5893,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Gregorio Sarubbi Ortiz",
    aliases: ["estadio gregorio sarubbi ortiz", "gregorio sarubbi ortiz"],
    cidade: "Zeballos Cué (Asunción)",
    regiao: "Paraguay",
    lat: -25.323,
    lng: -57.61,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Bernardino Caballero",
    aliases: ["estadio bernardino caballero", "bernardino caballero"],
    cidade: "San Felipe (Asunción)",
    regiao: "Paraguay",
    lat: -25.295,
    lng: -57.635,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Pinozá",
    aliases: ["estadio pinoza", "pinoza"],
    cidade: "Bernardino Caballero (Asunción)",
    regiao: "Paraguay",
    lat: -25.308,
    lng: -57.618,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio 3 de Febrero (Ricardo Brugada)",
    aliases: ["estadio 3 de febrero ricardo brugada", "estadio 3 de febrero"],
    cidade: "Barrio Ricardo Brugada (Asunción)",
    regiao: "Paraguay",
    lat: -25.287,
    lng: -57.635,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Bernabé Pedrozo",
    aliases: ["estadio bernabe pedrozo", "bernabe pedrozo", "benadet pedrozo"],
    cidade: "Barrio Republicano (Asunción)",
    regiao: "Paraguay",
    lat: -25.287,
    lng: -57.625,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio General Adrián Jara",
    aliases: ["estadio general adrian jara", "general adrian jara", "adrian jara"],
    cidade: "Luque",
    regiao: "Paraguay",
    lat: -25.2696,
    lng: -57.4872,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Feliciano Cáceres",
    aliases: ["estadio feliciano caceres", "feliciano caceres"],
    cidade: "Luque",
    regiao: "Paraguay",
    lat: -25.2696,
    lng: -57.4872,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Manuel Ferreira (El Bosque)",
    aliases: ["estadio manuel ferreira el bosque", "manuel ferreira", "el bosque de para uno"],
    cidade: "Bernardino Caballero (Asunción)",
    regiao: "Paraguay",
    lat: -25.308,
    lng: -57.618,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Roberto Bettega",
    aliases: ["estadio roberto bettega", "roberto bettega"],
    cidade: "Zeballos Cué (Asunción)",
    regiao: "Paraguay",
    lat: -25.323,
    lng: -57.61,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Nicolás Leoz",
    aliases: ["estadio nicolas leoz", "nicolas leoz"],
    cidade: "Tuyucuá (Asunción)",
    regiao: "Paraguay",
    lat: -25.245,
    lng: -57.595,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Luis Alfonso Giagni",
    aliases: ["estadio luis alfonso giagni", "luis alfonso giagni"],
    cidade: "Villa Elisa",
    regiao: "Paraguay",
    lat: -25.3628,
    lng: -57.5967,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Juan Canuto Pettengill",
    aliases: ["estadio juan canuto pettengill", "juan canuto pettengill", "juan c pettengill", "juan c petengill"],
    cidade: "Itauguá",
    regiao: "Paraguay",
    lat: -25.3958,
    lng: -57.3552,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Rogelio Livieres",
    aliases: ["estadio rogelio livieres", "rogelio livieres"],
    cidade: "Barrio Pinozá (Asunción)",
    regiao: "Paraguay",
    lat: -25.308,
    lng: -57.618,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Salustiano Zaracho (Molino)",
    aliases: ["estadio salustiano zaracho molino", "salustiano zaracho", "estadio molino"],
    cidade: "Luque",
    regiao: "Paraguay",
    lat: -25.2696,
    lng: -57.4872,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Agustín Báez (Pilcomayo)",
    aliases: ["estadio agustin baez pilcomayo", "agustin baez pilcomayo"],
    cidade: "Mariano Roque Alonso",
    regiao: "Paraguay",
    lat: -25.2001,
    lng: -57.5297,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ricardo Grégor",
    aliases: ["estadio ricardo gregor", "ricardo gregor"],
    cidade: "Campo Grande (Asunción)",
    regiao: "Paraguay",
    lat: -25.315,
    lng: -57.598,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Pioneros de Corumbá Cué",
    aliases: ["estadio pioneros de corumba cue", "pioneros de corumba cue"],
    cidade: "Mariano Roque Alonso",
    regiao: "Paraguay",
    lat: -25.2001,
    lng: -57.5297,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Andrés Rodríguez",
    aliases: ["estadio andres rodriguez", "andres rodriguez"],
    cidade: "Salvador del Mundo (Asunción)",
    regiao: "Paraguay",
    lat: -25.323,
    lng: -57.585,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Roque F. Batelhana",
    aliases: ["estadio roque f batelhana", "roque f batelhana", "roque batelhana"],
    cidade: "Recoleta (Asunción)",
    regiao: "Paraguay",
    lat: -25.282,
    lng: -57.568,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Enrique Soler",
    aliases: ["estadio enrique soler", "enrique soler"],
    cidade: "Capiatá",
    regiao: "Paraguay",
    lat: -25.3556,
    lng: -57.4453,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Federico Llamosas",
    aliases: ["estadio federico llamosas", "federico llamosas"],
    cidade: "Caaguazú",
    regiao: "Paraguay",
    lat: -25.4644,
    lng: -56.0192,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ypané",
    aliases: ["estadio ypane"],
    cidade: "Ypané",
    regiao: "Paraguay",
    lat: -25.1667,
    lng: -57.4667,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Juan José Vázquez",
    aliases: ["estadio juan jose vazquez", "juan jose vazquez"],
    cidade: "San Estanislao",
    regiao: "Paraguay",
    lat: -24.6275,
    lng: -56.4358,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Municipal de Carapeguá",
    aliases: ["estadio municipal de carapegua", "municipal de carapegua"],
    cidade: "Carapeguá",
    regiao: "Paraguay",
    lat: -25.7897,
    lng: -57.2589,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Antonio Oddone Sarubbi",
    aliases: ["estadio antonio oddone sarubbi", "antonio oddone sarubbi"],
    cidade: "Ciudad del Este",
    regiao: "Paraguay",
    lat: -25.5163,
    lng: -54.6111,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Ovetenses Unidos",
    aliases: ["estadio ovetenses unidos"],
    cidade: "Coronel Oviedo",
    regiao: "Paraguay",
    lat: -25.4319,
    lng: -56.4406,
    fonte: "manual/aproximado",
  },
  {
    nome: "Estadio Hugo Stroessner (Encarnación)",
    aliases: ["estadio hugo stroessner encarnacion", "hugo stroessner"],
    cidade: "Encarnación",
    regiao: "Paraguay",
    lat: -27.3306,
    lng: -55.8664,
    fonte: "manual/aproximado",
  },
  {
    nome: "Sede do Rubio Ñú (aproximado por cidade)",
    aliases: ["sede do rubio nu aproximado por cidade"],
    cidade: "Santísima Trinidad (Asunción)",
    regiao: "Paraguay",
    lat: -25.2667,
    lng: -57.5833,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Fernando de la Mora (aproximado por cidade)",
    aliases: ["sede do fernando de la mora aproximado por cidade"],
    cidade: "Fernando de la Mora",
    regiao: "Paraguay",
    lat: -25.3308,
    lng: -57.5647,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Sport Colombia (aproximado por cidade)",
    aliases: ["sede do sport colombia aproximado por cidade"],
    cidade: "Fernando de la Mora",
    regiao: "Paraguay",
    lat: -25.3308,
    lng: -57.5647,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do 24 de Setiembre (aproximado por cidade)",
    aliases: ["sede do 24 de setiembre aproximado por cidade"],
    cidade: "Areguá",
    regiao: "Paraguay",
    lat: -25.3122,
    lng: -57.4014,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do 29 de Setiembre (aproximado por cidade)",
    aliases: ["sede do 29 de setiembre aproximado por cidade"],
    cidade: "Luque",
    regiao: "Paraguay",
    lat: -25.2696,
    lng: -57.4872,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Cristóbal Colón JAS (aproximado por cidade)",
    aliases: ["sede do cristobal colon jas aproximado por cidade"],
    cidade: "Julián Augusto Saldívar",
    regiao: "Paraguay",
    lat: -25.32,
    lng: -57.51,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Cristóbal Colón de Ñemby (aproximado por cidade)",
    aliases: ["sede do cristobal colon de nemby aproximado por cidade"],
    cidade: "Ñemby",
    regiao: "Paraguay",
    lat: -25.3969,
    lng: -57.5386,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Atlético Colegiales (aproximado por cidade)",
    aliases: ["sede do atletico colegiales aproximado por cidade"],
    cidade: "Lambaré",
    regiao: "Paraguay",
    lat: -25.3428,
    lng: -57.6067,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Capitán Figari (aproximado por cidade)",
    aliases: ["sede do capitan figari aproximado por cidade"],
    cidade: "Lambaré",
    regiao: "Paraguay",
    lat: -25.3428,
    lng: -57.6067,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Sportivo Iteño (aproximado por cidade)",
    aliases: ["sede do sportivo iteno aproximado por cidade"],
    cidade: "Itá",
    regiao: "Paraguay",
    lat: -25.5075,
    lng: -57.3592,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Sportivo Limpeño (aproximado por cidade)",
    aliases: ["sede do sportivo limpeno aproximado por cidade"],
    cidade: "Limpio",
    regiao: "Paraguay",
    lat: -25.1636,
    lng: -57.4939,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Presidente Hayes (aproximado por cidade)",
    aliases: ["sede do presidente hayes aproximado por cidade"],
    cidade: "Barrio Tacumbú (Asunción)",
    regiao: "Paraguay",
    lat: -25.32,
    lng: -57.61,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Benjamín Aceval (aproximado por cidade)",
    aliases: ["sede do benjamin aceval aproximado por cidade"],
    cidade: "Villa Hayes",
    regiao: "Paraguay",
    lat: -25.0956,
    lng: -57.5389,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Atyrá (aproximado por cidade)",
    aliases: ["sede do atyra aproximado por cidade"],
    cidade: "Atyrá",
    regiao: "Paraguay",
    lat: -25.2667,
    lng: -57.15,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do Oriental (aproximado por cidade)",
    aliases: ["sede do oriental aproximado por cidade"],
    cidade: "Barrio Ricardo Brugada (Asunción)",
    regiao: "Paraguay",
    lat: -25.287,
    lng: -57.635,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do 1 de Marzo (aproximado por cidade)",
    aliases: ["sede do 1 de marzo aproximado por cidade"],
    cidade: "Fernando de la Mora",
    regiao: "Paraguay",
    lat: -25.3308,
    lng: -57.5647,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Sede do 3 de Noviembre (aproximado por cidade)",
    aliases: ["sede do 3 de noviembre aproximado por cidade"],
    cidade: "Asunción",
    regiao: "Paraguay",
    lat: -25.2637,
    lng: -57.5759,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Estadio General Bruguez",
    aliases: ["estadio general bruguez"],
    cidade: "Paraguarí",
    regiao: "Paraguay",
    lat: -25.6294,
    lng: -57.1547,
    fonte: "manual/aproximado (cidade de Paraguarí)",
  },
  {
    nome: "Estadio Facundo de León Fossatti",
    aliases: ["estadio facundo de leon fossatti"],
    cidade: "Villa Hayes",
    regiao: "Paraguay",
    lat: -25.0956,
    lng: -57.5389,
    fonte: "manual/aproximado (cidade de Villa Hayes)",
  },
  {
    nome: "Sede do Encarnación FC (aproximado por cidade)",
    aliases: ["sede do encarnacion fc aproximado por cidade"],
    cidade: "Encarnación",
    regiao: "Paraguay",
    lat: -27.3306,
    lng: -55.8664,
    fonte: "manual/aproximado (sem estadio proprio confirmado)",
  },
  {
    nome: "Estadio Parque del Guairá",
    aliases: ["parque del guaira", "parque del guairá"],
    cidade: "Villarrica",
    regiao: "Paraguay",
    lat: -25.7833,
    lng: -56.4333,
    fonte: "manual/confirmado (estádio do Guaireña FC, Villarrica — ABC Color)",
  },
  {
    nome: "Estadio Erico Galeano",
    aliases: ["erico galeano"],
    cidade: "Capiatá",
    regiao: "Paraguay",
    lat: -25.3556,
    lng: -57.4453,
    fonte: "manual/confirmado (estádio do Deportivo Capiatá — ABC Color)",
  },
];
