/*
  Base de estádios do futebol uruguaio (AUF: Liga AUF Uruguaya, Primera
  Divisional C, etc.). Mesmo formato de estadios.js / estadios_brasil.js /
  estadios_argentina.js.
*/

window.ESTADIOS_URUGUAY = [
  {
    nome: "Estadio Centenario",
    aliases: ["centenario", "estadio centenario"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8941,
    lng: -56.1568,
  },
  {
    nome: "Gran Parque Central",
    aliases: ["gran parque central"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8958,
    lng: -56.1656,
  },
  {
    nome: "Estadio Juventud Parque Artigas",
    aliases: ["parque artigas", "juventud parque artigas"],
    cidade: "Las Piedras",
    regiao: "Canelones",
    lat: -34.7167,
    lng: -56.2167,
  },
  {
    nome: "Estadio Luis Franzini",
    aliases: ["luis franzini", "franzini"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.9014,
    lng: -56.1567,
  },
  {
    nome: "Estadio Domingo Burgueño Miguel",
    aliases: ["domingo burgueno miguel", "domingo burgueño miguel", "burgueño"],
    cidade: "Maldonado",
    regiao: "Maldonado",
    lat: -34.9058,
    lng: -54.9628,
  },
  {
    nome: "Estadio Abraham Paladino",
    aliases: ["abraham paladino", "paladino"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8494,
    lng: -56.2364,
  },
  {
    nome: "Estadio Alfredo Víctor Viera",
    aliases: ["alfredo victor viera", "alfredo víctor viera"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8497,
    lng: -56.1858,
  },
  {
    nome: "Estadio Jardines del Hipódromo",
    aliases: ["jardines del hipodromo", "jardines del hipódromo"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8433,
    lng: -56.1719,
  },
  {
    nome: "Estadio Charrúa",
    aliases: ["charrua", "estadio charrua", "charrúa"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8956,
    lng: -56.0840,
  },
  {
    nome: "Estadio Cr. José Pedro Damiani (Las Acacias)",
    aliases: ["jose pedro damiani", "josé pedro damiani", "las acacias", "cr jose pedro damiani"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8280,
    lng: -56.2075,
  },
  {
    nome: "Estadio Municipal de Pando",
    aliases: ["municipal de pando", "estadio municipal de pando"],
    cidade: "Pando",
    regiao: "Canelones",
    lat: -34.7167,
    lng: -55.9578,
  },
  {
    nome: "Parque Ancap",
    aliases: ["parque ancap"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8631,
    lng: -56.2229,
  },
  {
    nome: "Parque Huracán Buceo",
    aliases: ["huracan buceo", "parque huracan buceo", "huracán buceo"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.9070,
    lng: -56.1250,
  },
  {
    nome: "Parque Palermo",
    aliases: ["parque palermo"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.9130,
    lng: -56.1930,
  },
  {
    nome: "Estadio Obdulio Varela",
    aliases: ["obdulio varela", "estadio obdulio varela"],
    cidade: "Las Piedras",
    regiao: "Canelones",
    lat: -34.7167,
    lng: -56.2167,
  },
  {
    nome: "Complejo Milton Gonnet",
    aliases: ["milton gonnet", "complejo milton gonnet"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8500,
    lng: -56.1800,
  },
  {
    nome: "Estadio Juan José Vispo Marí",
    aliases: ["juan jose vispo mari", "vispo mari", "juan josé vispo marí"],
    cidade: "Montevideo",
    regiao: "Montevideo",
    lat: -34.8500,
    lng: -56.1800,
  },
  {
    nome: "Estadio Matías González",
    aliases: ["matias gonzalez", "estadio matias gonzalez"],
    cidade: "Artigas",
    regiao: "Artigas",
    lat: -30.4034,
    lng: -56.4708,
    fonte: "manual/osm-like",
  },
];
