/*
  Base de estádios do futebol brasileiro (CBF: Série A/B/C/D, Copa do Brasil).

  Mesmo formato de /estadios.js (Chile), usado pelo script.js para
  resolver cidade, estado (regiao) e coordenadas dos jogos do Brasil
  quando o campo "estadio" do scraper bate com um destes nomes.

  Campos:
  - nome: nome principal
  - aliases: variações do nome que podem aparecer no JSON
  - cidade
  - regiao: estado (UF por extenso)
  - lat/lng
*/

window.ESTADIOS_BRASIL = [
  {
    nome: "Allianz Parque",
    aliases: ["allianz parque", "arena palmeiras", "nubank parque"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.5273,
    lng: -46.6783,
  },
  {
    nome: "Arena Condá",
    aliases: ["arena conda", "arena condá"],
    cidade: "Chapecó",
    regiao: "Santa Catarina",
    lat: -27.0910,
    lng: -52.6222,
  },
  {
    nome: "Arena Fonte Nova",
    aliases: ["arena fonte nova", "fonte nova", "itaipava arena fonte nova"],
    cidade: "Salvador",
    regiao: "Bahia",
    lat: -12.9836,
    lng: -38.5054,
  },
  {
    nome: "Arena MRV",
    aliases: ["arena mrv"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.8657,
    lng: -44.0994,
  },
  {
    nome: "Arena da Baixada",
    aliases: ["arena da baixada", "ligga arena", "joaquim americo"],
    cidade: "Curitiba",
    regiao: "Paraná",
    lat: -25.4483,
    lng: -49.2731,
  },
  {
    nome: "Arena do Grêmio",
    aliases: ["arena do gremio", "arena do grêmio"],
    cidade: "Porto Alegre",
    regiao: "Rio Grande do Sul",
    lat: -29.9827,
    lng: -51.0680,
  },
  {
    nome: "Estádio Barradão",
    aliases: ["barradão", "barradao"],
    cidade: "Salvador",
    regiao: "Bahia",
    lat: -12.9481,
    lng: -38.4489,
  },
  {
    nome: "Estádio Beira-Rio",
    aliases: ["beira-rio", "beira rio"],
    cidade: "Porto Alegre",
    regiao: "Rio Grande do Sul",
    lat: -30.0653,
    lng: -51.2352,
  },
  {
    nome: "Estádio Couto Pereira",
    aliases: ["couto pereira"],
    cidade: "Curitiba",
    regiao: "Paraná",
    lat: -25.4406,
    lng: -49.2439,
  },
  {
    nome: "Estádio Municipal Cícero de Souza Marques",
    aliases: ["cícero s. marques", "cicero s. marques", "cícero de souza marques", "cicero de souza marques"],
    cidade: "Bragança Paulista",
    regiao: "São Paulo",
    lat: -22.9519,
    lng: -46.5419,
  },
  {
    nome: "Estádio José Maria de Campos Maia",
    aliases: ["josé m. c. maia", "jose m. c. maia", "josé maria de campos maia"],
    cidade: "Mirassol",
    regiao: "São Paulo",
    lat: -20.8181,
    lng: -49.5222,
  },
  {
    nome: "Estádio Olímpico do Pará (Mangueirão)",
    aliases: ["mangueirão", "mangueirao", "olimpico do para"],
    cidade: "Belém",
    regiao: "Pará",
    lat: -1.4108,
    lng: -48.4489,
  },
  {
    nome: "Maracanã",
    aliases: ["maracanã", "maracana", "estadio do maracana"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9121,
    lng: -43.2302,
  },
  {
    nome: "Mineirão",
    aliases: ["mineirão", "mineirao", "governador magalhães pinto", "governador magalhaes pinto", "estadio governador magalhaes pinto"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.8656,
    lng: -43.9695,
  },
  {
    nome: "MorumBIS",
    aliases: ["morumbis", "morumbi", "estadio cicero pompeu de toledo"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.6003,
    lng: -46.7194,
  },
  {
    nome: "Neo Química Arena",
    aliases: ["neo quimica arena", "neo química arena", "arena corinthians"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.5453,
    lng: -46.4742,
  },
  {
    nome: "Estádio Nilton Santos",
    aliases: ["nilton santos", "engenhão", "engenhao"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8925,
    lng: -43.2300,
  },
  {
    nome: "Estádio São Januário",
    aliases: ["são januário", "sao januario"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8917,
    lng: -43.2286,
  },
  {
    nome: "Estádio Urbano Caldeira (Vila Belmiro)",
    aliases: ["vila belmiro", "urbano caldeira"],
    cidade: "Santos",
    regiao: "São Paulo",
    lat: -23.9469,
    lng: -46.3353,
  },
  {
    nome: "Estádio Santa Cruz",
    aliases: ["santa cruz"],
    cidade: "Ribeirão Preto",
    regiao: "São Paulo",
    lat: -21.1775,
    lng: -47.8103,
  },
  {
    nome: "Estádio Onésio Brasileiro Alvarenga (Serrinha)",
    aliases: ["onésio b. alvarenga", "onesio b. alvarenga", "onésio brasileiro alvarenga", "serrinha"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6764,
    lng: -49.2643,
  },
  {
    nome: "Estádio Augusto Bauer",
    aliases: ["augusto bauer", "augusto"],
    cidade: "Brusque",
    regiao: "Santa Catarina",
    lat: -27.0961,
    lng: -48.9107,
  },
  {
    nome: "Estádio Centenário",
    aliases: ["centenário", "centenario"],
    cidade: "Caxias do Sul",
    regiao: "Rio Grande do Sul",
    lat: -29.1686,
    lng: -51.1794,
  },
  {
    nome: "Arena Pantanal",
    aliases: ["arena pantanal"],
    cidade: "Cuiabá",
    regiao: "Mato Grosso",
    lat: -15.6014,
    lng: -56.1025,
  },
  {
    nome: "Arena Castelão",
    aliases: ["arena castelão", "arena castelao", "castelão", "castelao"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.8071,
    lng: -38.5219,
  },
  {
    nome: "Estádio Heriberto Hülse",
    aliases: ["heriberto hülse", "heriberto hulse"],
    cidade: "Criciúma",
    regiao: "Santa Catarina",
    lat: -28.6775,
    lng: -49.3697,
  },
  {
    nome: "Estádio Jorge Ismael de Biasi",
    aliases: ["jorge ismael de biasi", "jorge de biasi"],
    cidade: "Novo Horizonte",
    regiao: "São Paulo",
    lat: -21.4644,
    lng: -49.2214,
  },
  {
    nome: "Estádio Vitorino Gonçalves Dias",
    aliases: ["vitorino gonçalves dias", "vitorino goncalves dias"],
    cidade: "Londrina",
    regiao: "Paraná",
    lat: -23.3103,
    lng: -51.1628,
  },
  {
    nome: "Estádio Hailé Pinheiro",
    aliases: ["hailé pinheiro", "haile pinheiro"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6395,
    lng: -49.2903,
  },
  {
    nome: "Estádio Moisés Lucarelli",
    aliases: ["moisés lucarelli", "moises lucarelli"],
    cidade: "Campinas",
    regiao: "São Paulo",
    lat: -22.9067,
    lng: -47.0517,
  },
  {
    nome: "Estádio Alfredo Jaconi",
    aliases: ["alfredo jaconi"],
    cidade: "Caxias do Sul",
    regiao: "Rio Grande do Sul",
    lat: -29.1544,
    lng: -51.1636,
  },
  {
    nome: "Estádio Ilha do Retiro",
    aliases: ["ilha do retiro"],
    cidade: "Recife",
    regiao: "Pernambuco",
    lat: -8.0631,
    lng: -34.9086,
  },
  {
    nome: "Estádio Rei Pelé",
    aliases: ["rei pelé", "rei pele"],
    cidade: "Maceió",
    regiao: "Alagoas",
    lat: -9.6208,
    lng: -35.7181,
  },
  {
    nome: "Independência",
    aliases: ["arena da independência", "arena da independencia", "independência"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.9186,
    lng: -43.9411,
  },
  {
    nome: "Estádio Orlando Scarpelli",
    aliases: ["orlando scarpelli", "scarpelli"],
    cidade: "Florianópolis",
    regiao: "Santa Catarina",
    lat: -27.5972,
    lng: -48.5450,
  },
  {
    nome: "Estádio Curuzu",
    aliases: ["curuzu"],
    cidade: "Belém",
    regiao: "Pará",
    lat: -1.4392,
    lng: -48.4642,
  },
  {
    nome: "Estádio Almeidão",
    aliases: ["almeidão", "almeidao"],
    cidade: "João Pessoa",
    regiao: "Paraíba",
    lat: -7.1362,
    lng: -34.8578,
  },
  {
    nome: "Estádio Raulino de Oliveira",
    aliases: ["raulino de oliveira"],
    cidade: "Volta Redonda",
    regiao: "Rio de Janeiro",
    lat: -22.5202,
    lng: -44.1042,
  },
  {
    nome: "Arena Batistão",
    aliases: ["arena batistão", "arena batistao", "batistão"],
    cidade: "Aracaju",
    regiao: "Sergipe",
    lat: -10.9350,
    lng: -37.0731,
  },
  {
    nome: "Estádio Brinco de Ouro da Princesa",
    aliases: ["brinco de ouro", "brinco de ouro da princesa"],
    cidade: "Campinas",
    regiao: "São Paulo",
    lat: -22.9040,
    lng: -47.0850,
  },
  {
    nome: "Estádio Germano Krüger",
    aliases: ["germano kruger", "germano krüger"],
    cidade: "Ponta Grossa",
    regiao: "Paraná",
    lat: -25.0916,
    lng: -50.1668,
  },
  {
    nome: "Arena Pernambuco",
    aliases: ["arena pernambuco", "arena pernambuco s. lourenço"],
    cidade: "São Lourenço da Mata",
    regiao: "Pernambuco",
    lat: -8.0186,
    lng: -35.0119,
  },
  {
    nome: "Estádio Primeiro de Maio",
    aliases: ["1º de maio", "primeiro de maio", "1º de maio são bernardo"],
    cidade: "São Bernardo do Campo",
    regiao: "São Paulo",
    lat: -23.7167,
    lng: -46.5567,
  },
  {
    nome: "Estádio da Ressacada",
    aliases: ["ressacada"],
    cidade: "Florianópolis",
    regiao: "Santa Catarina",
    lat: -27.6797,
    lng: -48.5583,
  },
  {
    nome: "Estádio Frasqueirão (Saraivão)",
    aliases: ["saraivao", "saraivão", "frasqueirao"],
    cidade: "Ivinhema",
    regiao: "Mato Grosso do Sul",
    lat: -22.3033,
    lng: -53.8181,
  },
  {
    nome: "Arena das Dunas",
    aliases: ["arena das dunas"],
    cidade: "Natal",
    regiao: "Rio Grande do Norte",
    lat: -5.8236,
    lng: -35.2306,
  },
  {
    nome: "Estádio Bezerrão",
    aliases: ["bezerrao", "bezerrão"],
    cidade: "Gama",
    regiao: "Distrito Federal",
    lat: -15.9989,
    lng: -48.0611,
  },
  {
    nome: "Estádio Guilherme da Silveira Filho (Luso Brasileiro)",
    aliases: ["luso brasileiro", "guilherme da silveira"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8781,
    lng: -43.4642,
  },
  {
    nome: "Estádio Comendador Souza (Canindé)",
    aliases: ["caninde", "canindé", "comendador souza"],
    cidade: "São Paulo",
    regiao: "São Paulo",
    lat: -23.5217,
    lng: -46.6297,
  },
  {
    nome: "Estádio Municipal Parque do Sabiá",
    aliases: ["parque do sabia", "parque do sabiá"],
    cidade: "Uberlândia",
    regiao: "Minas Gerais",
    lat: -18.9142,
    lng: -48.2661,
  },
  {
    nome: "Estádio Amigão",
    aliases: ["amigao", "amigão"],
    cidade: "Campina Grande",
    regiao: "Paraíba",
    lat: -7.2325,
    lng: -35.8817,
  },
  {
    nome: "Estádio Presidente Vargas",
    aliases: ["presidente vargas"],
    cidade: "Fortaleza",
    regiao: "Ceará",
    lat: -3.7431,
    lng: -38.5406,
  },
  {
    nome: "Estádio Municipal João Saldanha",
    aliases: ["joao saldanha", "joão saldanha", "municipal joao saldanha"],
    cidade: "Maricá",
    regiao: "Rio de Janeiro",
    lat: -22.9195,
    lng: -42.8186,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Nivaldo Pereira (São Januário / CT Vasco)",
    aliases: ["nivaldo pereira"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8912,
    lng: -43.2229,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Jânio de Moraes (Laranjão)",
    aliases: ["janio de moraes", "jânio de moraes", "laranjao", "laranjão"],
    cidade: "Nova Iguaçu",
    regiao: "Rio de Janeiro",
    lat: -22.7556,
    lng: -43.4603,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Eduardo Guinle",
    aliases: ["eduardo guinle"],
    cidade: "Nova Friburgo",
    regiao: "Rio de Janeiro",
    lat: -22.2819,
    lng: -42.5311,
    fonte: "aproximado/cidade",
  },
  {
    nome: "CT do Boavista",
    aliases: ["ct do boavista", "boavista"],
    cidade: "Saquarema",
    regiao: "Rio de Janeiro",
    lat: -22.9200,
    lng: -42.5100,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Marcelo Vieira",
    aliases: ["marcelo vieira"],
    cidade: "Maricá",
    regiao: "Rio de Janeiro",
    lat: -22.9195,
    lng: -42.8186,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Municipal do Trabalhador (SESI)",
    aliases: ["municipal do trabalhador", "e. do sesi", "estadio do sesi"],
    cidade: "Resende",
    regiao: "Rio de Janeiro",
    lat: -22.4705,
    lng: -44.4509,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Antônio Ferreira de Medeiros",
    aliases: ["antonio ferreira de medeiros", "antônio ferreira de medeiros"],
    cidade: "Cardoso Moreira",
    regiao: "Rio de Janeiro",
    lat: -21.5850,
    lng: -41.4200,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Alair Corrêa",
    aliases: ["alair correa", "alair corrêa"],
    cidade: "Volta Redonda",
    regiao: "Rio de Janeiro",
    lat: -22.5202,
    lng: -44.1041,
    fonte: "aproximado/cidade - a confirmar",
  },
  {
    nome: "Estádio Giulite Coutinho (Edson Passos)",
    aliases: ["giulite coutinho", "edson passos"],
    cidade: "Mesquita",
    regiao: "Rio de Janeiro",
    lat: -22.7889,
    lng: -43.4392,
    fonte: "aproximado/cidade",
  },
  {
    nome: "Estádio Ítalo Del Cima",
    aliases: ["italo del cima", "ítalo del cima"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9020,
    lng: -43.5610,
  },
  {
    nome: "Estádio Leônidas da Silva",
    aliases: ["leonidas da silva", "leônidas da silva"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8620,
    lng: -43.2540,
  },
  {
    nome: "Estádio Prefeito Ismael de Souza Leão do Sul",
    aliases: ["ismael de souza", "leao do sul", "leão do sul"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9068,
    lng: -43.1729,
    fonte: "aproximado/cidade - a confirmar",
  },
  {
    nome: "Estádio de Los Lários",
    aliases: ["los larios", "los lários"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.9068,
    lng: -43.1729,
    fonte: "aproximado/cidade - a confirmar",
  },
  {
    nome: "Estádio Antônio Ferreira de Medeiros (Ferreirão)",
    aliases: ["antonio ferreira de medeiros", "antônio ferreira de medeiros", "ferreirao", "ferreirão"],
    cidade: "Cardoso Moreira",
    regiao: "Rio de Janeiro",
    lat: -21.5589,
    lng: -41.5158,
    fonte: "manual/aproximado (Cardoso Moreira, RJ)",
  },
  {
    nome: "Estádio Alair Corrêa (Correão)",
    aliases: ["alair correa", "alair corrêa", "correao", "correão"],
    cidade: "Cabo Frio",
    regiao: "Rio de Janeiro",
    lat: -22.8794,
    lng: -42.0186,
    fonte: "manual/aproximado (Cabo Frio, RJ)",
  },
  {
    nome: "Estádio Leônidas da Silva (Teixeira de Castro)",
    aliases: ["leonidas da silva", "leônidas da silva", "teixeira de castro"],
    cidade: "Rio de Janeiro",
    regiao: "Rio de Janeiro",
    lat: -22.8657,
    lng: -43.2578,
    fonte: "manual/aproximado (Bonsucesso, Rio de Janeiro)",
  },
  {
    nome: "Estádio Paulo Paschoalino",
    aliases: ["paulo paschoalino"],
    cidade: "Ubá",
    regiao: "Minas Gerais",
    lat: -21.1206,
    lng: -42.9434,
    fonte: "manual/aproximado (cidade de Ubá)",
  },
  {
    nome: "Estádio Flávio Pentagna Guimarães",
    aliases: ["flavio pentagna guimaraes"],
    cidade: "Contagem",
    regiao: "Minas Gerais",
    lat: -19.9317,
    lng: -44.0536,
    fonte: "manual/aproximado (cidade de Contagem)",
  },
  {
    nome: "José Flávio de Carvalho",
    aliases: ["jose flavio de carvalho"],
    cidade: "Itaúna",
    regiao: "Minas Gerais",
    lat: -20.0714,
    lng: -44.5789,
    fonte: "manual/aproximado (cidade de Itaúna)",
  },
  {
    nome: "Victor Andrade de Brito - Frimisa",
    aliases: ["victor andrade de brito", "frimisa"],
    cidade: "Santa Luzia",
    regiao: "Minas Gerais",
    lat: -19.7697,
    lng: -43.8514,
    fonte: "manual/aproximado (cidade de Santa Luzia)",
  },
  {
    nome: "Estádio José dos Santos (Campo do DER)",
    aliases: ["jose dos santos", "campo do der"],
    cidade: "Oliveira",
    regiao: "Minas Gerais",
    lat: -20.6975,
    lng: -44.8283,
    fonte: "manual/aproximado (cidade de Oliveira)",
  },
  {
    nome: "Arena Prime BH",
    aliases: ["arena prime bh"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.9167,
    lng: -43.9345,
    fonte: "manual/aproximado (cidade de Belo Horizonte)",
  },
  {
    nome: "CT Credinor - North EC",
    aliases: ["ct credinor", "north ec"],
    cidade: "Montes Claros",
    regiao: "Minas Gerais",
    lat: -16.7350,
    lng: -43.8617,
    fonte: "manual/aproximado (cidade de Montes Claros)",
  },
  {
    nome: "Instituto Bola Preta",
    aliases: ["instituto bola preta"],
    cidade: "Eloi Mendes",
    regiao: "Minas Gerais",
    lat: -21.6144,
    lng: -45.5964,
    fonte: "manual/aproximado (cidade de Elói Mendes)",
  },
  {
    nome: "Radialista Mário Helênio",
    aliases: ["mario helenio", "radialista mario helenio"],
    cidade: "Juiz de Fora",
    regiao: "Minas Gerais",
    lat: -21.7642,
    lng: -43.3467,
    fonte: "manual/aproximado (cidade de Juiz de Fora)",
  },
  {
    nome: "Campo do Durval de Barros",
    aliases: ["durval de barros"],
    cidade: "Ibirité",
    regiao: "Minas Gerais",
    lat: -20.0233,
    lng: -44.0578,
    fonte: "manual/aproximado (cidade de Ibirité)",
  },
  {
    nome: "Estádio Engenheiro João Guido (Uberabão)",
    aliases: ["engenheiro joao guido", "uberabao"],
    cidade: "Uberaba",
    regiao: "Minas Gerais",
    lat: -19.7483,
    lng: -47.9319,
    fonte: "manual/aproximado (cidade de Uberaba)",
  },
  {
    nome: "Estádio Castor Cifuentes (Alçapão do Bonfim)",
    aliases: ["castor cifuentes", "alcapao do bonfim"],
    cidade: "Nova Lima",
    regiao: "Minas Gerais",
    lat: -19.9861,
    lng: -43.8467,
    fonte: "manual/aproximado (cidade de Nova Lima)",
  },
  {
    nome: "Estádio João Lamego Netto (Ipatingão)",
    aliases: ["joao lamego netto", "ipatingao"],
    cidade: "Ipatinga",
    regiao: "Minas Gerais",
    lat: -19.4683,
    lng: -42.5367,
    fonte: "manual/aproximado (cidade de Ipatinga)",
  },
  {
    nome: "Pedro Alves do Nascimento",
    aliases: ["pedro alves do nascimento"],
    cidade: "Patrocínio",
    regiao: "Minas Gerais",
    lat: -18.9436,
    lng: -46.9928,
    fonte: "manual/aproximado (cidade de Patrocínio)",
  },
  {
    nome: "Juca Pedro",
    aliases: ["juca pedro"],
    cidade: "Formiga",
    regiao: "Minas Gerais",
    lat: -20.4664,
    lng: -45.4264,
    fonte: "manual/aproximado (cidade de Formiga)",
  },
  {
    nome: "Estádio Louis Ensch (Luisão)",
    aliases: ["louis ensch", "louís ensch", "luisao"],
    cidade: "Coronel Fabriciano",
    regiao: "Minas Gerais",
    lat: -19.5186,
    lng: -42.6289,
    fonte: "manual/aproximado (cidade de Coronel Fabriciano)",
  },
  {
    nome: "Arena Morro das Pedras",
    aliases: ["arena morro das pedras"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.9167,
    lng: -43.9345,
    fonte: "manual/aproximado (cidade de Belo Horizonte)",
  },
  {
    nome: "Toca da Raposa I",
    aliases: ["toca da raposa"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.9167,
    lng: -43.9345,
    fonte: "manual/aproximado (cidade de Belo Horizonte)",
  },
  {
    nome: "Estádio Bela Vista F.C.",
    aliases: ["bela vista fc"],
    cidade: "Sete Lagoas",
    regiao: "Minas Gerais",
    lat: -19.4658,
    lng: -44.2467,
    fonte: "manual/aproximado (cidade de Sete Lagoas)",
  },
  {
    nome: "Campo do Real",
    aliases: ["campo do real"],
    cidade: "Caeté",
    regiao: "Minas Gerais",
    lat: -19.8767,
    lng: -43.6739,
    fonte: "manual/aproximado (cidade de Caeté)",
  },
  {
    nome: "Campo do Alvorada",
    aliases: ["campo do alvorada"],
    cidade: "Belo Horizonte",
    regiao: "Minas Gerais",
    lat: -19.9167,
    lng: -43.9345,
    fonte: "manual/aproximado (cidade de Belo Horizonte)",
  },
  {
    nome: "Arena TCM Novo Cristina",
    aliases: ["arena tcm novo cristina", "tcm novo cristina"],
    cidade: "Betim",
    regiao: "Minas Gerais",
    lat: -19.9678,
    lng: -44.1983,
    fonte: "manual/aproximado (cidade de Betim)",
  },
  {
    nome: "Estádio Neca da Cunha",
    aliases: ["neca da cunha"],
    cidade: "Prudente de Morais",
    regiao: "Minas Gerais",
    lat: -19.5011,
    lng: -44.1531,
    fonte: "manual/aproximado (cidade de Prudente de Morais)",
  },
  {
    nome: "Estádio Dr. Luís Carlos Lobato",
    aliases: ["luis carlos lobato", "luís carlos lobato"],
    cidade: "Carmo da Mata",
    regiao: "Minas Gerais",
    lat: -20.1147,
    lng: -44.9636,
    fonte: "manual/aproximado (cidade de Carmo da Mata)",
  },
  {
    nome: "Estádio Chico Marques",
    aliases: ["chico marques"],
    cidade: "Bom Despacho",
    regiao: "Minas Gerais",
    lat: -19.7386,
    lng: -45.2517,
    fonte: "manual/aproximado (cidade de Bom Despacho)",
  },
  {
    nome: "Estádio Arthur Ferreira Campos",
    aliases: ["arthur ferreira campos"],
    cidade: "Mário Campos",
    regiao: "Minas Gerais",
    lat: -20.1114,
    lng: -44.1861,
    fonte: "manual/aproximado (cidade de Mário Campos)",
  },
  {
    nome: "Campo do Barrinha",
    aliases: ["campo do barrinha"],
    cidade: "Viçosa",
    regiao: "Minas Gerais",
    lat: -20.7546,
    lng: -42.8814,
    fonte: "manual/aproximado (cidade de Viçosa)",
  },
  {
    nome: "Campo do Sport",
    aliases: ["campo do sport"],
    cidade: "Carmo do Cajuru",
    regiao: "Minas Gerais",
    lat: -20.1656,
    lng: -44.7622,
    fonte: "manual/aproximado (cidade de Carmo do Cajuru)",
  },
  {
    nome: "Campo do Cruzeiro (Ituiutaba)",
    aliases: ["campo do cruzeiro"],
    cidade: "Ituiutaba",
    regiao: "Minas Gerais",
    lat: -18.9694,
    lng: -49.4642,
    fonte: "manual/aproximado (cidade de Ituiutaba)",
  },
  {
    nome: "Estádio Deodoro Campolina",
    aliases: ["deodoro campolina"],
    cidade: "Esmeraldas",
    regiao: "Minas Gerais",
    lat: -19.7614,
    lng: -44.3125,
    fonte: "manual/aproximado (cidade de Esmeraldas)",
  },
  {
    nome: "CSU Rio Acima",
    aliases: ["csu rio acima", "csu -rio acima"],
    cidade: "Rio Acima",
    regiao: "Minas Gerais",
    lat: -20.0736,
    lng: -43.7867,
    fonte: "manual/aproximado (cidade de Rio Acima)",
  },
  {
    nome: "Estádio José Porfírio de Oliveira",
    aliases: ["jose porfirio de oliveira"],
    cidade: "Pará de Minas",
    regiao: "Minas Gerais",
    lat: -19.8611,
    lng: -44.6089,
    fonte: "manual/aproximado (cidade de Pará de Minas)",
  },
  {
    nome: "Estádio Louís Ensch (João Monlevade)",
    aliases: ["estadio louis ensch joao monlevade"],
    cidade: "João Monlevade",
    regiao: "Minas Gerais",
    lat: -19.8100,
    lng: -43.1706,
    fonte: "manual/aproximado (cidade de João Monlevade)",
  },
  {
    nome: "Estádio Emílio de Vasconcelos Costa",
    aliases: ["emilio de vasconcelos costa"],
    cidade: "Sete Lagoas",
    regiao: "Minas Gerais",
    lat: -19.4658,
    lng: -44.2467,
    fonte: "manual/aproximado (cidade de Sete Lagoas)",
  },
  {
    nome: "Estádio Municipal José Vicente Moreira",
    aliases: ["jose vicente moreira"],
    cidade: "Mateus Leme",
    regiao: "Minas Gerais",
    lat: -19.9819,
    lng: -44.4300,
    fonte: "manual/aproximado (cidade de Mateus Leme)",
  },
  {
    nome: "Arena Mineral do Brasil",
    aliases: ["arena mineral do brasil"],
    cidade: "Brumadinho",
    regiao: "Minas Gerais",
    lat: -20.1436,
    lng: -44.2011,
    fonte: "manual/aproximado (cidade de Brumadinho)",
  },
  {
    nome: "Arena Colorado",
    aliases: ["arena colorado"],
    cidade: "Ibirité",
    regiao: "Minas Gerais",
    lat: -20.0233,
    lng: -44.0578,
    fonte: "manual/aproximado (cidade de Ibirité)",
  },
  {
    nome: "Campo do Alvorada (São José da Lapa)",
    aliases: ["campo do alvorada sao jose da lapa"],
    cidade: "São José da Lapa",
    regiao: "Minas Gerais",
    lat: -19.6564,
    lng: -43.9789,
    fonte: "manual/aproximado (cidade de São José da Lapa)",
  },
  {
    nome: "Estádio Miguel Arcanjo dos Campos (Miguelão)",
    aliases: ["miguel arcanjo dos campos", "miguelao"],
    cidade: "Abaeté",
    regiao: "Minas Gerais",
    lat: -19.1547,
    lng: -45.4453,
    fonte: "manual/aproximado (cidade de Abaeté)",
  },
  {
    nome: "Estádio Dr. Lindolfo Gonçalves Martins",
    aliases: ["lindolfo goncalves martins"],
    cidade: "Belmiro Braga",
    regiao: "Minas Gerais",
    lat: -21.6497,
    lng: -43.3489,
    fonte: "manual/aproximado (cidade de Belmiro Braga)",
  },
  {
    nome: "Estádio Prefeito Genival Alves Ramalho (Campo da Barra)",
    aliases: ["genival alves ramalho", "campo da barra"],
    cidade: "Ouro Preto",
    regiao: "Minas Gerais",
    lat: -20.3856,
    lng: -43.5039,
    fonte: "manual/aproximado (cidade de Ouro Preto)",
  },
  {
    nome: "Estádio José Nunes de Sá",
    aliases: ["jose nunes de sa"],
    cidade: "Itabira",
    regiao: "Minas Gerais",
    lat: -19.6178,
    lng: -43.2258,
    fonte: "manual/aproximado (cidade de Itabira)",
  },
  {
    nome: "Estádio José Mammoud Abbas (Mamudão)",
    aliases: ["jose mammoud abbas", "mamudao"],
    cidade: "Governador Valadares",
    regiao: "Minas Gerais",
    lat: -18.8511,
    lng: -41.9494,
    fonte: "manual/aproximado (cidade de Governador Valadares)",
  },
  {
    nome: "Estádio Bernardo Rubinger de Queiroz",
    aliases: ["bernardo rubinger de queiroz"],
    cidade: "Patos de Minas",
    regiao: "Minas Gerais",
    lat: -18.5789,
    lng: -46.5183,
    fonte: "manual/aproximado (cidade de Patos de Minas)",
  },
  {
    nome: "Arena Nova Pampulha",
    aliases: ["arena nova pampulha"],
    cidade: "Vespasiano",
    regiao: "Minas Gerais",
    lat: -19.6922,
    lng: -43.9236,
    fonte: "manual/aproximado (cidade de Vespasiano)",
  },
  {
    nome: "Estádio Soares de Azevedo",
    aliases: ["soares de azevedo"],
    cidade: "Muriaé",
    regiao: "Minas Gerais",
    lat: -21.1306,
    lng: -42.3664,
    fonte: "manual/aproximado (cidade de Muriaé)",
  },
  {
    nome: "Estádio Joseph Lambert",
    aliases: ["joseph lambert"],
    cidade: "Visconde do Rio Branco",
    regiao: "Minas Gerais",
    lat: -21.0031,
    lng: -42.8378,
    fonte: "manual/aproximado (cidade de Visconde do Rio Branco)",
  },
  {
    nome: "Estádio Flausino Moreira da Silva",
    aliases: ["flausino moreira da silva"],
    cidade: "Raposos",
    regiao: "Minas Gerais",
    lat: -19.9683,
    lng: -43.8047,
    fonte: "manual/aproximado (cidade de Raposos)",
  },
  {
    nome: "Arena do Jacaré (Joaquim Henrique Nogueira)",
    aliases: ["joaquim henrique nogueira", "arena do jacare"],
    cidade: "Sete Lagoas",
    regiao: "Minas Gerais",
    lat: -19.4658,
    lng: -44.2467,
    fonte: "manual/aproximado (cidade de Sete Lagoas)",
  },
  {
    nome: "Estádio Ilvo Marani",
    aliases: ["ilvo marani"],
    cidade: "Vespasiano",
    regiao: "Minas Gerais",
    lat: -19.6922,
    lng: -43.9236,
    fonte: "manual/aproximado (cidade de Vespasiano)",
  },
  {
    nome: "Estádio Olavo Bilac de Resende",
    aliases: ["olavo bilac de resende"],
    cidade: "São Gotardo",
    regiao: "Minas Gerais",
    lat: -19.3128,
    lng: -46.0464,
    fonte: "manual/aproximado (cidade de São Gotardo)",
  },
  {
    nome: "Estádio Dr. Ronaldo Junqueira (Ronaldão)",
    aliases: ["ronaldo junqueira", "ronaldao"],
    cidade: "Poços de Caldas",
    regiao: "Minas Gerais",
    lat: -21.7878,
    lng: -46.5619,
    fonte: "manual/aproximado (cidade de Poços de Caldas)",
  },
  {
    nome: "Arena SICOOB Divicred",
    aliases: ["arena sicoob divicred"],
    cidade: "Divinópolis",
    regiao: "Minas Gerais",
    lat: -20.1389,
    lng: -44.8836,
    fonte: "manual/aproximado (cidade de Divinópolis)",
  },
  {
    nome: "Estádio Israel Pinheiro",
    aliases: ["israel pinheiro"],
    cidade: "Itabira",
    regiao: "Minas Gerais",
    lat: -19.6178,
    lng: -43.2258,
    fonte: "manual/aproximado (cidade de Itabira)",
  },
  {
    nome: "Cidade do Galo",
    aliases: ["cidade do galo"],
    cidade: "Vespasiano",
    regiao: "Minas Gerais",
    lat: -19.6922,
    lng: -43.9236,
    fonte: "manual/aproximado (CT do Atlético-MG, Vespasiano)",
  },
  {
    nome: "Estádio Dr. Adilson Machado de Farias",
    aliases: ["adilson machado de farias"],
    cidade: "Itabirinha",
    regiao: "Minas Gerais",
    lat: -18.6047,
    lng: -41.5811,
    fonte: "manual/aproximado (cidade de Itabirinha)",
  },
  {
    nome: "Arena URBSAN",
    aliases: ["arena urbsan"],
    cidade: "Betim",
    regiao: "Minas Gerais",
    lat: -19.9678,
    lng: -44.1983,
    fonte: "manual/aproximado (cidade de Betim)",
  },
  {
    nome: "Complexo do Boston City I",
    aliases: ["boston city i", "complexo do boston city"],
    cidade: "Manhuaçu",
    regiao: "Minas Gerais",
    lat: -20.2586,
    lng: -42.0281,
    fonte: "manual/aproximado (cidade de Manhuaçu)",
  },
  {
    nome: "Complexo Esportivo Bonfim",
    aliases: ["complexo esportivo bonfim"],
    cidade: "São João Del Rei",
    regiao: "Minas Gerais",
    lat: -21.1356,
    lng: -44.2617,
    fonte: "manual/aproximado (cidade de São João Del Rei)",
  },
  {
    nome: "CT Ninho do Periquito",
    aliases: ["ninho do periquito"],
    cidade: "Uberlândia",
    regiao: "Minas Gerais",
    lat: -18.9186,
    lng: -48.2772,
    fonte: "manual/aproximado (cidade de Uberlândia)",
  },
  {
    nome: "Estádio Lanari Júnior",
    aliases: ["lanari junior"],
    cidade: "Ipatinga",
    regiao: "Minas Gerais",
    lat: -19.4683,
    lng: -42.5367,
    fonte: "manual/aproximado (cidade de Ipatinga)",
  },
  {
    nome: "Campo do Botafogo (Matozinhos)",
    aliases: ["campo do botafogo matozinhos"],
    cidade: "Matozinhos",
    regiao: "Minas Gerais",
    lat: -19.5578,
    lng: -44.1147,
    fonte: "manual/aproximado (cidade de Matozinhos)",
  },
  {
    nome: "CT Athletic (São João Del Rei)",
    aliases: ["ct athletic"],
    cidade: "São João Del Rei",
    regiao: "Minas Gerais",
    lat: -21.1356,
    lng: -44.2617,
    fonte: "manual/aproximado (cidade de São João Del Rei)",
  },
  {
    nome: "Estádio Didi Gouveia",
    aliases: ["didi gouveia"],
    cidade: "São Joaquim de Bicas",
    regiao: "Minas Gerais",
    lat: -20.0392,
    lng: -44.3078,
    fonte: "manual/aproximado (cidade de São Joaquim de Bicas)",
  },
  {
    nome: "Estádio Cassimiro de Abreu",
    aliases: ["cassimiro de abreu"],
    cidade: "Montes Claros",
    regiao: "Minas Gerais",
    lat: -16.7350,
    lng: -43.8617,
    fonte: "manual/aproximado (cidade de Montes Claros)",
  },
  {
    nome: "Estádio Fausto Alvim",
    aliases: ["fausto alvim"],
    cidade: "Araxá",
    regiao: "Minas Gerais",
    lat: -19.5928,
    lng: -46.9408,
    fonte: "manual/aproximado (cidade de Araxá)",
  },

  /* ===================================================================
     Rio Grande do Sul — Gauchão / Copa FGF / Recopa (adicionados na
     auditoria de estádios FGF). Coordenadas em nível de cidade
     (aproximado), mesma convenção do resto do arquivo.
     =================================================================== */
  {
    nome: "Estádio Eucaliptos",
    aliases: ["eucaliptos"],
    cidade: "Santa Cruz do Sul",
    regiao: "Rio Grande do Sul",
    lat: -29.7175,
    lng: -52.4258,
    fonte: "manual/aproximado (cidade de Santa Cruz do Sul — mandante Avenida)",
  },
  {
    nome: "Estádio Estrela D'Alva",
    aliases: ["estrela d'alva", "estrela dalva"],
    cidade: "Bagé",
    regiao: "Rio Grande do Sul",
    lat: -31.3311,
    lng: -54.1069,
    fonte: "manual/aproximado (cidade de Bagé — mandante Guarany)",
  },
  {
    nome: "Estádio Francisco Novelletto Neto",
    aliases: ["francisco novelletto", "francisco novelletto neto"],
    cidade: "Porto Alegre",
    regiao: "Rio Grande do Sul",
    lat: -30.0225,
    lng: -51.2211,
    fonte: "manual/aproximado (cidade de Porto Alegre — mandante Monsoon/Gramadense)",
  },
  {
    nome: "Estádio 19 de Outubro",
    aliases: ["19 de outubro"],
    cidade: "Ijuí",
    regiao: "Rio Grande do Sul",
    lat: -28.3900,
    lng: -53.9150,
    fonte: "manual/aproximado (cidade de Ijuí — mandante São Luiz)",
  },
  {
    nome: "Estádio Colosso da Lagoa",
    aliases: ["colosso da lagoa"],
    cidade: "Erechim",
    regiao: "Rio Grande do Sul",
    lat: -27.6350,
    lng: -52.2739,
    fonte: "manual/aproximado (cidade de Erechim — mandante Ypiranga)",
  },
  {
    nome: "Estádio do Vale",
    aliases: ["estádio do vale", "estadio do vale"],
    cidade: "Novo Hamburgo",
    regiao: "Rio Grande do Sul",
    lat: -29.6783,
    lng: -51.1300,
    fonte: "manual/aproximado (cidade de Novo Hamburgo — mandante Novo Hamburgo)",
  },
  {
    nome: "Estádio Bento Freitas",
    aliases: ["bento freitas"],
    cidade: "Pelotas",
    regiao: "Rio Grande do Sul",
    lat: -31.7654,
    lng: -52.3376,
    fonte: "manual/aproximado (cidade de Pelotas — mandante Brasil-Pel)",
  },

  /* ===================================================================
     Estádios de CBF (Série B/C/D, Copa do Brasil) faltantes, adicionados
     na auditoria de coordenadas do dataset real.
     =================================================================== */
  {
    nome: "Estádio Antônio Accioly",
    aliases: ["antonio accioly", "antônio accioly"],
    cidade: "Goiânia",
    regiao: "Goiás",
    lat: -16.6799,
    lng: -49.2550,
    fonte: "manual/aproximado (cidade de Goiânia — mandante Vila Nova)",
  },
  {
    nome: "Arena Barra",
    aliases: ["arena barra"],
    cidade: "Barra Velha",
    regiao: "Santa Catarina",
    lat: -26.4886,
    lng: -48.6844,
    fonte: "manual/aproximado (cidade de Barra Velha — mandante Barra FC)",
  },
  {
    nome: "Estádio Major Levy Sobrinho",
    aliases: ["major levi", "major levy"],
    cidade: "Limeira",
    regiao: "São Paulo",
    lat: -22.5646,
    lng: -47.4017,
    fonte: "manual/aproximado (cidade de Limeira — mandante Inter de Limeira)",
  },
  {
    nome: "Estádio Novelli Júnior",
    aliases: ["novelli", "novelli junior", "novelli júnior"],
    cidade: "Itu",
    regiao: "São Paulo",
    lat: -23.2634,
    lng: -47.2992,
    fonte: "manual/aproximado (cidade de Itu — mandante Ituano)",
  },
  {
    nome: "Estádio Ismael Benigno",
    aliases: ["ismael benigno"],
    cidade: "Manaus",
    regiao: "Amazonas",
    lat: -3.1190,
    lng: -60.0217,
    fonte: "manual/aproximado (cidade de Manaus)",
  },
  {
    nome: "Estádio Coaracy da Mata Fonseca",
    aliases: ["coaracy fonseca", "coaracy da mata fonseca"],
    cidade: "Arapiraca",
    regiao: "Alagoas",
    lat: -9.7519,
    lng: -36.6611,
    fonte: "manual/aproximado (cidade de Arapiraca — mandante ASA)",
  },
  {
    nome: "Estádio Barão de Serra Negra",
    aliases: ["barao da serra", "barão da serra", "barao de serra negra", "barão de serra negra"],
    cidade: "Piracicaba",
    regiao: "São Paulo",
    lat: -22.7253,
    lng: -47.6492,
    fonte: "manual/aproximado (cidade de Piracicaba — mandante XV de Piracicaba)",
  },
  {
    nome: "Estádio Jonas Duarte",
    aliases: ["jonas duarte"],
    cidade: "Anápolis",
    regiao: "Goiás",
    lat: -16.3285,
    lng: -48.9534,
    fonte: "manual/aproximado (cidade de Anápolis)",
  },
  {
    nome: "Estádio Etelvino Mendonça",
    aliases: ["etelvino", "etelvino mendonca", "etelvino mendonça"],
    cidade: "Itabaiana",
    regiao: "Sergipe",
    lat: -10.6853,
    lng: -37.4222,
    fonte: "manual/aproximado (cidade de Itabaiana — mandante Olímpico de Itabaiana)",
  },
  {
    nome: "Estádio Municipal Carlos Zamith",
    aliases: ["carlos zamith"],
    cidade: "Manaus",
    regiao: "Amazonas",
    lat: -3.1190,
    lng: -60.0217,
    fonte: "manual/aproximado (cidade de Manaus)",
  },
];
