/*
  Estadios/sedes dos clubes filiados a FERJ (Rio de Janeiro), obtidos via
  scrap_fferj_estadios.py a partir de servicos.fferj.com.br/ClubesLigas.

  window.ESTADIOS_FERJ_RJ: lista de estadios/sedes com coordenadas.
  window.ESTADIO_MANDANTE_PADRAO_FFERJ: nome do clube (normalizado) -> objeto
  de estadio/sede correspondente, usado como fallback em enrichGames() quando
  o card de um jogo da FFERJ nao informa o nome do estadio.
*/

window.ESTADIOS_FERJ_RJ = [
  {
    nome: "PROLETÁRIO GUILHERME DA SILVEIRA FILHO (MOÇA BONITA)",
    aliases: ["proletario guilherme da silveira filho moca bonita"],
    clube: "BANGU A.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8738053,
    lng: -43.4681413,
    fonte_endereco: "localizacao",
  },
  {
    nome: "JORNALISTA MÁRIO FILHO (MARACANÃ)",
    aliases: ["jornalista mario filho maracana"],
    clube: "C.R FLAMENGO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0136383,
    lng: -44.3302121,
    fonte_endereco: "localizacao",
  },
  {
    nome: "JORNALISTA MÁRIO FILHO (MARACANÃ)",
    aliases: ["jornalista mario filho maracana"],
    clube: "FLUMINENSE F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0136383,
    lng: -44.3302121,
    fonte_endereco: "localizacao",
  },
  {
    nome: "ANICETO MOSCOSO (E. DO MADUREIRA)",
    aliases: ["aniceto moscoso e do madureira"],
    clube: "MADUREIRA E.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8696968,
    lng: -43.337276,
    fonte_endereco: "localizacao",
  },
  {
    nome: "JÂNIO DE MORAES (LARANJÃO)",
    aliases: ["janio de moraes laranjao"],
    clube: "NOVA IGUAÇU S.A.F",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7554095,
    lng: -43.4547277,
    fonte_endereco: "localizacao",
  },
  {
    nome: "LOURIVAL GOMES DE ALMEIDA",
    aliases: ["lourival gomes de almeida"],
    clube: "SAMPAIO CORRÊA F.E",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8541197,
    lng: -42.5811299,
    fonte_endereco: "localizacao",
  },
  {
    nome: "EXPEDICIONÁRIO",
    aliases: ["expedicionario"],
    clube: "A.E INDEPENDENTE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.3817895,
    lng: -41.7786228,
    fonte_endereco: "localizacao",
  },
  {
    nome: "MUNICIPAL JAIR TOSCANO DE BRITO",
    aliases: ["municipal jair toscano de brito"],
    clube: "ANGRA DOS REIS E.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0008204,
    lng: -44.3056589,
    fonte_endereco: "localizacao",
  },
  {
    nome: "0",
    aliases: ["0"],
    clube: "BARCELONA E.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9142169,
    lng: -43.3656375,
    fonte_endereco: "sede",
  },
  {
    nome: "ANTONIO CORREA",
    aliases: ["antonio correa"],
    clube: "BRESCIA BARRA CLUBE LTDA ME",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9504452,
    lng: -43.1806936,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do CAACBRASIL F.C",
    aliases: ["sede do caacbrasil f c"],
    clube: "CAACBRASIL F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9110733,
    lng: -43.1851565,
    fonte_endereco: "sede",
  },
  {
    nome: "ANGELO DE CARVALHO",
    aliases: ["angelo de carvalho"],
    clube: "CAMPOS ATLÉTICO ASSOCIAÇÃO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.7483169,
    lng: -41.3428751,
    fonte_endereco: "localizacao",
  },
  {
    nome: "ANTONIO FERREIRA DE MEDEIROS",
    aliases: ["antonio ferreira de medeiros"],
    clube: "CARDOSO MOREIRA F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9231185,
    lng: -43.1879785,
    fonte_endereco: "localizacao",
  },
  {
    nome: "UBIRAJARA DE ALMEIDA REIS",
    aliases: ["ubirajara de almeida reis"],
    clube: "CASIMIRO DE ABREU E.C (INATIVO)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9013926,
    lng: -42.9387282,
    fonte_endereco: "localizacao",
  },
  {
    nome: "JOÃO FRANCISCO DOS SANTOS",
    aliases: ["joao francisco dos santos"],
    clube: "CERES F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8742683,
    lng: -43.4637134,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Sede do DUQUE CAXIENSE F.C",
    aliases: ["sede do duque caxiense f c"],
    clube: "DUQUE CAXIENSE F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7880237,
    lng: -43.3268514,
    fonte_endereco: "sede",
  },
  {
    nome: "DE LOS LÁRIOS",
    aliases: ["de los larios"],
    clube: "E.C TIGRES DO BRASIL",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5942868,
    lng: -43.3147454,
    fonte_endereco: "localizacao",
  },
  {
    nome: "FLÁVIO TEIXEIRA DOS SANTOS",
    aliases: ["flavio teixeira dos santos"],
    clube: "EC RIO SAO PAULO (LICENÇA DA TEMPORADA 2025 - RDP Nº 007/2025)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8825786,
    lng: -43.3538796,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "IMPÉRIO SERRANO ESPORTE CLUBE (INATIVO)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.874144,
    lng: -43.3365901,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ITABORAI PROFUTE FC",
    aliases: ["sede do itaborai profute fc"],
    clube: "ITABORAI PROFUTE FC",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7479242,
    lng: -42.8631015,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do JUVENTUS FC.",
    aliases: ["sede do juventus fc"],
    clube: "JUVENTUS FC.",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.3748692,
    lng: -41.7786903,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do MAGEENSE FUTEBOL CLUBE",
    aliases: ["sede do mageense futebol clube"],
    clube: "MAGEENSE FUTEBOL CLUBE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.6567304,
    lng: -43.0403092,
    fonte_endereco: "sede",
  },
  {
    nome: "NIELSEN LOUSADA (LOUSADÃO)",
    aliases: ["nielsen lousada lousadao"],
    clube: "MESQUITA F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7854714,
    lng: -43.4215329,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "PARAIBA DO SUL FC (INATIVO)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.1832499,
    lng: -43.287341,
    fonte_endereco: "sede",
  },
  {
    nome: "JÚLIO KENGEN",
    aliases: ["julio kengen"],
    clube: "QUEIMADOS F.C (INATIVO)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7176376,
    lng: -43.5525698,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Sede do RIO BARRA FUTEBOL CLUBE LTDA",
    aliases: ["sede do rio barra futebol clube ltda"],
    clube: "RIO BARRA FUTEBOL CLUBE LTDA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.476117,
    lng: -44.4505672,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do RIOSTRENSE E.C LTDA",
    aliases: ["sede do riostrense e c ltda"],
    clube: "RIOSTRENSE E.C LTDA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.6509732,
    lng: -42.3970251,
    fonte_endereco: "sede",
  },
  {
    nome: "MUNICIPAL DE BÚZIOS",
    aliases: ["municipal de buzios"],
    clube: "S. E. DE BUZIOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7584928,
    lng: -41.887136,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Sede do UNIÃO CENTRAL F.C",
    aliases: ["sede do uniao central f c"],
    clube: "UNIÃO CENTRAL F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7890587,
    lng: -43.165612,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA ALDEENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8395924,
    lng: -42.1022316,
    fonte_endereco: "sede",
  },
  {
    nome: "MUNICIPAL JAIR TOSCANO DE BRITO",
    aliases: ["municipal jair toscano de brito"],
    clube: "LIGA ANGRENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0008204,
    lng: -44.3056589,
    fonte_endereco: "localizacao",
  },
  {
    nome: "ESTÁDIO MUN. JOSÉ GONÇALVES BRANDÃO FILHO",
    aliases: ["estadio mun jose goncalves brandao filho"],
    clube: "LIGA APERIBEENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.6216939,
    lng: -42.1019142,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA BARRAMANSENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5297511,
    lng: -44.1465351,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA BONJESUENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.1284395,
    lng: -41.6685337,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA CAMBUCIENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.4141005,
    lng: -41.8112943,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA CAMPISTA DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.7511117,
    lng: -41.3361912,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA CORDEIRENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.0339757,
    lng: -42.3758959,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DE DESPORTOS DE BELFORD ROXO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7436522,
    lng: -43.3987544,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DE DESPORTOS DE QUEIMADOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7236724,
    lng: -43.5614778,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DE DESPORTOS DE RIO DAS OSTRAS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5195001,
    lng: -41.9576995,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DE DESPORTOS DE VOLTA REDONDA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5256891,
    lng: -44.0926272,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DE DESPORTOS SILVAJARDINENSE (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.6507422,
    lng: -42.3898262,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE ARRAIAL DO CABO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9678639,
    lng: -42.0245138,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE ITABORAI",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7453201,
    lng: -42.8589634,
    fonte_endereco: "sede",
  },
  {
    nome: "HERMANO VICTOR MEGUELLE",
    aliases: ["hermano victor meguelle"],
    clube: "LIGA DESPORTIVA DE ITAGUAI",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8727784,
    lng: -43.7925121,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE ITALVA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.4212046,
    lng: -41.6870274,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE MACUCO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.9872695,
    lng: -42.2544882,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE MIRACEMA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.4004836,
    lng: -42.1812263,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE PINHEIRAL (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5226303,
    lng: -44.0007104,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE SAPUCAIA (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.9955309,
    lng: -42.9146139,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE SEROPEDICA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7460551,
    lng: -43.7002871,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE SUMIDOURO (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.0512125,
    lng: -42.6779274,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DE TRES RIOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.1151781,
    lng: -43.2068677,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA DO CARMO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.9394106,
    lng: -42.6057583,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA DESPORTIVA UBAENSE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.3593294,
    lng: -41.9385893,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA GONCALENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8270826,
    lng: -43.0548893,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA IGUABENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8232014,
    lng: -42.0613149,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA ITAOCARENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.6693056,
    lng: -42.0805597,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA ITAPERUNENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.195882,
    lng: -41.9081137,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA MACABUENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.0838091,
    lng: -41.8717975,
    fonte_endereco: "sede",
  },
  {
    nome: "EXPEDICIONÁRIO",
    aliases: ["expedicionario"],
    clube: "LIGA MACAENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.3817895,
    lng: -41.7786228,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA MADALENENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -21.9560451,
    lng: -42.0087006,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA MESQUITENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7827657,
    lng: -43.4301988,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA NILOPOLITANA DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8099931,
    lng: -43.4198432,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA NOVA FRIBURGO DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.2803451,
    lng: -42.5328443,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA PETROPOLITANA DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.510597,
    lng: -43.1782413,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA RIOBONITENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7116487,
    lng: -42.6213649,
    fonte_endereco: "sede",
  },
  {
    nome: "MUNICIPAL CID MAGALHÃES SILVA",
    aliases: ["municipal cid magalhaes silva"],
    clube: "LIGA RIOCLARENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8177328,
    lng: -44.1876244,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA RIOFLORENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.1671355,
    lng: -43.5859041,
    fonte_endereco: "sede",
  },
  {
    nome: "MUNICIPAL MANOEL JOSÉ VIANA DE SÁ",
    aliases: ["municipal manoel jose viana de sa"],
    clube: "LIGA SANJOANENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.2800004,
    lng: -42.5325303,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA SAQUAREMENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.901398,
    lng: -42.4746103,
    fonte_endereco: "sede",
  },
  {
    nome: "PITUCÃO",
    aliases: ["pitucao"],
    clube: "LIGA TERESOPOLITANA DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.3979768,
    lng: -42.9836479,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA VALENCIANA DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.247427,
    lng: -43.7073408,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA VARRE-SAIENSE DE DESPORTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -20.9276831,
    lng: -41.8703448,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "LIGA VASSOURENSE DE DESPORTOS (INATIVA)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.3970868,
    lng: -43.6468351,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do A.A OLIVEIRA - FUTUROS TALENTOS",
    aliases: ["sede do a a oliveira futuros talentos"],
    clube: "A.A OLIVEIRA - FUTUROS TALENTOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9149147,
    lng: -43.5839361,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do A.E PISCINÃO DE RAMOS",
    aliases: ["sede do a e piscinao de ramos"],
    clube: "A.E PISCINÃO DE RAMOS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7972324,
    lng: -43.2903938,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ADELPHI FUTEBOL CLUBE",
    aliases: ["sede do adelphi futebol clube"],
    clube: "ADELPHI FUTEBOL CLUBE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9243231,
    lng: -43.5471713,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do AES CULTURAL MAMAO",
    aliases: ["sede do aes cultural mamao"],
    clube: "AES CULTURAL MAMAO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8878061,
    lng: -43.6118612,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ASSOCIAÇÃO ATLÉTICA BELA VISTA",
    aliases: ["sede do associacao atletica bela vista"],
    clube: "ASSOCIAÇÃO ATLÉTICA BELA VISTA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8894649,
    lng: -43.5763408,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ASSOCIAÇÃO OBSERVATÓRIO SOCIAL",
    aliases: ["sede do associacao observatorio social"],
    clube: "ASSOCIAÇÃO OBSERVATÓRIO SOCIAL",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0028275,
    lng: -43.3211741,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ASSOCIAÇÃO PROJETO ORIENTAÇÃO E DESENVOLVIMENTO DE ATIVIDADES ESPORTIVAS",
    aliases: ["sede do associacao projeto orientacao e desenvolvimento de atividades esportivas"],
    clube: "ASSOCIAÇÃO PROJETO ORIENTAÇÃO E DESENVOLVIMENTO DE ATIVIDADES ESPORTIVAS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8668115,
    lng: -43.4243934,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ASSOCIACAO QG DA CIDADANIA",
    aliases: ["sede do associacao qg da cidadania"],
    clube: "ASSOCIACAO QG DA CIDADANIA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8265495,
    lng: -43.3658558,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do C C ESPORTIVO DE JACAREPAGUA (INATIVO)",
    aliases: ["sede do c c esportivo de jacarepagua inativo"],
    clube: "C C ESPORTIVO DE JACAREPAGUA (INATIVO)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9135893,
    lng: -43.3575849,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do C E SOCIAL E CULTURAL HEIPS",
    aliases: ["sede do c e social e cultural heips"],
    clube: "C E SOCIAL E CULTURAL HEIPS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9849615,
    lng: -43.5661349,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do CECS EL SHADDAI",
    aliases: ["sede do cecs el shaddai"],
    clube: "CECS EL SHADDAI",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.945398,
    lng: -43.3920967,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do CEE VILA DO JOÃO",
    aliases: ["sede do cee vila do joao"],
    clube: "CEE VILA DO JOÃO",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8869783,
    lng: -43.5917594,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do CENTRO ESPORTIVO E CULTURAL ATLÉTICO JUVENTUDE",
    aliases: ["sede do centro esportivo e cultural atletico juventude"],
    clube: "CENTRO ESPORTIVO E CULTURAL ATLÉTICO JUVENTUDE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.4067751,
    lng: -41.803043,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do CENTRO ESPORTIVO GARDÊNIA AZUL",
    aliases: ["sede do centro esportivo gardenia azul"],
    clube: "CENTRO ESPORTIVO GARDÊNIA AZUL",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8425739,
    lng: -43.3412953,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do COLONIA A.C",
    aliases: ["sede do colonia a c"],
    clube: "COLONIA A.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8871131,
    lng: -43.4819256,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do CRUZEIRO F.C",
    aliases: ["sede do cruzeiro f c"],
    clube: "CRUZEIRO F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8704194,
    lng: -43.43585,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do ESPORTE CLUBE ROGI-MIRIM",
    aliases: ["sede do esporte clube rogi mirim"],
    clube: "ESPORTE CLUBE ROGI-MIRIM",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9407469,
    lng: -43.67094,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do GREMINHO FUTEBOL CLUBE",
    aliases: ["sede do greminho futebol clube"],
    clube: "GREMINHO FUTEBOL CLUBE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9072897,
    lng: -43.6132898,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do IMPERIAL F.C PACIÊNCIA",
    aliases: ["sede do imperial f c paciencia"],
    clube: "IMPERIAL F.C PACIÊNCIA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0086601,
    lng: -43.4430375,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do INSTITUTO SOCIAL DE ESP LAZER SAÚDE INCLUSÃO SOCIAL E MEIO AMB. (NOME FANTASIA: INSTITUTO PLANEJAR)",
    aliases: ["sede do instituto social de esp lazer saude inclusao social e meio amb nome fantasia instituto planejar"],
    clube: "INSTITUTO SOCIAL DE ESP LAZER SAÚDE INCLUSÃO SOCIAL E MEIO AMB. (NOME FANTASIA: INSTITUTO PLANEJAR)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9115221,
    lng: -43.1748116,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do KOSMOS A.S (LICENÇA DA TEMPORADA 2025 - RDP Nº 005/2025)",
    aliases: ["sede do kosmos a s licenca da temporada 2025 rdp n 005 2025"],
    clube: "KOSMOS A.S (LICENÇA DA TEMPORADA 2025 - RDP Nº 005/2025)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9080232,
    lng: -43.6148553,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do LOS ANGELES A.C.",
    aliases: ["sede do los angeles a c"],
    clube: "LOS ANGELES A.C.",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9299304,
    lng: -43.3661376,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do MUNICIPAL F.C. (PAQUETÁ)",
    aliases: ["sede do municipal f c paqueta"],
    clube: "MUNICIPAL F.C. (PAQUETÁ)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7515256,
    lng: -43.1067463,
    fonte_endereco: "sede",
  },
  {
    nome: "LEONIDAS DA SILVA",
    aliases: ["leonidas da silva"],
    clube: "BONSUCESSO F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8572404,
    lng: -43.2524224,
    fonte_endereco: "localizacao",
  },
  {
    nome: "ÍTALO DEL CIMA",
    aliases: ["italo del cima"],
    clube: "CAMPO GRANDE A.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8969832,
    lng: -43.5393732,
    fonte_endereco: "localizacao",
  },
  {
    nome: "CENTRO ESPORTIVO ROMÁRIO DE SOUZA FARIAS",
    aliases: ["centro esportivo romario de souza farias"],
    clube: "DUQUE DE CAXIAS F.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5970137,
    lng: -43.297077,
    fonte_endereco: "localizacao",
  },
  {
    nome: "JOAQUIM DE ALMEIDA FLORES",
    aliases: ["joaquim de almeida flores"],
    clube: "E.C NOVA CIDADE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.7971008,
    lng: -43.4155223,
    fonte_endereco: "localizacao",
  },
  {
    nome: "EDUARDO GUINLE",
    aliases: ["eduardo guinle"],
    clube: "FRIBURGUENSE A.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.2945957,
    lng: -42.5391936,
    fonte_endereco: "localizacao",
  },
  {
    nome: "CEFAT - CENTRO DE FORMAÇÃO DE ATLETAS DO TROPS",
    aliases: ["cefat centro de formacao de atletas do trops"],
    clube: "NITEROIENSE FUTEBOL CLUBE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8637338,
    lng: -43.0844492,
    fonte_endereco: "localizacao",
  },
  {
    nome: "FIGUEIRA DE MELO (FIGUEIRINHA)",
    aliases: ["figueira de melo figueirinha"],
    clube: "SÃO CRISTÓVÃO DE F.R",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9050512,
    lng: -43.2135629,
    fonte_endereco: "localizacao",
  },
  {
    nome: "SETE DE ABRIL",
    aliases: ["sete de abril"],
    clube: "CIG 7 DE ABRIL",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9149265,
    lng: -43.6389408,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Sede do CTA - CENTRO DE TREIN. E APERF. - SANTA CRUZ FUTEBOL CLUBE LTDA (N. FANTASIA: SANTA CRUZ FC)",
    aliases: ["sede do cta centro de trein e aperf santa cruz futebol clube ltda n fantasia santa cruz fc"],
    clube: "CTA - CENTRO DE TREIN. E APERF. - SANTA CRUZ FUTEBOL CLUBE LTDA (N. FANTASIA: SANTA CRUZ FC)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -23.0201903,
    lng: -43.4853992,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do SERRA MACAENSE FC",
    aliases: ["sede do serra macaense fc"],
    clube: "SERRA MACAENSE FC",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.3915511,
    lng: -41.775997,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do SOCIEDADE ESPORTIVA PARATY",
    aliases: ["sede do sociedade esportiva paraty"],
    clube: "SOCIEDADE ESPORTIVA PARATY",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8491392,
    lng: -43.5237368,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do UNI SOUZA FC",
    aliases: ["sede do uni souza fc"],
    clube: "UNI SOUZA FC",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8872855,
    lng: -43.2502494,
    fonte_endereco: "sede",
  },
  {
    nome: "Não Possui",
    aliases: ["nao possui"],
    clube: "ZINZANE FUTEBOL CLUBE SAF (ZINZA FC)",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9734814,
    lng: -43.3822898,
    fonte_endereco: "sede",
  },
  {
    nome: "ALAIR CORREA",
    aliases: ["alair correa"],
    clube: "A.D CABOFRIENSE",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8900655,
    lng: -42.0428408,
    fonte_endereco: "localizacao",
  },
  {
    nome: "HERMENEGILDO BARCELOS",
    aliases: ["hermenegildo barcelos"],
    clube: "AE ARARUAMA",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.5076318,
    lng: -43.1671709,
    fonte_endereco: "localizacao",
  },
  {
    nome: "MOURÃO VIEIRA FILHO ( RUA BARIRI )",
    aliases: ["mourao vieira filho rua bariri"],
    clube: "OLARIA A.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8418938,
    lng: -43.2673018,
    fonte_endereco: "localizacao",
  },
  {
    nome: "Sede do SÃO GONÇALO E.C",
    aliases: ["sede do sao goncalo e c"],
    clube: "SÃO GONÇALO E.C",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.8164741,
    lng: -43.0127848,
    fonte_endereco: "sede",
  },
  {
    nome: "Sede do VIVA RIO - PÉROLAS NEGRAS",
    aliases: ["sede do viva rio perolas negras"],
    clube: "VIVA RIO - PÉROLAS NEGRAS",
    cidade: "",
    regiao: "Rio de Janeiro",
    lat: -22.9212347,
    lng: -43.1751238,
    fonte_endereco: "sede",
  },
];

window.ESTADIO_MANDANTE_PADRAO_FFERJ = {
  "bangu a c": { nome: "PROLETÁRIO GUILHERME DA SILVEIRA FILHO (MOÇA BONITA)", cidade: "", regiao: "Rio de Janeiro", lat: -22.8738053, lng: -43.4681413 },
  "c r flamengo": { nome: "JORNALISTA MÁRIO FILHO (MARACANÃ)", cidade: "", regiao: "Rio de Janeiro", lat: -23.0136383, lng: -44.3302121 },
  "fluminense f c": { nome: "JORNALISTA MÁRIO FILHO (MARACANÃ)", cidade: "", regiao: "Rio de Janeiro", lat: -23.0136383, lng: -44.3302121 },
  "madureira e c": { nome: "ANICETO MOSCOSO (E. DO MADUREIRA)", cidade: "", regiao: "Rio de Janeiro", lat: -22.8696968, lng: -43.337276 },
  "nova iguacu s a f": { nome: "JÂNIO DE MORAES (LARANJÃO)", cidade: "", regiao: "Rio de Janeiro", lat: -22.7554095, lng: -43.4547277 },
  "sampaio correa f e": { nome: "LOURIVAL GOMES DE ALMEIDA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8541197, lng: -42.5811299 },
  "a e independente": { nome: "EXPEDICIONÁRIO", cidade: "", regiao: "Rio de Janeiro", lat: -22.3817895, lng: -41.7786228 },
  "angra dos reis e c": { nome: "MUNICIPAL JAIR TOSCANO DE BRITO", cidade: "", regiao: "Rio de Janeiro", lat: -23.0008204, lng: -44.3056589 },
  "barcelona e c": { nome: "0", cidade: "", regiao: "Rio de Janeiro", lat: -22.9142169, lng: -43.3656375 },
  "brescia barra clube ltda me": { nome: "ANTONIO CORREA", cidade: "", regiao: "Rio de Janeiro", lat: -22.9504452, lng: -43.1806936 },
  "caacbrasil f c": { nome: "Sede do CAACBRASIL F.C", cidade: "", regiao: "Rio de Janeiro", lat: -22.9110733, lng: -43.1851565 },
  "campos atletico associacao": { nome: "ANGELO DE CARVALHO", cidade: "", regiao: "Rio de Janeiro", lat: -21.7483169, lng: -41.3428751 },
  "cardoso moreira f c": { nome: "ANTONIO FERREIRA DE MEDEIROS", cidade: "", regiao: "Rio de Janeiro", lat: -22.9231185, lng: -43.1879785 },
  "casimiro de abreu e c inativo": { nome: "UBIRAJARA DE ALMEIDA REIS", cidade: "", regiao: "Rio de Janeiro", lat: -22.9013926, lng: -42.9387282 },
  "ceres f c": { nome: "JOÃO FRANCISCO DOS SANTOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.8742683, lng: -43.4637134 },
  "duque caxiense f c": { nome: "Sede do DUQUE CAXIENSE F.C", cidade: "", regiao: "Rio de Janeiro", lat: -22.7880237, lng: -43.3268514 },
  "e c tigres do brasil": { nome: "DE LOS LÁRIOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.5942868, lng: -43.3147454 },
  "ec rio sao paulo licenca da temporada 2025 rdp n 007 2025": { nome: "FLÁVIO TEIXEIRA DOS SANTOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.8825786, lng: -43.3538796 },
  "imperio serrano esporte clube inativo": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.874144, lng: -43.3365901 },
  "itaborai profute fc": { nome: "Sede do ITABORAI PROFUTE FC", cidade: "", regiao: "Rio de Janeiro", lat: -22.7479242, lng: -42.8631015 },
  "juventus fc": { nome: "Sede do JUVENTUS FC.", cidade: "", regiao: "Rio de Janeiro", lat: -22.3748692, lng: -41.7786903 },
  "mageense futebol clube": { nome: "Sede do MAGEENSE FUTEBOL CLUBE", cidade: "", regiao: "Rio de Janeiro", lat: -22.6567304, lng: -43.0403092 },
  "mesquita f c": { nome: "NIELSEN LOUSADA (LOUSADÃO)", cidade: "", regiao: "Rio de Janeiro", lat: -22.7854714, lng: -43.4215329 },
  "paraiba do sul fc inativo": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.1832499, lng: -43.287341 },
  "queimados f c inativo": { nome: "JÚLIO KENGEN", cidade: "", regiao: "Rio de Janeiro", lat: -22.7176376, lng: -43.5525698 },
  "rio barra futebol clube ltda": { nome: "Sede do RIO BARRA FUTEBOL CLUBE LTDA", cidade: "", regiao: "Rio de Janeiro", lat: -22.476117, lng: -44.4505672 },
  "riostrense e c ltda": { nome: "Sede do RIOSTRENSE E.C LTDA", cidade: "", regiao: "Rio de Janeiro", lat: -22.6509732, lng: -42.3970251 },
  "s e de buzios": { nome: "MUNICIPAL DE BÚZIOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.7584928, lng: -41.887136 },
  "uniao central f c": { nome: "Sede do UNIÃO CENTRAL F.C", cidade: "", regiao: "Rio de Janeiro", lat: -22.7890587, lng: -43.165612 },
  "liga aldeense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.8395924, lng: -42.1022316 },
  "liga angrense de desportos": { nome: "MUNICIPAL JAIR TOSCANO DE BRITO", cidade: "", regiao: "Rio de Janeiro", lat: -23.0008204, lng: -44.3056589 },
  "liga aperibeense de desportos": { nome: "ESTÁDIO MUN. JOSÉ GONÇALVES BRANDÃO FILHO", cidade: "", regiao: "Rio de Janeiro", lat: -21.6216939, lng: -42.1019142 },
  "liga barramansense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.5297511, lng: -44.1465351 },
  "liga bonjesuense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.1284395, lng: -41.6685337 },
  "liga cambuciense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.4141005, lng: -41.8112943 },
  "liga campista de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.7511117, lng: -41.3361912 },
  "liga cordeirense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.0339757, lng: -42.3758959 },
  "liga de desportos de belford roxo": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.7436522, lng: -43.3987544 },
  "liga de desportos de queimados": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.7236724, lng: -43.5614778 },
  "liga de desportos de rio das ostras": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.5195001, lng: -41.9576995 },
  "liga de desportos de volta redonda": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.5256891, lng: -44.0926272 },
  "liga de desportos silvajardinense inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.6507422, lng: -42.3898262 },
  "liga desportiva de arraial do cabo": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.9678639, lng: -42.0245138 },
  "liga desportiva de itaborai": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.7453201, lng: -42.8589634 },
  "liga desportiva de itaguai": { nome: "HERMANO VICTOR MEGUELLE", cidade: "", regiao: "Rio de Janeiro", lat: -22.8727784, lng: -43.7925121 },
  "liga desportiva de italva": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.4212046, lng: -41.6870274 },
  "liga desportiva de macuco": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.9872695, lng: -42.2544882 },
  "liga desportiva de miracema": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.4004836, lng: -42.1812263 },
  "liga desportiva de pinheiral inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.5226303, lng: -44.0007104 },
  "liga desportiva de sapucaia inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.9955309, lng: -42.9146139 },
  "liga desportiva de seropedica": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.7460551, lng: -43.7002871 },
  "liga desportiva de sumidouro inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.0512125, lng: -42.6779274 },
  "liga desportiva de tres rios inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.1151781, lng: -43.2068677 },
  "liga desportiva do carmo": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.9394106, lng: -42.6057583 },
  "liga desportiva ubaense": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.3593294, lng: -41.9385893 },
  "liga goncalense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.8270826, lng: -43.0548893 },
  "liga iguabense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.8232014, lng: -42.0613149 },
  "liga itaocarense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.6693056, lng: -42.0805597 },
  "liga itaperunense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.195882, lng: -41.9081137 },
  "liga macabuense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.0838091, lng: -41.8717975 },
  "liga macaense de desportos": { nome: "EXPEDICIONÁRIO", cidade: "", regiao: "Rio de Janeiro", lat: -22.3817895, lng: -41.7786228 },
  "liga madalenense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -21.9560451, lng: -42.0087006 },
  "liga mesquitense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.7827657, lng: -43.4301988 },
  "liga nilopolitana de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.8099931, lng: -43.4198432 },
  "liga nova friburgo de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.2803451, lng: -42.5328443 },
  "liga petropolitana de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.510597, lng: -43.1782413 },
  "liga riobonitense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.7116487, lng: -42.6213649 },
  "liga rioclarense de desportos": { nome: "MUNICIPAL CID MAGALHÃES SILVA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8177328, lng: -44.1876244 },
  "liga rioflorense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.1671355, lng: -43.5859041 },
  "liga sanjoanense de desportos": { nome: "MUNICIPAL MANOEL JOSÉ VIANA DE SÁ", cidade: "", regiao: "Rio de Janeiro", lat: -22.2800004, lng: -42.5325303 },
  "liga saquaremense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.901398, lng: -42.4746103 },
  "liga teresopolitana de desportos": { nome: "PITUCÃO", cidade: "", regiao: "Rio de Janeiro", lat: -22.3979768, lng: -42.9836479 },
  "liga valenciana de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.247427, lng: -43.7073408 },
  "liga varre saiense de desportos": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -20.9276831, lng: -41.8703448 },
  "liga vassourense de desportos inativa": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.3970868, lng: -43.6468351 },
  "a a oliveira futuros talentos": { nome: "Sede do A.A OLIVEIRA - FUTUROS TALENTOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.9149147, lng: -43.5839361 },
  "a e piscinao de ramos": { nome: "Sede do A.E PISCINÃO DE RAMOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.7972324, lng: -43.2903938 },
  "adelphi futebol clube": { nome: "Sede do ADELPHI FUTEBOL CLUBE", cidade: "", regiao: "Rio de Janeiro", lat: -22.9243231, lng: -43.5471713 },
  "aes cultural mamao": { nome: "Sede do AES CULTURAL MAMAO", cidade: "", regiao: "Rio de Janeiro", lat: -22.8878061, lng: -43.6118612 },
  "associacao atletica bela vista": { nome: "Sede do ASSOCIAÇÃO ATLÉTICA BELA VISTA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8894649, lng: -43.5763408 },
  "associacao observatorio social": { nome: "Sede do ASSOCIAÇÃO OBSERVATÓRIO SOCIAL", cidade: "", regiao: "Rio de Janeiro", lat: -23.0028275, lng: -43.3211741 },
  "associacao projeto orientacao e desenvolvimento de atividades esportivas": { nome: "Sede do ASSOCIAÇÃO PROJETO ORIENTAÇÃO E DESENVOLVIMENTO DE ATIVIDADES ESPORTIVAS", cidade: "", regiao: "Rio de Janeiro", lat: -22.8668115, lng: -43.4243934 },
  "associacao qg da cidadania": { nome: "Sede do ASSOCIACAO QG DA CIDADANIA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8265495, lng: -43.3658558 },
  "c c esportivo de jacarepagua inativo": { nome: "Sede do C C ESPORTIVO DE JACAREPAGUA (INATIVO)", cidade: "", regiao: "Rio de Janeiro", lat: -22.9135893, lng: -43.3575849 },
  "c e social e cultural heips": { nome: "Sede do C E SOCIAL E CULTURAL HEIPS", cidade: "", regiao: "Rio de Janeiro", lat: -22.9849615, lng: -43.5661349 },
  "cecs el shaddai": { nome: "Sede do CECS EL SHADDAI", cidade: "", regiao: "Rio de Janeiro", lat: -22.945398, lng: -43.3920967 },
  "cee vila do joao": { nome: "Sede do CEE VILA DO JOÃO", cidade: "", regiao: "Rio de Janeiro", lat: -22.8869783, lng: -43.5917594 },
  "centro esportivo e cultural atletico juventude": { nome: "Sede do CENTRO ESPORTIVO E CULTURAL ATLÉTICO JUVENTUDE", cidade: "", regiao: "Rio de Janeiro", lat: -22.4067751, lng: -41.803043 },
  "centro esportivo gardenia azul": { nome: "Sede do CENTRO ESPORTIVO GARDÊNIA AZUL", cidade: "", regiao: "Rio de Janeiro", lat: -22.8425739, lng: -43.3412953 },
  "colonia a c": { nome: "Sede do COLONIA A.C", cidade: "", regiao: "Rio de Janeiro", lat: -22.8871131, lng: -43.4819256 },
  "cruzeiro f c": { nome: "Sede do CRUZEIRO F.C", cidade: "", regiao: "Rio de Janeiro", lat: -22.8704194, lng: -43.43585 },
  "esporte clube rogi mirim": { nome: "Sede do ESPORTE CLUBE ROGI-MIRIM", cidade: "", regiao: "Rio de Janeiro", lat: -22.9407469, lng: -43.67094 },
  "greminho futebol clube": { nome: "Sede do GREMINHO FUTEBOL CLUBE", cidade: "", regiao: "Rio de Janeiro", lat: -22.9072897, lng: -43.6132898 },
  "imperial f c paciencia": { nome: "Sede do IMPERIAL F.C PACIÊNCIA", cidade: "", regiao: "Rio de Janeiro", lat: -23.0086601, lng: -43.4430375 },
  "instituto social de esp lazer saude inclusao social e meio amb nome fantasia instituto planejar": { nome: "Sede do INSTITUTO SOCIAL DE ESP LAZER SAÚDE INCLUSÃO SOCIAL E MEIO AMB. (NOME FANTASIA: INSTITUTO PLANEJAR)", cidade: "", regiao: "Rio de Janeiro", lat: -22.9115221, lng: -43.1748116 },
  "kosmos a s licenca da temporada 2025 rdp n 005 2025": { nome: "Sede do KOSMOS A.S (LICENÇA DA TEMPORADA 2025 - RDP Nº 005/2025)", cidade: "", regiao: "Rio de Janeiro", lat: -22.9080232, lng: -43.6148553 },
  "los angeles a c": { nome: "Sede do LOS ANGELES A.C.", cidade: "", regiao: "Rio de Janeiro", lat: -22.9299304, lng: -43.3661376 },
  "municipal f c paqueta": { nome: "Sede do MUNICIPAL F.C. (PAQUETÁ)", cidade: "", regiao: "Rio de Janeiro", lat: -22.7515256, lng: -43.1067463 },
  "bonsucesso f c": { nome: "LEONIDAS DA SILVA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8572404, lng: -43.2524224 },
  "campo grande a c": { nome: "ÍTALO DEL CIMA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8969832, lng: -43.5393732 },
  "duque de caxias f c": { nome: "CENTRO ESPORTIVO ROMÁRIO DE SOUZA FARIAS", cidade: "", regiao: "Rio de Janeiro", lat: -22.5970137, lng: -43.297077 },
  "e c nova cidade": { nome: "JOAQUIM DE ALMEIDA FLORES", cidade: "", regiao: "Rio de Janeiro", lat: -22.7971008, lng: -43.4155223 },
  "friburguense a c": { nome: "EDUARDO GUINLE", cidade: "", regiao: "Rio de Janeiro", lat: -22.2945957, lng: -42.5391936 },
  "niteroiense futebol clube": { nome: "CEFAT - CENTRO DE FORMAÇÃO DE ATLETAS DO TROPS", cidade: "", regiao: "Rio de Janeiro", lat: -22.8637338, lng: -43.0844492 },
  "sao cristovao de f r": { nome: "FIGUEIRA DE MELO (FIGUEIRINHA)", cidade: "", regiao: "Rio de Janeiro", lat: -22.9050512, lng: -43.2135629 },
  "cig 7 de abril": { nome: "SETE DE ABRIL", cidade: "", regiao: "Rio de Janeiro", lat: -22.9149265, lng: -43.6389408 },
  "cta centro de trein e aperf santa cruz futebol clube ltda n fantasia santa cruz fc": { nome: "Sede do CTA - CENTRO DE TREIN. E APERF. - SANTA CRUZ FUTEBOL CLUBE LTDA (N. FANTASIA: SANTA CRUZ FC)", cidade: "", regiao: "Rio de Janeiro", lat: -23.0201903, lng: -43.4853992 },
  "serra macaense fc": { nome: "Sede do SERRA MACAENSE FC", cidade: "", regiao: "Rio de Janeiro", lat: -22.3915511, lng: -41.775997 },
  "sociedade esportiva paraty": { nome: "Sede do SOCIEDADE ESPORTIVA PARATY", cidade: "", regiao: "Rio de Janeiro", lat: -22.8491392, lng: -43.5237368 },
  "uni souza fc": { nome: "Sede do UNI SOUZA FC", cidade: "", regiao: "Rio de Janeiro", lat: -22.8872855, lng: -43.2502494 },
  "zinzane futebol clube saf zinza fc": { nome: "Não Possui", cidade: "", regiao: "Rio de Janeiro", lat: -22.9734814, lng: -43.3822898 },
  "a d cabofriense": { nome: "ALAIR CORREA", cidade: "", regiao: "Rio de Janeiro", lat: -22.8900655, lng: -42.0428408 },
  "ae araruama": { nome: "HERMENEGILDO BARCELOS", cidade: "", regiao: "Rio de Janeiro", lat: -22.5076318, lng: -43.1671709 },
  "olaria a c": { nome: "MOURÃO VIEIRA FILHO ( RUA BARIRI )", cidade: "", regiao: "Rio de Janeiro", lat: -22.8418938, lng: -43.2673018 },
  "sao goncalo e c": { nome: "Sede do SÃO GONÇALO E.C", cidade: "", regiao: "Rio de Janeiro", lat: -22.8164741, lng: -43.0127848 },
  "viva rio perolas negras": { nome: "Sede do VIVA RIO - PÉROLAS NEGRAS", cidade: "", regiao: "Rio de Janeiro", lat: -22.9212347, lng: -43.1751238 },
};