/*
  Base melhorada de estádios do futebol chileno.

  Importante:
  - O site campeonatochileno.cl expõe nomes/páginas de estádio, mas não latitude/longitude no HTML público.
  - Este arquivo cruza os nomes extraídos do site com coordenadas aproximadas.
  - Quando aparecer um estádio novo, adicione um objeto nesta lista ou rode o scraper de estádios para gerar pendências.

  Campos:
  - nome: nome principal
  - aliases: variações do nome que podem aparecer no JSON
  - cidade
  - regiao
  - lat/lng
  - fonte: "manual/osm-like" = coordenada aproximada validada manualmente
*/

window.ESTADIOS_CHILE = [
  {
    nome: "Estadio Nacional Julio Martínez Prádanos",
    aliases: ["estadio nacional", "nacional julio martínez", "nacional julio martinez", "nacional"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.4649,
    lng: -70.6107,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Monumental David Arellano",
    aliases: ["estadio monumental", "monumental david arellano", "monumental", "estadio de colo colo"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.5065,
    lng: -70.6055,
    fonte: "manual/osm-like"
  },
  {
    nome: "Claro Arena / San Carlos de Apoquindo",
    aliases: ["claro arena", "san carlos de apoquindo", "estadio san carlos de apoquindo"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.3960,
    lng: -70.5018,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Santa Laura Universidad SEK",
    aliases: ["santa laura", "estadio santa laura", "santa laura universidad sek"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.4046,
    lng: -70.6590,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de La Cisterna",
    aliases: ["la cisterna", "municipal de la cisterna", "estadio municipal de la cisterna"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.5210,
    lng: -70.6730,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Bicentenario de La Florida",
    aliases: ["bicentenario de la florida", "la florida", "estadio bicentenario la florida", "estadio bicentenario de la florida", "municipal de la florida"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.5408,
    lng: -70.5783,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de La Pintana",
    aliases: ["la pintana", "municipal de la pintana", "estadio municipal de la pintana"],
    cidade: "Santiago",
    regiao: "Región Metropolitana",
    lat: -33.5852,
    lng: -70.6346,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Santiago Bueras",
    aliases: ["santiago bueras", "estadio santiago bueras", "municipal santiago bueras"],
    cidade: "Maipú",
    regiao: "Región Metropolitana",
    lat: -33.5098,
    lng: -70.7583,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal Luis Navarro Avilés",
    aliases: ["municipal de san bernardo", "san bernardo", "estadio municipal san bernardo", "luis navarro avilés", "luis navarro aviles", "san bernardo luis navarro", "alcalde luis navarro avilés"],
    cidade: "San Bernardo",
    regiao: "Región Metropolitana",
    lat: -33.5945,
    lng: -70.6903,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de Lo Barnechea",
    aliases: ["lo barnechea", "municipal de lo barnechea", "estadio municipal de lo barnechea"],
    cidade: "Lo Barnechea",
    regiao: "Región Metropolitana",
    lat: -33.3506,
    lng: -70.5184,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Sausalito",
    aliases: ["sausalito", "estadio sausalito"],
    cidade: "Viña del Mar",
    regiao: "Valparaíso",
    lat: -33.0145,
    lng: -71.5355,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Elías Figueroa Brander",
    aliases: ["elías figueroa", "elias figueroa", "playa ancha", "estadio playa ancha", "estadio elías figueroa brander"],
    cidade: "Valparaíso",
    regiao: "Valparaíso",
    lat: -33.0223,
    lng: -71.6400,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Lucio Fariña Fernández",
    aliases: ["lucio fariña", "lucio farina", "municipal lucio fariña fernández", "municipal lucio farina fernandez", "estadio lucio fariña"],
    cidade: "Quillota",
    regiao: "Valparaíso",
    lat: -32.8836,
    lng: -71.2481,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Nicolás Chahuán Nazar",
    aliases: ["nicolás chahuán", "nicolas chahuan", "estadio nicolás chahuán", "estadio nicolas chahuan"],
    cidade: "La Calera",
    regiao: "Valparaíso",
    lat: -32.7931,
    lng: -71.2087,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Regional de Los Andes",
    aliases: ["regional de los andes", "estadio regional de los andes", "los andes"],
    cidade: "Los Andes",
    regiao: "Valparaíso",
    lat: -32.8353,
    lng: -70.5983,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de Cartagena",
    aliases: ["municipal de cartagena", "cartagena", "estadio municipal cartagena"],
    cidade: "Cartagena",
    regiao: "Valparaíso",
    lat: -33.5527,
    lng: -71.6059,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de Concón",
    aliases: ["municipal de concón", "municipal de concon", "concon", "concón"],
    cidade: "Concón",
    regiao: "Valparaíso",
    lat: -32.9306,
    lng: -71.5186,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Francisco Sánchez Rumoroso",
    aliases: ["francisco sánchez rumoroso", "francisco sanchez rumoroso", "sánchez rumoroso", "sanchez rumoroso", "estadio municipal francisco sánchez rumoroso", "estadio municipal francisco sanchez rumoroso"],
    cidade: "Coquimbo",
    regiao: "Coquimbo",
    lat: -29.9647,
    lng: -71.3387,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio La Portada",
    aliases: ["la portada", "estadio la portada"],
    cidade: "La Serena",
    regiao: "Coquimbo",
    lat: -29.9078,
    lng: -71.2520,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Diaguita",
    aliases: ["diaguita", "estadio diaguita", "estadio municipal diaguita"],
    cidade: "Ovalle",
    regiao: "Coquimbo",
    lat: -30.6030,
    lng: -71.2055,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio El Teniente / Codelco El Teniente",
    aliases: ["el teniente", "estadio el teniente", "estadio codelco el teniente", "codelco el teniente"],
    cidade: "Rancagua",
    regiao: "O'Higgins",
    lat: -34.1778,
    lng: -70.7380,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal Jorge Silva Valenzuela",
    aliases: ["jorge silva valenzuela", "san fernando", "estadio municipal jorge silva valenzuela"],
    cidade: "San Fernando",
    regiao: "O'Higgins",
    lat: -34.5847,
    lng: -70.9901,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal Joaquín Muñoz García",
    aliases: ["joaquín muñoz garcía", "joaquin munoz garcia", "santa cruz", "estadio municipal de santa cruz"],
    cidade: "Santa Cruz",
    regiao: "O'Higgins",
    lat: -34.6381,
    lng: -71.3619,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Fiscal de Talca",
    aliases: ["fiscal de talca", "estadio fiscal de talca"],
    cidade: "Talca",
    regiao: "Maule",
    lat: -35.4264,
    lng: -71.6669,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal Tucapel Bustamante Lastra",
    aliases: ["tucapel bustamante", "municipal de linares", "linares", "estadio municipal de linares"],
    cidade: "Linares",
    regiao: "Maule",
    lat: -35.8463,
    lng: -71.5919,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Fiscal Manuel Moya Medel",
    aliases: ["manuel moya medel", "cauquenes", "fiscal manuel moya medel"],
    cidade: "Cauquenes",
    regiao: "Maule",
    lat: -35.9697,
    lng: -72.3220,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Bicentenario Nelson Oyarzún Arenas",
    aliases: ["nelson oyarzún", "nelson oyarzun", "bicentenario nelson oyarzún", "bicentenario nelson oyarzun", "estadio bicentenario nelson oyarzún"],
    cidade: "Chillán",
    regiao: "Ñuble",
    lat: -36.6183,
    lng: -72.1078,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Ester Roa Rebolledo",
    aliases: ["ester roa", "ester roa rebolledo", "ester roa de concepción", "ester roa de concepcion", "estadio ester roa rebolledo"],
    cidade: "Concepción",
    regiao: "Biobío",
    lat: -36.8149,
    lng: -73.0238,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Huachipato / CAP Acero",
    aliases: ["estadio huachipato", "huachipato", "estadio cap", "cap acero", "estadio cap acero"],
    cidade: "Talcahuano",
    regiao: "Biobío",
    lat: -36.7542,
    lng: -73.1079,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de Los Ángeles",
    aliases: ["municipal de los ángeles", "municipal de los angeles", "los ángeles", "los angeles", "estadio municipal de los ángeles"],
    cidade: "Los Ángeles",
    regiao: "Biobío",
    lat: -37.4666,
    lng: -72.3522,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Federico Schwager",
    aliases: ["federico schwager", "coronel", "estadio federico schwager"],
    cidade: "Coronel",
    regiao: "Biobío",
    lat: -37.0286,
    lng: -73.1447,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio El Morro",
    aliases: ["el morro", "estadio el morro"],
    cidade: "Talcahuano",
    regiao: "Biobío",
    lat: -36.7214,
    lng: -73.1161,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Las Golondrinas",
    aliases: ["las golondrinas", "municipal las golondrinas", "hualpén", "hualpen"],
    cidade: "Hualpén",
    regiao: "Biobío",
    lat: -36.7817,
    lng: -73.1080,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Germán Becker",
    aliases: ["germán becker", "german becker", "estadio germán becker"],
    cidade: "Temuco",
    regiao: "La Araucanía",
    lat: -38.7427,
    lng: -72.6197,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de Villarrica",
    aliases: ["municipal de villarrica", "villarrica"],
    cidade: "Villarrica",
    regiao: "La Araucanía",
    lat: -39.2796,
    lng: -72.2273,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Parque Municipal de Valdivia",
    aliases: ["parque municipal de valdivia", "municipal de valdivia", "valdivia"],
    cidade: "Valdivia",
    regiao: "Los Ríos",
    lat: -39.8194,
    lng: -73.2442,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Chinquihue",
    aliases: ["chinquihue", "estadio chinquihue"],
    cidade: "Puerto Montt",
    regiao: "Los Lagos",
    lat: -41.4752,
    lng: -72.9396,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Rubén Marcos Peralta",
    aliases: ["rubén marcos", "ruben marcos", "estadio rubén marcos peralta", "estadio ruben marcos peralta"],
    cidade: "Osorno",
    regiao: "Los Lagos",
    lat: -40.5747,
    lng: -73.1335,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Zorros del Desierto",
    aliases: ["zorros del desierto", "municipal de calama", "estadio zorros del desierto"],
    cidade: "Calama",
    regiao: "Antofagasta",
    lat: -22.4567,
    lng: -68.9241,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Regional Calvo y Bascuñán",
    aliases: ["calvo y bascuñán", "calvo y bascunan", "regional calvo y bascuñán", "regional de antofagasta", "estadio regional calvo y bascuñán"],
    cidade: "Antofagasta",
    regiao: "Antofagasta",
    lat: -23.6701,
    lng: -70.4046,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio El Cobre",
    aliases: ["el cobre", "estadio el cobre"],
    cidade: "El Salvador",
    regiao: "Atacama",
    lat: -26.3403,
    lng: -70.6247,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Luis Valenzuela Hermosilla",
    aliases: ["luis valenzuela hermosilla", "estadio luis valenzuela hermosilla"],
    cidade: "Copiapó",
    regiao: "Atacama",
    lat: -27.3662,
    lng: -70.3323,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Tierra de Campeones Ramón Estay Saavedra",
    aliases: ["tierra de campeones", "estadio tierra de campeones"],
    cidade: "Iquique",
    regiao: "Tarapacá",
    lat: -20.2441,
    lng: -70.1350,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Carlos Dittborn",
    aliases: ["carlos dittborn", "estadio carlos dittborn", "dittborn", "estadio regional de arica", "regional de arica"],
    cidade: "Arica",
    regiao: "Arica y Parinacota",
    lat: -18.4876,
    lng: -70.2991,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Bicentenario La Granja",
    aliases: ["la granja", "estadio la granja", "estadio bicentenario la granja", "bicentenario la granja"],
    cidade: "Curicó",
    regiao: "Maule",
    lat: -34.9744,
    lng: -71.2307,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal Leonel Sánchez Lineros",
    aliases: ["leonel sanchez", "leonel sánchez", "municipal de recoleta", "estadio municipal de recoleta", "estadio municipal de recoleta leonel sánchez", "recoleta"],
    cidade: "Recoleta",
    regiao: "Región Metropolitana",
    lat: -33.3994,
    lng: -70.6416,
    fonte: "manual/osm-like"
  },
  {
    nome: "Estadio Municipal de Mejillones",
    aliases: ["municipal de mejillones"],
    cidade: "Mejillones",
    regiao: "Antofagasta",
    lat: -23.0997,
    lng: -70.4453,
    fonte: "manual/aproximado (cidade de Mejillones)",
  },
  {
    nome: "Estadio Augusto Rodríguez de San Vicente de Tagua Tagua",
    aliases: ["augusto rodriguez", "san vicente de tagua tagua"],
    cidade: "San Vicente de Tagua Tagua",
    regiao: "O'Higgins",
    lat: -34.4436,
    lng: -71.0472,
    fonte: "manual/aproximado (cidade de San Vicente de Tagua Tagua)",
  },
  {
    nome: "Estadio Municipal de San Felipe",
    aliases: ["municipal de san felipe"],
    cidade: "San Felipe",
    regiao: "Valparaíso",
    lat: -32.7500,
    lng: -70.7247,
    fonte: "manual/aproximado (cidade de San Felipe)",
  },
  {
    nome: "Estadio Turingia",
    aliases: ["turingia"],
    cidade: "Temuco",
    regiao: "Araucanía",
    lat: -38.7359,
    lng: -72.5904,
    fonte: "manual/aproximado (setor Turingia, Temuco)",
  },
  {
    nome: "Fiscal Talca",
    aliases: ["fiscal talca", "estadio fiscal de talca"],
    cidade: "Talca",
    regiao: "Maule",
    lat: -35.4264,
    lng: -71.6554,
    fonte: "manual/aproximado (cidade de Talca)",
  },
  {
    nome: "Estadio Municipal de Puente Alto",
    aliases: ["municipal de puente alto"],
    cidade: "Puente Alto",
    regiao: "Metropolitana",
    lat: -33.6119,
    lng: -70.5756,
    fonte: "manual/aproximado (cidade de Puente Alto)",
  },
  {
    nome: "Estadio Universidad de Atacama",
    aliases: ["universidad de atacama"],
    cidade: "Copiapó",
    regiao: "Atacama",
    lat: -27.3668,
    lng: -70.3314,
    fonte: "manual/aproximado (Copiapó, campus da Universidad de Atacama)",
  },
  {
    nome: "Estadio Labranza",
    aliases: ["labranza"],
    cidade: "Temuco",
    regiao: "Araucanía",
    lat: -38.6975,
    lng: -72.6608,
    fonte: "manual/aproximado (setor Labranza, Temuco)",
  },
  {
    nome: "Estadio Municipal De Pichidegua",
    aliases: ["municipal de pichidegua"],
    cidade: "Pichidegua",
    regiao: "O'Higgins",
    lat: -34.3606,
    lng: -71.2967,
    fonte: "manual/aproximado (cidade de Pichidegua)",
  },
  {
    nome: "Estadio Liceo Pablo Neruda de Temuco",
    aliases: ["liceo pablo neruda"],
    cidade: "Temuco",
    regiao: "Araucanía",
    lat: -38.7359,
    lng: -72.5904,
    fonte: "manual/aproximado (cidade de Temuco)",
  },
  {
    nome: "Estadio Soinca Bata Melipilla",
    aliases: ["soinca bata melipilla", "soinca melipilla"],
    cidade: "Melipilla",
    regiao: "Metropolitana",
    lat: -33.6906,
    lng: -71.2144,
    fonte: "manual/aproximado (cidade de Melipilla)",
  },
  {
    nome: "Estadio Soinca – Cancha 2",
    aliases: ["soinca cancha 2", "soinca – cancha 2"],
    cidade: "Melipilla",
    regiao: "Metropolitana",
    lat: -33.6906,
    lng: -71.2144,
    fonte: "manual/aproximado (mesmo complexo do Soinca Bata, Melipilla)",
  },
  {
    nome: "Estadio Universidad del Bio Bio",
    aliases: ["universidad del bio bio", "universidad del bío bío"],
    cidade: "Concepción",
    regiao: "Biobío",
    lat: -36.8270,
    lng: -73.0444,
    fonte: "manual/aproximado (campus Concepción da UBB)",
  },
  {
    nome: "Estadio Municipal de San Clemente",
    aliases: ["municipal de san clemente"],
    cidade: "San Clemente",
    regiao: "Maule",
    lat: -35.5397,
    lng: -71.4919,
    fonte: "manual/aproximado (cidade de San Clemente)",
  },
  {
    nome: "Estadio Costanera",
    aliases: ["costanera"],
    cidade: "Limache",
    regiao: "Valparaíso",
    lat: -33.0089,
    lng: -71.2661,
    fonte: "manual/aproximado (cidade de Limache — mandante Deportes Limache)",
  },
  {
    nome: "Estadio Municipal de San Joaquín",
    aliases: ["municipal de san joaquin", "san joaquin"],
    cidade: "Santiago (San Joaquín)",
    regiao: "Región Metropolitana",
    lat: -33.4913,
    lng: -70.6220,
    fonte: "manual/aproximado (comuna San Joaquín — mandantes Aguará y Rodelindo Román)",
  },
  {
    nome: "Estadio Municipal de Chimbarongo",
    aliases: ["municipal de chimbarongo", "mun. de chimbarongo", "mun de chimbarongo"],
    cidade: "Chimbarongo",
    regiao: "O'Higgins",
    lat: -34.7167,
    lng: -71.0333,
    fonte: "manual/aproximado (cidade de Chimbarongo — mandante Chimbarongo FC)",
  },
  {
    nome: "Estadio Luis Figueroa",
    aliases: ["luis figueroa", "estadio municipal luis figueroa"],
    cidade: "Cabrero",
    regiao: "Biobío",
    lat: -37.0333,
    lng: -72.4000,
    fonte: "manual/aproximado (cidade de Cabrero — mandante Comunal Cabrero)",
  },
  {
    nome: "Estadio Enrique Donn",
    aliases: ["enrique donn"],
    cidade: "Constitución",
    regiao: "Maule",
    lat: -35.3333,
    lng: -72.4167,
    fonte: "manual/aproximado (cidade de Constitución — mandante Constitución Unido)",
  },
  {
    nome: "Estadio Municipal Patricio Mekis",
    aliases: ["municipal patricio mekis", "patricio mekis"],
    cidade: "Rancagua",
    regiao: "O'Higgins",
    lat: -34.1708,
    lng: -70.7444,
    fonte: "manual/aproximado (cidade de Rancagua — mandante Deportes Rancagua)",
  },
  {
    nome: "Estadio Municipal de Peñalolén",
    aliases: ["municipal de penalolen", "municipal de peñalolén", "mun. de penalolen", "mun de penalolen"],
    cidade: "Santiago (Peñalolén)",
    regiao: "Región Metropolitana",
    lat: -33.4833,
    lng: -70.5333,
    fonte: "manual/aproximado (comuna Peñalolén — mandante Futuro FC)",
  },
  {
    nome: "Estadio El Alto",
    aliases: ["el alto", "el alto de nueva imperial"],
    cidade: "Nueva Imperial",
    regiao: "La Araucanía",
    lat: -38.7444,
    lng: -72.9500,
    fonte: "manual/aproximado (cidade de Nueva Imperial — mandante Imperial Unido)",
  },
  {
    nome: "Estadio Lautaro de Buin",
    aliases: ["lautaro de buin"],
    cidade: "Buin",
    regiao: "Región Metropolitana",
    lat: -33.7333,
    lng: -70.7500,
    fonte: "manual/aproximado (cidade de Buin — mandante Lautaro de Buin)",
  },
  {
    nome: "Estadio Municipal Alberto Larraguibel",
    aliases: ["municipal alberto larraguibel", "alberto larraguibel morales"],
    cidade: "Angol",
    regiao: "La Araucanía",
    lat: -37.8000,
    lng: -72.7167,
    fonte: "manual/aproximado (cidade de Angol — mandante Malleco Unido)",
  },
  {
    nome: "Estadio Raúl Vargas",
    aliases: ["raul vargas", "mun. de quintero raul vargas verdejo", "municipal de quintero raul vargas verdejo"],
    cidade: "Quintero",
    regiao: "Valparaíso",
    lat: -32.7833,
    lng: -71.5333,
    fonte: "manual/aproximado (cidade de Quintero — mandante Quintero Unido)",
  },
  {
    nome: "Estadio Rolando Cortés",
    aliases: ["rolando cortes", "mun. de mejillones", "mun de mejillones"],
    cidade: "Mejillones",
    regiao: "Antofagasta",
    lat: -23.1000,
    lng: -70.4500,
    fonte: "manual/aproximado (cidade de Mejillones — mandante Municipal Mejillones)",
  },
  {
    nome: "Estadio Luis Valenzuela",
    aliases: ["luis valenzuela"],
    cidade: "Copiapó",
    regiao: "Atacama",
    lat: -27.3668,
    lng: -70.3323,
    fonte: "manual/aproximado (cidade de Copiapó — mandantes Audax Italiano de Paipote e CEFF Copiapó)",
  },
  {
    nome: "Estadio Nelson Rojas",
    aliases: ["nelson rojas", "mun. nelson rojas"],
    cidade: "Vallenar",
    regiao: "Atacama",
    lat: -28.5708,
    lng: -70.7581,
    fonte: "manual/aproximado (cidade de Vallenar — mandante Deportes Vallenar)",
  },
  {
    nome: "Estadio Olímpico Cuyuncaví",
    aliases: ["olimpico cuyuncavi", "olimpico de cuyuncavi"],
    cidade: "Curacaví",
    regiao: "Región Metropolitana",
    lat: -33.4167,
    lng: -71.1333,
    fonte: "manual/aproximado (cidade de Curacaví — mandante Curacaví FC)",
  },
  {
    nome: "Estadio Municipal de Conchalí",
    aliases: ["municipal de conchali"],
    cidade: "Santiago (Conchalí)",
    regiao: "Región Metropolitana",
    lat: -33.3833,
    lng: -70.6667,
    fonte: "manual/aproximado (comuna Conchalí — mandante EFC Conchalí)",
  },
  {
    nome: "Estadio Los Jardines",
    aliases: ["los jardines", "mun. los jardines"],
    cidade: "Padre Hurtado",
    regiao: "Región Metropolitana",
    lat: -33.5667,
    lng: -70.8167,
    fonte: "manual/aproximado (cidade de Padre Hurtado — mandante Julio Covarrubias)",
  },
  {
    nome: "Estadio Lucas Pacheco",
    aliases: ["lucas pacheco"],
    cidade: "Talagante",
    regiao: "Región Metropolitana",
    lat: -33.6667,
    lng: -70.9333,
    fonte: "manual/aproximado (cidade de Talagante — mandante Provincial Talagante)",
  },
  {
    nome: "Estadio Municipal de Paine",
    aliases: ["municipal de paine"],
    cidade: "Paine",
    regiao: "Región Metropolitana",
    lat: -33.8083,
    lng: -70.7414,
    fonte: "manual/aproximado (cidade de Paine — mandante Tricolor Municipal)",
  },
  {
    nome: "Estadio Lo Blanco",
    aliases: ["lo blanco", "mun. lo blanco"],
    cidade: "Santiago (El Bosque)",
    regiao: "Región Metropolitana",
    lat: -33.5667,
    lng: -70.6750,
    fonte: "manual/aproximado (comuna El Bosque — mandante Gasparín FC)",
  },
  {
    nome: "Estadio Municipal de Pumanque",
    aliases: ["municipal de pumanque", "mun. de pumanque"],
    cidade: "Pumanque",
    regiao: "O'Higgins",
    lat: -34.5000,
    lng: -71.5833,
    fonte: "manual/aproximado (cidade de Pumanque — mandante Deportivo Pumanque)",
  },
  {
    nome: "Estadio Nelson Valenzuela",
    aliases: ["nelson valenzuela"],
    cidade: "Parral",
    regiao: "Maule",
    lat: -36.1439,
    lng: -71.8261,
    fonte: "manual/aproximado (cidade de Parral — mandante Buenos Aires)",
  },
  {
    nome: "Estadio Facela",
    aliases: ["facela"],
    cidade: "Laja",
    regiao: "Biobío",
    lat: -37.2833,
    lng: -72.7167,
    fonte: "manual/aproximado (cidade de Laja — mandante Deportes Laja Histórico)",
  },
  {
    nome: "Estadio Municipal de Nacimiento",
    aliases: ["municipal de nacimiento"],
    cidade: "Nacimiento",
    regiao: "Biobío",
    lat: -37.5000,
    lng: -72.6667,
    fonte: "manual/aproximado (cidade de Nacimiento — mandante Nacimiento CDSC)",
  },
  {
    nome: "Estadio Municipal de Hualqui",
    aliases: ["municipal de hualqui", "mun. de hualqui"],
    cidade: "Hualqui",
    regiao: "Biobío",
    lat: -36.9833,
    lng: -72.9333,
    fonte: "manual/aproximado (cidade de Hualqui — mandante República Independiente)",
  },
  {
    nome: "Estadio Municipal de Florida",
    aliases: ["municipal de florida"],
    cidade: "Concepción (Florida)",
    regiao: "Biobío",
    lat: -36.9333,
    lng: -72.8667,
    fonte: "manual/aproximado (comuna Florida, Concepción — mandante Inter Concepción)",
  },
  {
    nome: "Estadio Félix Gallardo",
    aliases: ["felix gallardo"],
    cidade: "Valdivia",
    regiao: "Los Ríos",
    lat: -39.8142,
    lng: -73.2459,
    fonte: "manual/aproximado (cidade de Valdivia — mandante Deportes Valdivia)",
  },
  {
    nome: "Estadio Municipal de Paillaco",
    aliases: ["municipal de paillaco"],
    cidade: "Paillaco",
    regiao: "Los Ríos",
    lat: -40.0667,
    lng: -72.8833,
    fonte: "manual/aproximado (cidade de Paillaco — mandante Municipal Paillaco)",
  },
  {
    nome: "Estadio Olímpico Gómez Carreño",
    aliases: ["olimpico gomez carreno", "gomez carreno"],
    cidade: "Viña del Mar",
    regiao: "Valparaíso",
    lat: -33.0244,
    lng: -71.5644,
    fonte: "manual/aproximado (cidade de Viña del Mar — cancha de semana de Unión Glorias Navales; a Wikipédia lista Sausalito como estádio oficial do clube, usado em jogos pontuais)",
  },
  {
    nome: "Estadio San Gregorio",
    aliases: ["san gregorio", "san gregorio la granja", "municipal san gregorio"],
    cidade: "Santiago (La Granja)",
    regiao: "Región Metropolitana",
    lat: -33.5453,
    lng: -70.6297,
    fonte: "manual/aproximado (comuna La Granja — visto em cf3.cl como mandante Rodelindo Román; Wikipédia lista Municipal de San Joaquín como estádio oficial do clube)",
  },
  {
    nome: "Estadio Municipal Santa Ana",
    aliases: ["municipal santa ana", "santa ana"],
    cidade: "Santa Cruz",
    regiao: "O'Higgins",
    lat: -34.6383,
    lng: -71.3667,
    fonte: "manual/aproximado (cidade de Santa Cruz — mandante Deportes Santa Cruz)",
  },
  {
    nome: "Estadio Gustavo Ocaranza",
    aliases: ["gustavo ocaranza"],
    cidade: "Limache",
    regiao: "Valparaíso",
    lat: -33.0122,
    lng: -71.2622,
    fonte: "manual/aproximado (cidade de Limache — mandante Deportes Limache, categoria juvenil/femenina)",
  },
  {
    nome: "Estadio Manuel Rojas del Río",
    aliases: ["manuel rojas del rio", "manuel rojas del río"],
    cidade: "Colina",
    regiao: "Región Metropolitana",
    lat: -33.2000,
    lng: -70.6742,
    fonte: "manual/aproximado (cidade de Colina — mandante Atlético Colina)",
  },
  {
    nome: "Estadio Municipal de Melipilla",
    aliases: ["municipal de melipilla"],
    cidade: "Melipilla",
    regiao: "Región Metropolitana",
    lat: -33.6833,
    lng: -71.2167,
    fonte: "manual/aproximado (cidade de Melipilla — mandante Deportes Melipilla)",
  },
  {
    nome: "Estadio Parque Los Batros",
    aliases: ["parque los batros", "los batros"],
    cidade: "San Pedro de la Paz",
    regiao: "Región del Biobío",
    lat: -36.8410,
    lng: -73.1067,
    fonte: "manual/aproximado (cidade de San Pedro de la Paz)",
  },
  {
    nome: "Estadio Independiente de Bollenar",
    aliases: ["independiente de bollenar", "bollenar"],
    cidade: "Melipilla",
    regiao: "Región Metropolitana",
    lat: -33.6906,
    lng: -71.2158,
    fonte: "manual/aproximado (localidade de Bollenar, comuna de Melipilla)",
  },
  {
    nome: "Estadio Tegualda",
    aliases: ["tegualda"],
    cidade: "Chol Chol",
    regiao: "Región de La Araucanía",
    lat: -38.5989,
    lng: -72.9711,
    fonte: "manual/aproximado (cidade de Chol Chol)",
  },
  {
    nome: "Estadio Venecia",
    aliases: ["venecia"],
    cidade: "Temuco",
    regiao: "Región de La Araucanía",
    lat: -38.7359,
    lng: -72.5904,
    fonte: "manual/aproximado (cidade de Temuco — Deporte Municipal Temuco)",
  },
  {
    nome: "Estadio Eladio Rojas",
    aliases: ["eladio rojas", "eladio rojas diaz", "eladio rojas díaz"],
    cidade: "Tierra Amarilla",
    regiao: "Región de Atacama",
    lat: -27.4783,
    lng: -70.2661,
    fonte: "manual/aproximado (cidade de Tierra Amarilla)",
  },
  {
    nome: "Estadio Municipal El Bajio",
    aliases: ["municipal el bajio", "municipal el bajío", "el bajio"],
    cidade: "Quillota",
    regiao: "Región de Valparaíso",
    lat: -32.8824,
    lng: -71.2489,
    fonte: "manual/aproximado (sinal fraco: clube 'Juventud El Bajío' aparece em torneios da zona de Quillota — conferir se bater errado)",
  },
  {
    nome: "Estadio Municipal Roberto Echeverría Boutaud",
    aliases: ["roberto echeverria boutaud", "roberto echeverría boutaud", "echeverria boutaud"],
    cidade: "Cunco",
    regiao: "Región de La Araucanía",
    lat: -38.9236,
    lng: -72.0303,
    fonte: "manual/aproximado (cidade de Cunco)",
  },
];
