/*
  Base de estádios do futebol boliviano (Liga Profesional Boliviana,
  Copa Bolivia).
*/

window.ESTADIOS_BOLIVIA = [
  {
    nome: "Estadio Hernando Siles",
    aliases: ["hernando siles"],
    cidade: "La Paz",
    regiao: "La Paz",
    lat: -16.5309,
    lng: -68.1193,
  },
  {
    nome: "Estadio Félix Capriles",
    aliases: ["felix capriles", "félix capriles"],
    cidade: "Cochabamba",
    regiao: "Cochabamba",
    lat: -17.3895,
    lng: -66.1568,
    fonte: "manual/aproximado (cidade de Cochabamba)",
  },
  {
    nome: "Estadio Gilberto Parada",
    aliases: ["gilberto parada"],
    cidade: "Montero",
    regiao: "Santa Cruz",
    lat: -17.3395,
    lng: -63.2517,
    fonte: "manual/aproximado (cidade de Montero)",
  },
  {
    nome: "Estadio IV Centenário",
    aliases: ["iv centenario", "iv centenário"],
    cidade: "Tarija",
    regiao: "Tarija",
    lat: -21.5355,
    lng: -64.7296,
    fonte: "manual/aproximado (cidade de Tarija)",
  },
  {
    nome: "Estadio Jesús Bermúdez",
    aliases: ["jesus bermudez", "jesús bermúdez"],
    cidade: "Oruro",
    regiao: "Oruro",
    lat: -17.9833,
    lng: -67.1500,
    fonte: "manual/aproximado (cidade de Oruro)",
  },
  {
    nome: "Estadio Olímpico Patria",
    aliases: ["olimpico patria", "olímpico patria", "estadio patria"],
    cidade: "Sucre",
    regiao: "Chuquisaca",
    lat: -19.0333,
    lng: -65.2627,
    fonte: "manual/aproximado (Sucre — a ESPN às vezes rotula a cidade errada como Cochabamba para este estádio)",
  },
  {
    nome: "Estadio Ramón Tahuichi (Aguilera)",
    aliases: ["ramon tahuichi", "ramón tahuichi", "tahuichi aguilera"],
    cidade: "Santa Cruz de la Sierra",
    regiao: "Santa Cruz",
    lat: -17.7833,
    lng: -63.1821,
    fonte: "manual/aproximado (cidade de Santa Cruz de la Sierra)",
  },
  {
    nome: "Estadio Víctor Agustín Ugarte",
    aliases: ["victor agustin ugarte", "víctor agustín ugarte"],
    cidade: "Potosí",
    regiao: "Potosí",
    lat: -19.5836,
    lng: -65.7531,
    fonte: "manual/aproximado (cidade de Potosí)",
  },
  {
    nome: "Estadio Municipal Villa Ingenio",
    aliases: ["municipal villa ingenio", "villa ingenio"],
    cidade: "El Alto",
    regiao: "La Paz",
    lat: -16.5000,
    lng: -68.1500,
    fonte: "manual/aproximado (El Alto, La Paz)",
  },
];
