/*
  Base de estádios do futebol equatoriano (LigaPro Serie A / Serie B).

  Nota: a ESPN rotula erroneamente alguns estádios de Guayaquil (Banco
  Pichincha, do Barcelona SC, e George Capwell, do Emelec) com
  cidade="Quito" no campo próprio. Aqui usamos a cidade real
  (Guayaquil) em vez de confiar cegamente nesse campo da fonte.
*/

window.ESTADIOS_ECUADOR = [
  {
    nome: "Estadio Rodrigo Paz Delgado (Casa Blanca)",
    aliases: ["rodrigo paz delgado", "casa blanca"],
    cidade: "Quito",
    regiao: "Pichincha",
    lat: -0.1858,
    lng: -78.4783,
    fonte: "manual/aproximado (Quito, Equador)",
  },
  {
    nome: "Estadio Banco Guayaquil",
    aliases: ["banco guayaquil", "estadio idv"],
    cidade: "Quito",
    regiao: "Pichincha",
    lat: -0.4014,
    lng: -78.4517,
    fonte: "manual/aproximado (Sangolquí/Amaguaña, região de Quito)",
  },
  {
    nome: "Estadio Banco Pichincha",
    aliases: ["banco pichincha", "monumental banco pichincha", "estadio monumental isidro romero carbo"],
    cidade: "Guayaquil",
    regiao: "Guayas",
    lat: -2.1608,
    lng: -79.9224,
    fonte: "manual/aproximado (Guayaquil — mandante Barcelona SC; a ESPN rotula erradamente como Quito)",
  },
  {
    nome: "Estadio George Capwell",
    aliases: ["george capwell", "banco del austro (guayaquil)"],
    cidade: "Guayaquil",
    regiao: "Guayas",
    lat: -2.1886,
    lng: -79.9013,
    fonte: "manual/aproximado (Guayaquil — mandante Emelec; a ESPN rotula erradamente como Quito)",
  },
  {
    nome: "Estadio Olímpico Atahualpa",
    aliases: ["olimpico atahualpa", "olímpico atahualpa"],
    cidade: "Quito",
    regiao: "Pichincha",
    lat: -0.1961,
    lng: -78.4842,
    fonte: "manual/aproximado (Quito, Equador)",
  },
  {
    nome: "Estadio Gonzalo Pozo Ripalda",
    aliases: ["gonzalo pozo ripalda"],
    cidade: "Quito",
    regiao: "Pichincha",
    lat: -0.1500,
    lng: -78.4700,
    fonte: "manual/aproximado (Quito — mandante Aucas)",
  },
  {
    nome: "Estadio Christian Benítez Betancourt",
    aliases: ["christian benitez betancourt", "christian benítez betancourt"],
    cidade: "Quito",
    regiao: "Pichincha",
    lat: -0.1807,
    lng: -78.4678,
    fonte: "manual/aproximado (cidade de Quito)",
  },
  {
    nome: "Banco del Austro Alejandro Serrano Aguilar",
    aliases: ["alejandro serrano aguilar", "banco del austro alejandro serrano"],
    cidade: "Cuenca",
    regiao: "Azuay",
    lat: -2.9006,
    lng: -79.0045,
    fonte: "manual/aproximado (cidade de Cuenca — mandante Deportivo Cuenca)",
  },
  {
    nome: "Estadio 9 de Mayo",
    aliases: ["9 de mayo"],
    cidade: "Machala",
    regiao: "El Oro",
    lat: -3.2581,
    lng: -79.9553,
    fonte: "manual/aproximado (cidade de Machala)",
  },
  {
    nome: "Estadio Bellavista",
    aliases: ["bellavista"],
    cidade: "Ambato",
    regiao: "Tungurahua",
    lat: -1.2543,
    lng: -78.6229,
    fonte: "manual/aproximado (cidade de Ambato — mandante Macará)",
  },
  {
    nome: "Estadio COAC Mushuc Runa",
    aliases: ["coac mushuc runa", "mushuc runa estadio"],
    cidade: "Ambato",
    regiao: "Tungurahua",
    lat: -1.2543,
    lng: -78.6229,
    fonte: "manual/aproximado (cidade de Ambato — mandante Mushuc Runa)",
  },
  {
    nome: "Estadio Federativo Reina del Cisne",
    aliases: ["federativo reina del cisne", "reina del cisne"],
    cidade: "Loja",
    regiao: "Loja",
    lat: -3.9931,
    lng: -79.2042,
    fonte: "manual/aproximado (cidade de Loja)",
  },
  {
    nome: "Estadio Jocay",
    aliases: ["jocay"],
    cidade: "Manta",
    regiao: "Manabí",
    lat: -0.9500,
    lng: -80.7333,
    fonte: "manual/aproximado (cidade de Manta — mandante Delfín)",
  },
  {
    nome: "Estadio Olímpico de Ibarra",
    aliases: ["olimpico de ibarra", "olímpico de ibarra"],
    cidade: "Ibarra",
    regiao: "Imbabura",
    lat: 0.3517,
    lng: -78.1223,
    fonte: "manual/aproximado (cidade de Ibarra)",
  },
];
